#!/usr/bin/env python3
"""Generate runtime tactic costs from original serializer trace, never from a web table."""
import argparse, hashlib, json
from pathlib import Path
from inspect_pc_effect_bindings import EXE_SHA

def export(source,java,audit):
    raw=source.read_bytes();report=json.loads(raw)
    if report['source_executable_sha256']!=EXE_SHA:raise ValueError('Unverified executable')
    shared=next(s for s in report['sources'] if s['path']=='Media/scenario/Scenario.s11')
    rows=[r for r in shared['records'] if r['kind']=='table_84858']
    if [r['native_index'] for r in rows]!=list(range(32)):raise ValueError('Incomplete native table')
    costs=[];evidence=[]
    for r in rows:
        read=next(x for x in r['reads'] if x['destination']=='actor+0x30')
        if read['bytes']!=1:raise ValueError('Changed field format')
        cost=bytes.fromhex(r['actor_hex'])[0x30]
        if bytes.fromhex(r['raw_hex'])[read['offset']-r['offset']]!=cost:raise ValueError('Source/actor mismatch')
        costs.append(cost);evidence.append(dict(native_index=r['native_index'],cost=cost,source_offset=read['offset'],record_sha256=r['sha256']))
    text='''package game.sanguo.core;

/** Generated by tools/content/export_pc_tactic_costs.py; native Scenario.s11 costs.
 * Getter4951a0, execution5a31d0 and debit58589c..5858b7 verified offline.
 * Native IDs are independent of project weapon/ship enum ordinals. */
final class PcTacticCosts {
    private PcTacticCosts() {}
    private static final int[] VALUES={%s};
    static int at(int nativeId) { return VALUES[nativeId]; }
}
''' % ','.join(map(str,costs))
    java.write_text(text)
    audit.write_text(json.dumps(dict(schema=1,executable_sha256=EXE_SHA,source_path=shared['path'],source_sha256=shared['sha256'],report_sha256=hashlib.sha256(raw).hexdigest(),records=evidence,execution='5a31d0 returns actor+30;58589c..5858b7 negates and passes to4964f0; no injected gameplay hooks',limits=['Bounded neutral-unit execution; full native battle/target validation not emulated','Shared installed data; optional external runtime patch activation remains unverified']),ensure_ascii=False,indent=2)+'\n')

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('source',type=Path);p.add_argument('--java',required=True,type=Path);p.add_argument('--audit',required=True,type=Path);a=p.parse_args();export(a.source,a.java,a.audit)
