package game.sanguo.mobile;
import game.sanguo.core.map.SourceGridCoord;

import android.app.*;
import android.content.*;
import android.os.*;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import game.sanguo.core.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

/** Production MapView + production map resolver; never receives the live campaign World. */
public final class MapEditorActivity extends Activity {
    private static final int EXPORT=6701,IMPORT=6702;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private MapLibrary library;
    private MapEditSession session;
    private MapHost map;
    private LinearLayout tools;
    private TextView coordinate,status;
    private ProgressBar progress;
    private boolean busy,destroyed,discardOnExit,drawing,grid,coords,passability,footprints=true;
    private int tab,radius;
    private String tool="连续画笔";
    private World.Terrain brush=World.Terrain.PLAIN;
    private Hex selected,lastStroke,rectangleStart;
    private Set<Hex> stroke=new LinkedHashSet<>();
    private MapPatch.Site placing;
    private String placingAction;
    private byte[] exporting;
    private final List<CustomMaps.Issue> issues=new ArrayList<>();
    private Bundle pendingCamera;
    @Override public void onCreate(Bundle state){super.onCreate(state);library=new MapLibrary(this);pendingCamera=state;build();work("读取独立草稿",()->new MapEditSession(library.draft()),s->{session=s;refresh("独立草稿，与当前战局隔离");if(pendingCamera!=null)map.restoreCamera(pendingCamera);else map.post(map::fit);});}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private TextView text(String value,int size){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(0xffe8e0c7);v.setPadding(dp(8),dp(4),dp(8),dp(4));return v;}
    private Button button(String label,Runnable run){Button b=CompactButtons.create(this);b.setText(label);b.setTextSize(11);b.setOnClickListener(v->{if(!busy&&session!=null)run.run();});return b;}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xff14252d);coordinate=text("地图编辑器 · 读取草稿",13);coordinate.setMaxLines(2);root.addView(coordinate);status=text("",11);status.setMaxLines(2);root.addView(status);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setIndeterminate(true);progress.setVisibility(View.GONE);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));
        map=new MapHost(this,this::tap);map.editorMode(this::strokeEvent);root.addView(map,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout tabs=new LinearLayout(this);root.addView(tabs);String[] names={"地形","据点","检查"};for(int i=0;i<names.length;i++){final int index=i;tabs.addView(button(names[i],()->{cancelPlacement();tab=index;toolbar();}),new LinearLayout.LayoutParams(0,dp(44),1));}
        HorizontalScrollView scrolling=new HorizontalScrollView(this);scrolling.setHorizontalScrollBarEnabled(false);tools=new LinearLayout(this);scrolling.addView(tools);root.addView(scrolling,new LinearLayout.LayoutParams(-1,dp(48)));
        LinearLayout common=new LinearLayout(this);root.addView(common);common.addView(button("撤销",()->change("撤销",()->{session.undo();return null;})),new LinearLayout.LayoutParams(0,dp(44),1));common.addView(button("重做",()->change("重做",()->{session.redo();return null;})),new LinearLayout.LayoutParams(0,dp(44),1));common.addView(button("定位",this::locate),new LinearLayout.LayoutParams(0,dp(44),1));common.addView(button("地图",this::libraryMenu),new LinearLayout.LayoutParams(0,dp(44),1));setContentView(root);toolbar();}
    private void toolbar(){tools.removeAllViews();add(map.is3D()?"切换2D":"切换3D",()->{map.switchMode(!map.is3D());toolbar();});add("回正",map::resetOrientation);add("视觉属性",this::visualProperties);if(tab==0){add(drawing?"绘制中":"浏览",()->{drawing=!drawing;rectangleStart=null;map.editorDrawing(drawing&&"连续画笔".equals(tool));toolbar();refresh(drawing?"绘制：单指操作；双指只平移/缩放":"浏览：单指平移，点击选格");});add(TerrainPresentation.of(brush).name(),this::chooseTerrain);add(tool,this::chooseTool);add("范围 "+(radius==0?"1格":radius==1?"7格":"19格"),()->{radius=(radius+1)%3;toolbar();});add("辅助层",this::layers);}
        else if(tab==1){add("新增",this::addSite);add("据点列表",this::siteList);add("属性",this::selectedProperties);add("移动",()->selectedSite(s->place(s,"移动")));add("复制",()->selectedSite(s->{try{place(s.copy(session.newId()),"复制");}catch(Exception e){error(e);}}));add("删除",()->selectedSite(this::deleteSite));add("取消放置",this::cancelPlacement);}
        else{add("检查地图",this::validateMap);add("诊断列表 "+issues.size(),this::showIssues);add("预览剧本",this::chooseScenario);add("主水系",this::waterInfo);add("辅助层",this::layers);add("全图",map::fit);}
        map.editorDrawing(tab==0&&drawing&&"连续画笔".equals(tool));}
    private void visualProperties(){
        if(selected==null||!session.world().inside(selected)){status.setText("先选中有效地块");return;}
        MapPatch patch=session.patch();SourceGridCoord source=MapCoordinates.nationalSource(session.world(),selected);int cell=source.x*200+source.y;
        World.City site=session.world().cityAt(selected);MapPatch.Appearance appearance=site==null?null:patch.appearances.get(site.id);
        LinearLayout form=form();form.addView(text("仅改变3D外观。水面和据点占地保持水平；地形重绘会清除此格高度。旧版应用不支持带视觉字段的格式2。",12));
        EditText height=input(form,"视觉高度 0—2600（千分之一格）",String.valueOf(patch.heights.getOrDefault(cell,60)),true);
        EditText variant=site==null?null:input(form,"城市模型变体 0—2",String.valueOf(appearance==null?0:appearance.variant()),true);
        EditText angle=site==null?null:input(form,"模型朝向 0—359度",String.valueOf(appearance==null?0:appearance.degrees()),true);
        new AlertDialog.Builder(this).setTitle("视觉属性 · 可撤销").setView(scroll(form)).setNegativeButton("取消",null).setNeutralButton("恢复默认",(d,n)->change("重置视觉",()->{MapPatch next=session.patch();next.heights.remove(cell);if(site!=null)next.appearances.remove(site.id);session.replace("重置视觉",next);return "已恢复默认外观";})).setPositiveButton("应用",(d,n)->{try{int h=number(height);if(h<0||h>2600)throw new IOException("高度必须在0—2600");MapPatch next=session.patch();next.heights.put(cell,h);if(site!=null){int v=number(variant),a=number(angle);if(v<0||v>2||a<0||a>359)throw new IOException("变体或朝向超出范围");next.appearances.put(site.id,new MapPatch.Appearance(v,a));}change("视觉属性",()->{session.replace("视觉属性",next);return "外观已更新；逻辑规则不变";});}catch(Exception e){error(e);}}).show();
    }
    private void add(String label,Runnable run){tools.addView(button(label,run),new LinearLayout.LayoutParams(-2,-1));}
    private void refresh(String message){if(session==null)return;World w=session.world();map.setWorld(w,selected,-1);map.editorLayers(grid,coords,passability,footprints);MapPatch p=session.patch();String at=selected!=null&&w.sourceInside(selected)?MapCoordinates.display(w,selected)+" · "+TerrainPresentation.of(w.terrain[selected.q][selected.r]).name():"点选地图格子";coordinate.setText(at+"\n"+p.name+" r"+p.revision+" · "+w.scenarioName);status.setText(message);toolbar();}
    private void tap(Hex h){if(busy||session==null||h==null)return;selected=h;
        if(placing!=null){SourceGridCoord source=MapCoordinates.nationalSource(session.world(),h);placing=placing.at(source.x,source.y);World.City ghost=new World.City(placing.id(),placing.name(),h,-1);ghost.kind=placing.kind();String error=CustomMaps.placement(session.world(),placing,placing.id());map.editorPreview(new LinkedHashSet<>(SiteFootprint.cells(ghost)),error==null);refresh(error==null?"七格/一格预览有效；确认后创建真实据点":error);
            if(error==null){MapPatch.Site value=placing;new AlertDialog.Builder(this).setTitle(placingAction+" "+value.name()).setMessage("中心 "+source.x+","+source.y+"；"+(value.kind()==World.SiteKind.CITY?"七格占地":"一格占地")+"。\n提交前再次检查正式占地、引用及港口水路。不会自动挪动到别处。").setNegativeButton("继续选位置",null).setNeutralButton("取消放置",(d,n)->cancelPlacement()).setPositiveButton("确认位置",(d,n)->commitPlacement(value)).show();}return;}
        if(tab==0&&drawing){if("吸管".equals(tool)){brush=session.world().terrain[h.q][h.r];refresh("已吸取地形："+TerrainPresentation.of(brush).name());return;}
            if("框选".equals(tool)){if(rectangleStart==null){rectangleStart=h;map.editorPreview(Collections.singleton(h),true);refresh("框选起点已选；再点击对角终点");}else{Set<Hex> range=session.rectangle(rectangleStart,h);rectangleStart=null;previewPaint("框选",range);}return;}
            if("连通填充".equals(tool)){work("计算同类连通区域",()->session.fill(h),range->previewPaint("连通填充",range));return;}
        }
        refresh(session.protectedAt(h)?"该格受据点、初始设施、开发地或边界保护":"已选中 · 浏览不会修改地形");if(tab==1&&session.world().cityAt(h)!=null)selectedProperties();}
    private void strokeEvent(int action,Hex h){if(busy||session==null)return;if(action==MotionEvent.ACTION_CANCEL){stroke.clear();lastStroke=null;map.editorPreview(Collections.emptySet(),true);status.setText("双指/取消：整次笔画未应用");return;}
        if(action==MotionEvent.ACTION_DOWN){stroke=new LinkedHashSet<>();lastStroke=h;}
        if(h!=null&&(action==MotionEvent.ACTION_DOWN||action==MotionEvent.ACTION_MOVE||action==MotionEvent.ACTION_UP)){selected=h;if(lastStroke==null)lastStroke=h;stroke.addAll(session.stroke(lastStroke,h,radius));lastStroke=h;map.editorPreview(stroke,true);coordinate.setText(MapCoordinates.display(session.world(),h)+" · "+TerrainPresentation.of(session.world().terrain[h.q][h.r]).name()+"\n"+tool+" · 预览 "+stroke.size()+" 格（受保护格跳过）");}
        if(action==MotionEvent.ACTION_UP){Set<Hex> completed=new LinkedHashSet<>(stroke);stroke=new LinkedHashSet<>();lastStroke=null;if(completed.size()>500)previewPaint("连续画笔",completed);else commitPaint("连续画笔",completed);}}
    private void chooseTerrain(){World.Terrain[] all=World.Terrain.values();String[] names=new String[all.length];for(int i=0;i<all.length;i++)names[i]=TerrainPresentation.of(all[i]).name()+(all[i]==World.Terrain.VOID?"（边界，不可绘制）":"");new AlertDialog.Builder(this).setTitle("正式游戏支持的地形").setItems(names,(d,n)->{if(all[n]==World.Terrain.VOID){status.setText("有效边界和外景受保护，不能刷VOID");return;}brush=all[n];toolbar();}).show();}
    private void chooseTool(){String[] names={"连续画笔","框选","连通填充","吸管"};new AlertDialog.Builder(this).setTitle("地形工具").setItems(names,(d,n)->{tool=names[n];drawing=true;rectangleStart=null;toolbar();refresh("已切换"+tool+"；操作前后可撤销/重做");}).show();}
    private void previewPaint(String label,Set<Hex> cells){Set<Hex> actual=session.differences(cells,brush);map.editorPreview(actual,true);new AlertDialog.Builder(this).setTitle(label+"预览").setMessage("将 "+actual.size()+" 格改为"+TerrainPresentation.of(brush).name()+"。\n受保护格和相同地形已排除。一次确认对应一次撤销；不会自动修复水路。").setNegativeButton("取消",(d,n)->map.editorPreview(Collections.emptySet(),true)).setPositiveButton("确认修改",(d,n)->commitPaint(label,actual)).setOnCancelListener(d->map.editorPreview(Collections.emptySet(),true)).show();}
    private void commitPaint(String label,Set<Hex> cells){World.Terrain terrain=brush;change(label,()->{int n=session.paint(label,cells,terrain);return n+" 格已修改；发布前需检查地图";});}
    private void layers(){String[] names={"格线（近景）","源坐标（近景）","步兵地形通行性（非路径保证）","据点逻辑占地"};boolean[] values={grid,coords,passability,footprints};new AlertDialog.Builder(this).setTitle("辅助显示").setMultiChoiceItems(names,values,(d,n,b)->values[n]=b).setPositiveButton("应用",(d,n)->{grid=values[0];coords=values[1];passability=values[2];footprints=values[3];map.editorLayers(grid,coords,passability,footprints);}).show();}
    private void locate(){LinearLayout form=form();EditText x=input(form,"源坐标 X（0—199）","100",true),y=input(form,"源坐标 Y（0—199）","100",true);new AlertDialog.Builder(this).setTitle("定位全国地图").setView(form).setNegativeButton("取消",null).setPositiveButton("定位",(d,n)->{try{int sx=number(x),sy=number(y);if(sx<0||sx>199||sy<0||sy>199)throw new IOException("坐标须为0—199");selected=MapCoordinates.fromNationalSource(session.world(),new SourceGridCoord(sx,sy));map.focus(selected);refresh("已定位源坐标；边界不能绘制");}catch(Exception e){error(e);}}).show();}
    private void addSite(){new AlertDialog.Builder(this).setTitle("新增真实据点").setItems(new String[]{"城池 · 七格","港口 · 一格","关卡 · 一格"},(d,n)->{World.SiteKind kind=n==0?World.SiteKind.CITY:n==1?World.SiteKind.PORT:World.SiteKind.GATE;try{int id=session.newId();if(kind==World.SiteKind.CITY)place(new MapPatch.Site(id,"新城",0,0,kind,-1,WorldEvents.Tribe.BANDIT),"新增");else chooseCity("选择关联城市（不等于实际归属）",parent->place(new MapPatch.Site(id,kind==World.SiteKind.PORT?"新港":"新关",0,0,kind,parent,WorldEvents.Tribe.BANDIT),"新增"));}catch(Exception e){error(e);}}).show();}
    private void place(MapPatch.Site s,String action){placing=s;placingAction=action;drawing=false;tab=1;toolbar();status.setText(action+" "+s.name()+"：点击地图预览位置；不自动移动到其他坐标");}
    private void cancelPlacement(){placing=null;rectangleStart=null;stroke.clear();lastStroke=null;if(map!=null)map.editorPreview(Collections.emptySet(),true);}
    private void commitPlacement(MapPatch.Site value){work("验证据点位置与引用",()->{MapPatch p=session.putSite(value);World candidate=CustomMaps.preview(p,p.preview);Set<String> existingErrors=new HashSet<>();for(CustomMaps.Issue e:CustomMaps.diagnose(session.world(),session.patch(),p.preview))if(e.blocking())existingErrors.add(e.message());List<CustomMaps.Issue> errors=CustomMaps.diagnose(candidate,p,p.preview);for(CustomMaps.Issue e:errors)if(e.blocking()&&!existingErrors.contains(e.message()))throw new IOException(e.message());return p;},p->{cancelPlacement();change("据点"+placingAction,()->{session.replace("据点"+placingAction,p);return "已创建/移动真实实体 #"+value.id()+"；新增据点默认为中立，可编辑剧本初始状态";});});}
    private void selectedSite(java.util.function.Consumer<MapPatch.Site> callback){try{World.City c=session.world().cityAt(selected);if(c==null){status.setText("请先选择一个据点，或通过据点列表选择已禁用实体");return;}callback.accept(CustomMaps.sites(session.patch()).get(c.id));}catch(Exception e){error(e);}}
    private void selectedProperties(){selectedSite(this::properties);}
    private void siteList(){try{List<MapPatch.Site> list=new ArrayList<>(CustomMaps.sites(session.patch()).values());String[] labels=new String[list.size()];for(int i=0;i<labels.length;i++){MapPatch.Site s=list.get(i);labels[i]=s.name()+" · "+kind(s.kind())+" #"+s.id()+(session.world().city(s.id())==null?"（本剧本禁用）":"");}new AlertDialog.Builder(this).setTitle("真实据点 · "+list.size()).setItems(labels,(d,n)->{MapPatch.Site s=list.get(n);selected=s.hex(session.world());map.focus(selected);refresh("已定位 "+s.name());properties(s);}).setNegativeButton("返回",null).show();}catch(Exception e){error(e);}}
    private String kind(World.SiteKind kind){return kind==World.SiteKind.CITY?"城池":kind==World.SiteKind.PORT?"港口":"关卡";}
    private void properties(MapPatch.Site s){World.City c=session.world().city(s.id());String info=kind(s.kind())+" #"+s.id()+" · 中心 "+s.x()+","+s.y()+"\n地区："+s.region().label+"；关联城市："+(s.parent()<0?"无":s.parent())+"\n本剧本实际归属："+(c==null?"禁用":session.world().faction(c.owner))+"\n地理关联不会改变港关实际占领势力。";new AlertDialog.Builder(this).setTitle(s.name()).setMessage(info).setPositiveButton("编辑地理",(d,n)->geography(s)).setNeutralButton("剧本状态",(d,n)->initialForm(s)).setNegativeButton("更多",(d,n)->new AlertDialog.Builder(this).setTitle(s.name()).setItems(new String[]{"移动","复制","删除并检查引用","关闭"},(d2,n2)->{if(n2==0)place(s,"移动");else if(n2==1)try{place(s.copy(session.newId()),"复制");}catch(Exception e){error(e);}else if(n2==2)deleteSite(s);}).show()).show();}
    private void geography(MapPatch.Site s){LinearLayout form=form();EditText name=input(form,"名称",s.name(),false),x=input(form,"源X",String.valueOf(s.x()),true),y=input(form,"源Y",String.valueOf(s.y()),true);Spinner region=spinner(form,"地区/异族区域",Arrays.stream(WorldEvents.Tribe.values()).map(t->t.label).toArray(String[]::new),s.region().ordinal());List<World.City> parents=cities();int parentIndex=0;for(int i=0;i<parents.size();i++)if(parents.get(i).id==s.parent())parentIndex=i;Spinner parent=s.kind()==World.SiteKind.CITY?null:spinner(form,"关联城市（地理，不转移归属）",parents.stream().map(c->c.name+" #"+c.id).toArray(String[]::new),parentIndex);
        new AlertDialog.Builder(this).setTitle("地理属性 · "+s.name()).setView(scroll(form)).setNegativeButton("取消",null).setPositiveButton("预检并保存",(d,n)->{try{MapPatch.Site value=new MapPatch.Site(s.id(),name.getText().toString().trim(),number(x),number(y),s.kind(),parent==null?-1:parents.get(parent.getSelectedItemPosition()).id,WorldEvents.Tribe.values()[region.getSelectedItemPosition()]);placingAction="修改";commitPlacement(value);}catch(Exception e){error(e);}}).show();}
    private void initialForm(MapPatch.Site s){MapPatch p=session.patch();World.City c=session.world().city(s.id());MapPatch.Initial existing=p.initial(p.preview,s.id());MapPatch.Initial state=existing!=null?existing:c==null?MapPatch.Initial.neutral(s.kind()):MapPatch.Initial.of(c);LinearLayout form=form();CheckBox enabled=new CheckBox(this);enabled.setText("在当前预览剧本启用");enabled.setTextColor(0xffe8e0c7);enabled.setChecked(state.enabled());form.addView(enabled);String[] sides=new String[session.world().factions.length+1];sides[0]="中立";for(int i=1;i<sides.length;i++)sides[i]=session.world().faction(i-1);Spinner owner=spinner(form,"初始势力（不是地理属性）",sides,state.owner()+1);
        EditText gold=input(form,"金",String.valueOf(state.gold()),true),food=input(form,"粮",String.valueOf(state.food()),true),troops=input(form,"兵力",String.valueOf(state.troops()),true),order=input(form,"治安",String.valueOf(state.order()),true),morale=input(form,"气力",String.valueOf(state.morale()),true),defense=input(form,"耐久",String.valueOf(state.defense()),true);
        new AlertDialog.Builder(this).setTitle(session.world().scenarioName+" · "+s.name()).setView(scroll(form)).setNegativeButton("取消",null).setPositiveButton("预览影响",(d,n)->{try{MapPatch.Initial value=new MapPatch.Initial(enabled.isChecked(),owner.getSelectedItemPosition()-1,number(gold),number(food),number(troops),number(order),number(morale),number(defense));work("检查剧本引用",()->session.initial(s.id(),value),next->confirmTransaction("确认当前剧本初始状态",next,"仅影响 "+next.preview+"。\n若武将驻地不再合法，迁移计划如下（未确认不生效）：\n"+migrationText(next),"修改剧本初始状态"));}catch(Exception e){error(e);}}).setNeutralButton("批量中立（仅新增）",(d,n)->{try{if(CustomMaps.base().sites.containsKey(s.id()))throw new IOException("历史据点不能批量覆盖；请逐剧本编辑并检查引用");MapPatch.Initial value=new MapPatch.Initial(enabled.isChecked(),-1,number(gold),number(food),number(troops),number(order),number(morale),number(defense));MapPatch next=session.patch();for(String scenario:CustomMaps.base().scenarioHashes.keySet())next.scenarios.computeIfAbsent(scenario,k->new TreeMap<>()).put(s.id(),value);confirmTransaction("批量设置新增据点",next,"将这个新增据点在全部完整全国剧本设为相同资源及中立归属，不改变历史据点。", "批量初始状态");}catch(Exception e){error(e);}}).show();}
    private void confirmTransaction(String title,MapPatch next,String detail,String label){new AlertDialog.Builder(this).setTitle(title).setMessage(detail).setNegativeButton("取消",null).setPositiveButton("确认",(d,n)->change(label,()->{session.replace(label,next);return label+"完成，整个操作可撤销";})).show();}
    private String migrationText(MapPatch p){StringBuilder s=new StringBuilder();for(var e:p.redirects.entrySet())for(var r:e.getValue().entrySet())s.append(e.getKey()).append("：#").append(r.getKey()).append(" → #").append(r.getValue()).append('\n');return s.length()==0?"无需迁移":s.toString();}
    private void deleteSite(MapPatch.Site s){work("查询所有剧本真实引用",()->CustomMaps.references(session.patch(),s.id()),refs->{TextView details=text(String.join("\n",refs),12);ScrollView scroll=new ScrollView(this);scroll.addView(details);new AlertDialog.Builder(this).setTitle("删除依赖 · "+s.name()+"（"+refs.size()+"项）").setView(scroll).setNegativeButton("取消",null).setPositiveButton("选择迁移城市",(d,n)->chooseCity("港关关联迁移城市；异势力驻将会另列同势力目的地",parent->work("构造可撤销的删除与引用修正",()->CustomMaps.deletionProposal(session.patch(),s.id(),parent),next->confirmTransaction("确认删除 "+s.name(),next,"地理实体删除；开发地随实体移除。港关只变关联，不转移势力。\n所有驻地/登场地等引用按下列明确计划迁移：\n"+migrationText(next),"删除据点及引用修正")))).show();});}
    private List<World.City> cities(){List<World.City> out=new ArrayList<>();for(World.City c:session.world().cities)if(c.kind==World.SiteKind.CITY)out.add(c);return out;}
    private void chooseCity(String title,java.util.function.IntConsumer selected){List<World.City> options=cities();new AlertDialog.Builder(this).setTitle(title).setItems(options.stream().map(c->c.name+" · "+session.world().faction(c.owner)+" #"+c.id).toArray(String[]::new),(d,n)->selected.accept(options.get(n).id)).setNegativeButton("取消",null).show();}
    private void chooseScenario(){try{List<String> ids=new ArrayList<>(CustomMaps.base().scenarioHashes.keySet());new AlertDialog.Builder(this).setTitle("切换预览剧本（不写入战局）").setItems(ids.toArray(new String[0]),(d,n)->{MapPatch p=session.patch();p.preview=ids.get(n);change("切换预览剧本",()->{session.replace("切换预览剧本",p);return "当前剧本的初始状态可在据点属性中编辑";});}).show();}catch(Exception e){error(e);}}
    private void validateMap(){MapPatch snapshot=session.patch();work("检查所有兼容剧本、占地和正式通行规则",()->CustomMaps.validateAll(snapshot),result->{issues.clear();issues.addAll(result);long blocking=result.stream().filter(CustomMaps.Issue::blocking).count();refresh(blocking==0?"没有阻断错误；提示 "+result.size()+" 项（不自动改图）":"发现 "+blocking+" 项阻断错误；仅可保存草稿，不能发布");showIssues();});}
    private void showIssues(){if(issues.isEmpty()){status.setText("尚无诊断记录，请先检查地图");return;}String[] rows=issues.stream().map(i->(i.blocking()?"阻断 · ":"提示 · ")+i.scenario()+" · "+i.message()).toArray(String[]::new);new AlertDialog.Builder(this).setTitle("诊断结果 · 点击定位").setItems(rows,(d,n)->{CustomMaps.Issue i=issues.get(n);if(i.hex()!=null){selected=i.hex();map.focus(selected);}refresh(i.message());new AlertDialog.Builder(this).setTitle(i.blocking()?"阻断错误":"诊断提示").setMessage(i.message()+"\n剧本："+i.scenario()+"\n据点："+(i.site()==null?"无":i.site())).setPositiveButton("返回地图",null).show();}).setNegativeButton("返回",null).show();}
    private void waterInfo(){Hex at=selected;work("按正式水上通行规则重算主水系",()->{MapWater water=new MapWater(session.world());StringBuilder s=new StringBuilder("主水系通过全国已知航道锚点识别，不按水塘面积判断。\n");if(at!=null){World.City c=session.world().cityAt(at);if(c!=null&&c.kind==World.SiteKind.PORT){String error=water.portError(c);s.append(c.name).append(error==null?"：合法港口":"："+error).append('\n');}for(Hex h:at.neighbors())if(session.world().army.water(h))s.append(MapCoordinates.display(session.world(),h)).append(' ').append(water.description(h)).append('\n');}return s.toString();},s->new AlertDialog.Builder(this).setTitle("邻接水域与连通检查").setMessage(s).setPositiveButton("返回",null).show());}
    private void libraryMenu(){new AlertDialog.Builder(this).setTitle("地图与版本").setItems(new String[]{"保存草稿","检查并保存为自定义地图","新建原版副本","读取已保存地图","重命名当前草稿","删除已保存地图","恢复原版草稿","导出增量JSON","导入增量JSON","返回游戏"},(d,n)->{switch(n){case 0:saveDraft();break;case 1:publish();break;case 2:case 6:work("载入只读基础地图副本",()->CustomMaps.base().fresh(),p->confirmTransaction("恢复原版副本",p,"原版始终保留。当前草稿将切换为新副本；该操作可撤销，已发布地图和旧存档不改变。","原版副本"));break;case 3:openLibrary(false);break;case 4:rename();break;case 5:openLibrary(true);break;case 7:exportPatch();break;case 8:Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);pick.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/json","text/plain","application/octet-stream"});startActivityForResult(pick,IMPORT);break;case 9:onBackPressed();break;}}).show();}
    private void saveDraft(){MapPatch p=session.patch();work("原子保存草稿",()->{library.saveDraft(p);return p.fingerprint();},hash->{session.saved(hash);refresh("草稿已保存；应用重启后可恢复");});}
    private void publish(){MapPatch p=session.patch();work("全剧本校验并保存不可变地图版本",()->library.publish(p),saved->change("保存自定义版本",()->{session.replace("保存自定义版本",saved);return "已发布 "+saved.name+" r"+saved.revision+"；新建游戏 → 剧本 → 自定义地图选择此版本";}));}
    private void rename(){LinearLayout form=form();EditText name=input(form,"草稿地图名称",session.patch().name,false);new AlertDialog.Builder(this).setTitle("重命名").setView(form).setNegativeButton("取消",null).setPositiveButton("保存名称",(d,n)->{MapPatch p=session.patch();p.name=name.getText().toString().trim();change("重命名",()->{session.replace("重命名",p);return "草稿已重命名；发布会生成新修订，不覆盖旧版本";});}).show();}
    private void openLibrary(boolean delete){work("读取自定义地图库",library::entries,entries->{if(entries.isEmpty()){status.setText("尚未发布自定义地图");return;}new AlertDialog.Builder(this).setTitle(delete?"删除地图（不影响自包含存档）":"选择自定义地图").setItems(entries.stream().map(MapLibrary.Entry::label).toArray(String[]::new),(d,n)->{MapLibrary.Entry entry=entries.get(n);if(delete)new AlertDialog.Builder(this).setTitle("删除 "+entry.label()).setMessage("删除该地图在地图库的全部修订。已保存的战局内嵌完整地理，仍可继续；当前草稿也不删除。").setNegativeButton("取消",null).setPositiveButton("删除地图",(d2,n2)->work("删除地图库修订",()->{library.delete(entry.id());return "已删除地图库版本";},this::refresh)).show();else work("读取不可变版本",()->library.load(entry),p->confirmTransaction("打开 "+entry.label(),p,"将替换当前草稿，可撤销；不修改正在进行的战局。","打开自定义地图"));}).show();});}
    private void exportPatch(){MapPatch snapshot=session.patch();work("生成带基线与前置值的增量JSON",()->{CustomMaps.verifyBase(snapshot);return snapshot.encode();},bytes->{exporting=bytes;Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"map-"+snapshot.id+"-r"+snapshot.revision+".json");startActivityForResult(intent,EXPORT);});}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){if(request==EXPORT)exporting=null;return;}Uri uri=data.getData();if(request==EXPORT){byte[] bytes=exporting;exporting=null;if(bytes==null){error(new IOException("导出会话已重建，请重新导出；草稿仍保留"));return;}work("保存到系统文档位置",()->{try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("系统文档不可写");out.write(bytes);out.flush();}return "JSON已保存到系统文档，可通过文件管理器分享";},this::refresh);}else if(request==IMPORT)work("只读解析与冲突预检",()->{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取选择的文件");MapPatch p=MapPatch.read(in);CustomMaps.verifyBase(p);CustomMaps.preview(p,p.preview);return p;}},this::previewImport);}
    private record ImportPreview(boolean conflict,String detail){}
    private void previewImport(MapPatch p){work("检查导入影响（尚未应用）",()->{
        MapLibrary.ImportCheck conflict=library.checkImport(p);List<CustomMaps.Issue> found=CustomMaps.validateAll(p);long errors=found.stream().filter(CustomMaps.Issue::blocking).count();
        return new ImportPreview(conflict.forkRequired(),conflict.message()+"\n"+p.summary()+"\n阻断错误："+errors+"；有错误只能保留待修草稿。\n"+siteChanges(p));
    },preview->{AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle("导入预览 · 未修改当前数据").setMessage(preview.detail()).setNegativeButton("取消",null);
        if(!preview.conflict())dialog.setPositiveButton("替换草稿（可撤销）",(d,n)->change("导入Patch",()->{session.replace("导入Patch",p);return "导入完成；重复导入不会重复创建实体。请校验并发布后新开游戏";}));
        else dialog.setPositiveButton("明确作为新地图",(d,n)->{MapPatch fork=p.copy();fork.id=UUID.randomUUID().toString();fork.revision=1;change("作为新地图导入",()->{session.replace("作为新地图导入",fork);return "已使用新地图ID；原版本未覆盖";});});dialog.show();});}
    private String siteChanges(MapPatch p){StringBuilder s=new StringBuilder();for(MapPatch.SiteChange change:p.sites.values()){MapPatch.Site value=change.after()==null?change.before():change.after();s.append(change.before()==null?"新增 ":change.after()==null?"删除 ":"修改/移动 ").append(value.name()).append(" #").append(value.id()).append("\n");}return s.toString();}
    private LinearLayout form(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(12),dp(4),dp(12),dp(4));return v;}
    private EditText input(LinearLayout form,String label,String value,boolean numeric){form.addView(text(label,12));EditText input=new EditText(this);input.setSingleLine(true);input.setTextColor(0xffe8e0c7);input.setHint(label);input.setContentDescription(label);input.setInputType(numeric?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_SIGNED:InputType.TYPE_CLASS_TEXT);input.setText(value);form.addView(input);return input;}
    private Spinner spinner(LinearLayout form,String label,String[] names,int selected){form.addView(text(label,12));Spinner v=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names);v.setAdapter(adapter);v.setSelection(Math.max(0,selected));form.addView(v);return v;}
    private ScrollView scroll(View child){ScrollView sc=new ScrollView(this);sc.addView(child);return sc;}
    private int number(EditText input)throws IOException {try{return Integer.parseInt(input.getText().toString().trim());}catch(NumberFormatException e){throw new IOException("请输入有效整数："+input.getHint());}}
    private <T> void work(String label,Callable<T> action,java.util.function.Consumer<T> result){if(busy||destroyed)return;busy=true;status.setText(label+"…");progress.setVisibility(View.VISIBLE);map.setEnabled(false);worker.execute(()->{try{T value=action.call();runOnUiThread(()->{if(destroyed)return;busy=false;progress.setVisibility(View.GONE);map.setEnabled(true);try{result.accept(value);}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->{if(destroyed)return;busy=false;progress.setVisibility(View.GONE);map.setEnabled(true);error(e);});}});}
    private void change(String label,Callable<?> action){if(busy||destroyed)return;map.setVisibility(View.INVISIBLE);work(label,()->{Object result=action.call();MapPatch p=session.patch();library.saveDraft(p);session.saved(p.fingerprint());return result==null?label+"完成":result.toString();},message->{map.setVisibility(View.VISIBLE);issues.clear();map.editorPreview(Collections.emptySet(),true);refresh(message+" · 已自动保存草稿");});}
    private void error(Exception e){map.setVisibility(View.VISIBLE);status.setText("操作未完成："+e.getMessage());AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle("操作失败，请检查草稿保存状态").setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("返回",null);if(session==null)dialog.setNeutralButton("保留旧文件并新建",(d,n)->work("保留恢复副本并建立新草稿",()->{library.archiveDraft();MapPatch fresh=CustomMaps.base().fresh();library.saveDraft(fresh);return new MapEditSession(fresh);},s->{session=s;refresh("旧草稿文件保留为恢复副本；已创建新的原版副本");map.post(map::fit);}));dialog.show();}
    @Override public void onBackPressed(){if(busy){status.setText("当前事务尚未结束，返回未执行");return;}if(session==null){finish();return;}if(!session.dirty()){finish();return;}new AlertDialog.Builder(this).setTitle("保存修改后退出？").setNegativeButton("取消",null).setNeutralButton("不保存退出",(d,n)->{discardOnExit=true;finish();}).setPositiveButton("保存并退出",(d,n)->{MapPatch p=session.patch();work("保存草稿",()->{library.saveDraft(p);return true;},done->finish());}).show();}
    @Override protected void onSaveInstanceState(Bundle out){if(map!=null)map.saveCamera(out);super.onSaveInstanceState(out);}
    @Override protected void onResume(){super.onResume();if(map!=null)map.resume(true);}
    @Override protected void onPause(){super.onPause();if(map!=null)map.resume(false);if(session!=null&&!discardOnExit){MapPatch snapshot;long expected;synchronized(session){snapshot=session.patch();expected=session.generation();}worker.execute(()->{try{if(session.generation()==expected)library.saveDraft(snapshot);}catch(IOException ignored){/* Every edit already saves atomically; foreground save surfaces errors. */}});}}
    @Override protected void onDestroy(){destroyed=true;if(map!=null)map.release();worker.shutdown();super.onDestroy();}
}
