package game.sanguo.core;
import java.nio.*;import java.nio.file.*;import java.util.*;
import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** Full original held-item callback and typed campaign. Item placements are
 * declared after the real original battle, not naturally equipped combat. */
public final class PcDuelNaturalDeathItemSessionTest {
    static int checks;static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
    static Map<String,String> items(World w){var out=new TreeMap<String,String>();for(var item:w.treasures.items())out.put(item.definition.id,item.place.name()+":"+item.holder);return out;}
    public static void main(String[]args)throws Exception {
        Path endpoint=Path.of(args[0]),path=Path.of(args[1]);byte[]raw=Files.readAllBytes(path);check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(raw)).equals("ddad0d8380073d2ddf331c9d83b05150da5e2832e5dce39c98545df67ca77468"),"pinned full original held callback");String text=new String(raw,java.nio.charset.StandardCharsets.UTF_8);var ints=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);byte[]parsed=ints.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8);var receipt=MapJson.object(MapJson.parse(parsed));check(Boolean.TRUE.equals(receipt.get("wholeWorldAndRngRestored")),"original World/RNG restored");
        for(Object value:MapJson.array(receipt.get("cases"))){var row=MapJson.object(value);List<Integer>held=MapJson.array(row.get("declaredPostbattleHeld")).stream().map(v->((Number)v).intValue()).toList();World w=PcDuelNaturalDeathSessionTest.fixture(endpoint,true,false);int target=PcDuelNaturalDeathSessionTest.stable(w,116),ruler=PcDuelNaturalDeathSessionTest.stable(w,517),active=PcDuelNaturalDeathSessionTest.stable(w,14),commander=PcDuelNaturalDeathSessionTest.stable(w,558);
            check(ruler!=active&&ruler!=commander&&w.loyalty.ruler(w.officer(active).owner).id==ruler,"current ruler/active/support/unit commander distinct");for(int n:held)w.treasures.place(Treasures.definition(String.format(Locale.ROOT,"item-%03d",n)),Treasures.Place.OFFICER,target);var beforeItems=items(w);byte[]pending=SaveCodec.encode(w);check(Arrays.equals(pending,SaveCodec.encode(SaveCodec.decode(pending))),"full held pending cold exact "+held);
            try(GameSession game=new GameSession(SaveCodec.decode(pending))){var facts=game.contest();check(facts.nativeDuel.terminal&&facts.settlementAvailable&&facts.nativeDuel.settlementError.isEmpty()&&facts.nativeDuel.disposition.isEmpty(),"held natural preview ready without captive menu");check(Arrays.equals(pending,game.captureSave()),"preview/recipient no RNG/item/life write");var old=game.state();game.replace(SaveCodec.decode(pending));var rejected=game.execute(ContestCommand.finishNativeDuel(old,1,0));check(!rejected.ok()&&Arrays.equals(pending,game.captureSave()),"cold old StateToken fences held transfer");facts=game.contest();var token=game.state();var done=game.execute(ContestCommand.finishNativeDuel(token,facts.contestId,facts.revision));check(done.ok(),"held natural campaign terminal "+done.detail);byte[]finished=game.captureSave();World after=SaveCodec.decode(finished);
                check(after.life.state(target)==Lifecycle.State.DEAD&&after.officer(target).owner==-1&&!after.contests.busy()&&PcDuelCampaignPolicy.lastFinished(after)==1,"complete death and one terminal receipt");check(PcNativeDebatePolicy.seed(after)==((Number)row.get("rngAfter")).intValue()&&after.strategy.getRandomState()==w.strategy.getRandomState(),"original exact rule RNG/no display draw");check(after.government.merit(active)==100&&after.officerAbilities.experience(active,1)==10&&after.government.merit(target)==0,"natural100 merit/10 WARXP; no capture200/dead XP");
                for(Object originalValue:MapJson.array(row.get("after"))){var original=MapJson.object(originalValue);int n=((Number)original.get("nativeId")).intValue();if(!held.contains(n))continue;int nativeOwner=ByteBuffer.wrap(HexFormat.of().parseHex((String)original.get("hex"))).order(ByteOrder.LITTLE_ENDIAN).getInt(0x40);int expected=PcDuelNaturalDeathSessionTest.stable(after,nativeOwner);var item=after.treasures.item(String.format(Locale.ROOT,"item-%03d",n));check(nativeOwner==517&&item.place==Treasures.Place.OFFICER&&item.holder==expected,"original held item "+n+" recipient current ruler517");}
                var afterItems=items(after);for(var entry:beforeItems.entrySet()){int n=Integer.parseInt(entry.getKey().substring(5));if(!held.contains(n))check(Objects.equals(afterItems.get(entry.getKey()),entry.getValue()),"other current ownership unchanged "+entry.getKey());}check(beforeItems.size()==afterItems.size(),"no item invented/lost");check(Arrays.equals(finished,SaveCodec.encode(after)),"complete held death World cold exact");rejected=game.execute(ContestCommand.finishNativeDuel(token,1,0));check(!rejected.ok()&&Arrays.equals(finished,game.captureSave()),"duplicate old token no transfer/XP/RNG");rejected=game.execute(ContestCommand.finishNativeDuel(game.state(),1,0));check(!rejected.ok()&&Arrays.equals(finished,game.captureSave()),"fresh no-session duplicate no transfer");check(game.officers().officer(ruler).treasuresDescription.equals(after.treasures.describe(ruler))&&Arrays.equals(finished,game.captureSave()),"normal ruler details/source holdings pure");
                if(held.equals(List.of(0,30))){Files.write(Path.of("out/session-b/natural-death-item-pending-v1.sg11"),pending);Files.write(Path.of("out/session-b/natural-death-item-finished-v1.sg11"),finished);}
                for(int turn=0;turn<3;turn++){var ticket=game.beginTurn();World computed=SaveCodec.decode(ticket.initial());var next=computed.nextTurn();check(next.ok&&game.commitTurn(ticket,computed),"actual full AI turn held="+held+" turn="+turn);byte[]saved=game.captureSave();game.replace(SaveCodec.decode(saved));check(Arrays.equals(saved,game.captureSave())&&SaveCodec.decode(saved).life.state(target)==Lifecycle.State.DEAD,"full World/both RNG cold future held="+held);}
            }
        }System.out.println("PASS original natural held transfer/current ruler/typed once terminal/3 whole turns/cold "+checks+" checks; declared equipped endpoint, normal equipped deployment/menu/APK pending");
    }
}
