package game.sanguo.core;
import java.util.*;
import game.sanguo.api.*;
import game.sanguo.runtime.GameSession;
/** Real new-source factory and command-generated model; adjacent serving
 * units are declared fixtures, not a normal campaign deployment/APK proof. */
public final class PcDuelChallengeSessionTest {
    static int checks;static void check(boolean b,String label){checks++;if(!b)throw new AssertionError(label);}
    public static void main(String[]args)throws Exception {
        boolean retreat=args.length>0&&args[0].equals("retreat");boolean requestedRetreat=false;String source=PcScenarioCatalog.all().get(0).identity.scenarioId;World legacy=PcScenarioCatalog.load(source,2,23);check(!legacy.contests.nativeDuelConfigured(),"existing factory unchanged");byte[]old=SaveCodec.encode(legacy);check(Arrays.equals(old,SaveCodec.encode(SaveCodec.decode(old))),"existing source cold byte parity");
        boolean accepted=false,refused=false;
        for(int seed=0;seed<12&&(!accepted||!refused);seed++){
            World w=PcScenarioCatalog.load(source,2,seed,new PcDuelOptions(0,0,0));check(w.contests.nativeDuelConfigured(),"explicit fresh source factory");int[]natives={365,116,466,558,14,517},ids=new int[6];for(int i=0;i<6;i++){final int n=natives[i];ids[i]=PcDuelSourceFacts.saved(w).values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}
            Hex first=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),k=new Hex(q+1,r);if(w.inside(k)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(k,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(k)&&w.cityAt(h)==null&&w.cityAt(k)==null){first=h;break outer;}}
            for(int side=0;side<2;side++){var leader=w.officer(ids[side*3]);var home=w.city(leader.cityId);var unit=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,17000);unit.deputies=new int[]{ids[side*3+1],ids[side*3+2]};unit.gold=1000;w.units.add(unit);for(var person:w.army.crew(unit)){w.strategy.releaseGovernor(person.id);person.unitId=unit.id;person.cityId=-1;}w.districts.deployed(home.id,unit);PcGovernorPolicy.deployed(w,unit,home);}w.nextUnitId=3;w.governance.reconcile(false);
            byte[]before=SaveCodec.encode(w);var candidates=w.contests.nativeDuelCandidates(1,2);check(candidates.size()==3&&Arrays.equals(before,SaveCodec.encode(w)),"ordered menu no World/RNG changes");
            try(GameSession game=new GameSession(w)){var token=game.state();var bad=game.execute(ContestCommand.startNativeDuel(token,1,2,ids[3]));check(!bad.ok()&&Arrays.equals(before,game.captureSave()),"invalid nominated enemy rejected purely");var result=game.execute(ContestCommand.startNativeDuel(token,1,2,ids[0]));check(result.ok(),"normal creator command "+result.detail);byte[]created=game.captureSave();check(!Arrays.equals(before,created),"creator changes authoritative World");var duplicate=game.execute(ContestCommand.startNativeDuel(token,1,2,ids[0]));check(!duplicate.ok()&&Arrays.equals(created,game.captureSave()),"start duplicate old StateToken rejected");World current=SaveCodec.decode(created);check(current.unit(1).acted&&!current.unit(2).acted&&current.unit(1).gold==1000,"actor-only action/money");check(Arrays.equals(created,SaveCodec.encode(current)),"whole created World/RNG cold exact");
                if(game.contest().nativeDuel==null){refused=true;check(!current.contests.busy(),"refusal keeps normal campaign available");System.out.println("PASS actual creator refused seed "+seed);continue;}
                accepted=true;int adviserBefore=current.government.advisor(2)==null?-1:current.government.advisor(2).id;check(current.contests.session.nativeDuel.commandBoundary&&current.contests.session.nativeDuel.settings.separateDeath,"real creator format5");var commandFacts=game.contest().nativeDuel;check(commandFacts.commandBoundary&&!commandFacts.previousOpponentActed&&commandFacts.openingSpeechCode==current.contests.session.nativeDuel.openingVoice,"saved command/speech fact API preserves original raw code without audio guessing");int inputs=0;while(!game.contest().nativeDuel.terminal&&inputs++<250){var facts=game.contest();var choice=facts.nativeDuel.choices.stream().filter(p->p.enabled()&&p.special==-1&&p.replacement==-1).findFirst().orElseThrow();if(retreat){var request=facts.nativeDuel.choices.stream().filter(p->p.enabled()&&p.special==3).findFirst();if(request.isPresent()){choice=request.get();requestedRetreat=true;}else{var pose=facts.nativeDuel.choices.stream().filter(p->p.enabled()&&p.stance==2&&p.special==-1&&p.replacement==-1).findFirst();if(pose.isPresent())choice=pose.get();}}var input=game.execute(ContestCommand.nativeDuelInput(facts.state,facts.contestId,facts.revision,choice.stance,choice.special,choice.replacement));check(input.ok(),"real generated human/AI advance "+input.detail);byte[]saved=game.captureSave();game.replace(SaveCodec.decode(saved));check(Arrays.equals(saved,game.captureSave()),"cold input exact");}
                check(game.contest().nativeDuel.terminal,"actual generated battle reaches terminal");if(seed==1&&!retreat){var priorPath=java.nio.file.Path.of("out/session-b/duel-creator-pending-seed1.sg11");if(java.nio.file.Files.exists(priorPath)){byte[]prior=java.nio.file.Files.readAllBytes(priorPath);World priorWorld=SaveCodec.decode(prior);check(PcDuelCampaignPolicy.read(priorWorld).version==2&&PcGovernorPolicy.data(priorWorld).format==1&&Arrays.equals(prior,SaveCodec.encode(priorWorld)),"preserved prior generated PDU2/PGO1 checkpoint cold exact without upgrade");}var previousCurrent=java.nio.file.Path.of("out/session-b/duel-creator-pending-v3-seed1.sg11");if(java.nio.file.Files.exists(previousCurrent)){byte[] prior=java.nio.file.Files.readAllBytes(previousCurrent);World oldCurrent=SaveCodec.decode(prior);check(PcDuelCampaignPolicy.read(oldCurrent).version==3&&PcGovernorPolicy.data(oldCurrent).format==2&&Arrays.equals(prior,SaveCodec.encode(oldCurrent)),"saved PDU3/PGO2 not upgraded to vacancy-aware PGO3");}var path=java.nio.file.Path.of("out/session-b/duel-creator-pending-pdu3-pgo3-seed1.sg11");if(java.nio.file.Files.exists(path))check(Arrays.equals(java.nio.file.Files.readAllBytes(path),game.captureSave()),"generated full pending World exact for same explicit new PDU3/PGO2 strategy");else java.nio.file.Files.write(path,game.captureSave());}var facts=game.contest();result=game.execute(ContestCommand.finishNativeDuel(facts.state,facts.contestId,facts.revision));check(result.ok(),"first real generated terminal "+result.detail);if(game.contest().nativeDuel!=null){for(var row:game.contest().nativeDuel.disposition){var choose=game.contest();result=game.execute(ContestCommand.nativeDuelDisposition(choose.state,choose.contestId,choose.revision,row.officerId,1));check(result.ok(),"actual generated custody selection "+result.detail);}facts=game.contest();result=game.execute(ContestCommand.finishNativeDuel(facts.state,facts.contestId,facts.revision));check(result.ok(),"actual generated confirmed campaign terminal "+result.detail);}
                check(!game.contest().nativeRules,"real generated session ends");byte[]finished=game.captureSave();current=SaveCodec.decode(finished);check(Arrays.equals(finished,SaveCodec.encode(current))&&PcDuelCampaignPolicy.read(current).version==3,"new options survive terminal/full cold");if(adviserBefore>=0&&current.government.captive(adviserBefore))check(current.government.advisor(2)==null,"original captured military adviser cleared without invented replacement");if(current.unit(2)!=null)check(!current.unit(2).acted,"defender action preserved through actual full battle");var duplicateFinish=game.execute(ContestCommand.finishNativeDuel(game.state(),facts.contestId,facts.revision));check(!duplicateFinish.ok()&&Arrays.equals(finished,game.captureSave()),"terminal cannot settle twice with current or old token");
                for(int turn=0;turn<3;turn++){var ticket=game.beginTurn();World computed=SaveCodec.decode(ticket.initial());var next=computed.nextTurn();check(next.ok,"actual generated terminal future whole turn "+next.message);check(game.commitTurn(ticket,computed),"whole future turn once committed");byte[]future=game.captureSave();game.replace(SaveCodec.decode(future));check(Arrays.equals(future,game.captureSave()),"future wholeWorld/allRNG cold exact");}
                System.out.println("PASS actual creator accepted seed "+seed+" inputs "+inputs+" future whole turns 3");
            }
        }
        check(accepted&&refused,"actual new factory reaches accepted/refused normal creator branches");if(retreat)check(requestedRetreat,"real human retreat enabled and requested without modified spirit or health");System.out.println("PASS new source creator "+checks+" checks; declared adjacent units, actual menus/APK/complete ruler callbacks remain pending");
    }
}
