package game.sanguo.core;
import java.util.*;import java.nio.file.*;import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** Both deaths originate in natural typed battle/production disposition,
 * separated by complete campaign AI turn. Source units at each encounter
 * and initial unavailable default-heir captivity are declared fixtures;
 * this is not ordinary deployment/capture/menu/APK proof. */
public final class PcDuelSwornDoubleBattleSessionTest {
    static int checks;static void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
    static Map<Integer,Integer> ids(World w)throws Exception {var out=new TreeMap<Integer,Integer>();for(var f:PcDuelSourceFacts.saved(w).values())out.put(f.nativeId,f.officerId);return out;}
    static Hex land(World w)throws Exception {for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex a=new Hex(q,r),b=new Hex(q+1,r);if(w.inside(b)&&w.cost(a,World.Weapon.SWORD)>0&&w.cost(b,World.Weapon.SWORD)>0&&!w.army.water(a)&&!w.army.water(b)&&w.cityAt(a)==null&&w.cityAt(b)==null&&PcPersonnelReturnRules.cityAt(w,b)==15)return a;}throw new AssertionError("original source15 lawful land pair");}
    static void cold(GameSession game)throws Exception {byte[] save=game.captureSave();game.replace(SaveCodec.decode(save));check(Arrays.equals(save,game.captureSave()),"whole World/dualRNG cold exact");}
    static void turn(GameSession game)throws Exception {var ticket=game.beginTurn();World next=SaveCodec.decode(ticket.initial());check(next.nextTurn().ok,"complete AI campaign turn");check(game.commitTurn(ticket,next),"turn commits once");cold(game);}
    static void declare(World w,int officer,int unitId,Hex hex)throws Exception {var o=w.officer(officer);check(o.unitId<0&&o.cityId>=0&&o.otherTaskTurns==0&&w.life.present(officer),"declared encounter source person remains current idle");var home=w.city(o.cityId);var u=new World.Unit(unitId,o.owner,o.id,World.Weapon.SWORD,hex,5000,17000);u.gold=997;w.units.add(u);w.strategy.releaseGovernor(o.id);o.unitId=unitId;o.cityId=-1;w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);w.nextUnitId=Math.max(w.nextUnitId,unitId+1);w.governance.reconcile(false);}
    static World firstEncounter(World source,int target,Hex land)throws Exception {
        byte[] initial=SaveCodec.encode(source);var facts=PcDuelSourceFacts.saved(source);var candidates=source.officers.stream().filter(o->o.owner==2&&source.life.present(o.id)&&o.cityId>=0&&o.unitId<0&&o.otherTaskTurns==0&&!source.government.captive(o.id)&&facts.containsKey(o.id)).sorted(Comparator.comparingInt((World.Officer o)->Math.abs(o.war-source.officer(target).war))).toList();
        for(var candidate:candidates){World probe=SaveCodec.decode(initial);declare(probe,candidate.id,1,land);declare(probe,target,2,new Hex(land.q+1,land.r));byte[] before=SaveCodec.encode(probe);var menu=probe.contests.nativeDuelCandidates(1,2);check(Arrays.equals(before,SaveCodec.encode(probe)),"actual candidate query pure World/RNG");int chance=menu.get(0).chance;System.out.println("Source first candidate native "+facts.get(candidate.id).nativeId+" war "+candidate.war+" vs "+source.officer(target).war+" chance "+chance);if(chance>0)return probe;}
        throw new AssertionError("No actual source actor has legal positive first response; preserve admission instead of editing rules");
    }
    static Hex[] emptyPair(World w,Hex origin){for(Hex a:origin.neighbors())if(w.inside(a)&&w.cost(a,World.Weapon.SWORD)>0&&!w.army.water(a)&&w.cityAt(a)==null&&w.unitAt(a)==null)for(Hex b:a.neighbors())if(!b.equals(origin)&&w.inside(b)&&w.cost(b,World.Weapon.SWORD)>0&&!w.army.water(b)&&w.cityAt(b)==null&&w.unitAt(b)==null)return new Hex[]{a,b};throw new AssertionError("lawful empty second encounter pair");}
    static int[] secondEncounter(World source,int target,Hex origin)throws Exception {
        byte[] initial=SaveCodec.encode(source);var facts=PcDuelSourceFacts.saved(source);var candidates=source.officers.stream().filter(o->o.owner==2&&source.life.present(o.id)&&o.cityId>=0&&o.unitId<0&&o.otherTaskTurns==0&&!source.government.captive(o.id)&&facts.containsKey(o.id)&&o.war>=source.officer(target).war).sorted(Comparator.comparingInt((World.Officer o)->Math.abs(o.war-source.officer(target).war))).toList();
        for(var candidate:candidates){World probe=SaveCodec.decode(initial);Hex[] pair=emptyPair(probe,origin);int own=probe.nextUnitId;declare(probe,candidate.id,own,pair[0]);int other=probe.nextUnitId;declare(probe,target,other,pair[1]);byte[] before=SaveCodec.encode(probe);var menu=probe.contests.nativeDuelCandidates(own,other);check(Arrays.equals(before,SaveCodec.encode(probe)),"second candidate query fullWorld/RNG pure");int chance=menu.get(0).chance;System.out.println("Source second candidate native "+facts.get(candidate.id).nativeId+" war "+candidate.war+" vs "+source.officer(target).war+" chance "+chance);if(chance>0){secondPrepared=probe;return new int[]{own,other};}}
        throw new AssertionError("No current strong legal second actor; preserve response rules");
    }
    static World secondPrepared;
    static boolean battle(GameSession game,int own,int other,int target)throws Exception {
        World current=SaveCodec.decode(game.captureSave());int actor=current.unit(own).officerId;if(game.contest().nativeDuel==null)System.out.println("Natural encounter targetNative "+PcDuelSourceFacts.saved(current).get(target).nativeId+" turn "+current.turn+" chance "+current.contests.nativeDuelCandidates(own,other).get(0).chance);
        CommandResult result;
        if(game.contest().nativeDuel==null){result=game.execute(ContestCommand.startNativeDuel(game.state(),own,other,actor));check(result.ok(),"typed original battle admission "+result.detail);if(game.contest().nativeDuel==null){System.out.println("Actual refusal");return false;}}
        else {var saved=current.contests.current();check(saved.leftRef==own&&saved.rightRef==other,"exact saved actual battle resumes");System.out.println("Resume saved original battle/model/RNG");}
        int inputs=0;while(!game.contest().nativeDuel.terminal&&inputs++<300){var f=game.contest();var choice=f.nativeDuel.choices.stream().filter(c->c.enabled()&&c.special==-1&&c.replacement==-1).findFirst().orElseThrow();result=game.execute(ContestCommand.nativeDuelInput(f.state,f.contestId,f.revision,choice.stance,choice.special,choice.replacement));check(result.ok(),"actual legal human/AI input "+result.detail);}
        var f=game.contest();check(f.nativeDuel.terminal,"natural terminal");cold(game);f=game.contest();result=game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision));check(result.ok(),"actual terminal preparation "+result.detail);
        if(game.contest().nativeDuel==null){System.out.println("Natural no-fate terminal inputs "+inputs);return false;}
        f=game.contest();if(f.nativeDuel.inheritance!=null||f.nativeDuel.disposition.size()!=1||f.nativeDuel.disposition.get(0).officerId!=target){System.out.println("Other actual terminal target, not selected for double-death case");return false;}
        byte[] before=game.captureSave();var command=ContestCommand.nativeDuelDisposition(f.state,f.contestId,f.revision,target,3);result=game.execute(command);check(result.ok(),"original current EXECUTE admitted "+result.detail);byte[] selected=game.captureSave();check(!game.execute(command).ok()&&Arrays.equals(selected,game.captureSave()),"double/stale disposition rejects without World/RNG write");cold(game);f=game.contest();result=game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision));check(result.ok(),"actual current ruler/death/sworn production settlement "+result.detail);check(game.contest().nativeDuel==null,"once terminal ends");cold(game);byte[] finished=game.captureSave();check(!game.execute(ContestCommand.finishNativeDuel(game.state(),f.contestId,f.revision)).ok()&&Arrays.equals(finished,game.captureSave()),"settlement double rejects pure");check(SaveCodec.decode(finished).life.state(target)==Lifecycle.State.DEAD,"actual battle target died");System.out.println("Actual original EXECUTE inputs "+inputs+" priorWorldBytes "+before.length);return true;
    }
    public static void main(String[]args)throws Exception {
        boolean done=false;
        int begin=args.length>1?Integer.parseInt(args[1]):args.length==0?28:49;
        for(int seed=begin;seed<128&&!done;seed++){
            boolean restored=args.length>0&&seed==begin;World w=restored?SaveCodec.decode(Files.readAllBytes(Path.of(args[0]))):PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,seed,new PcDuelOptions(0,0,0));var ids=ids(w);int actor=ids.get(365),first=ids.get(614);boolean firstComplete=w.life.state(first)==Lifecycle.State.DEAD;int selected=firstComplete?w.loyalty.ruler(4).id:PcRulerSuccession.preview(w,first).selected;int originalDefault=PcDuelSourceFacts.saved(w).get(selected).nativeId;
            if(originalDefault!=98&&originalDefault!=432&&originalDefault!=635){System.out.println("Declared initial current captivity for actual AI default native "+originalDefault);var jail=w.cities.stream().filter(c->c.owner==2).findFirst().orElseThrow();w.government.capture(w.officer(selected),jail);}
            int initialHeir=PcDuelSourceFacts.saved(w).get(firstComplete?w.loyalty.ruler(4).id:PcRulerSuccession.preview(w,first).selected).nativeId;System.out.println("Source0 seed "+seed+" actual initial AI heir native "+initialHeir);check(initialHeir==98||initialHeir==432||initialHeir==635,"actual AI default first successor is original sworn member");Hex land=land(w);if(!restored)w=firstEncounter(w,first,land);
            try(GameSession game=new GameSession(w)){
                try {
                    if(!firstComplete&&!battle(game,1,2,first))continue;var current=SaveCodec.decode(game.captureSave());var ruler=current.loyalty.ruler(4);int second=ruler.id;check(PcDuelSourceFacts.saved(current).get(second).nativeId==initialHeir,"first production AI selected real successor");if(!firstComplete)turn(game);current=SaveCodec.decode(game.captureSave());for(int wait=0;current.officer(second).unitId<0&&current.officer(second).otherTaskTurns>0&&wait<8;wait++){System.out.println("Actual ruler task turn "+current.turn+" "+current.officer(second).otherTask+" remaining "+current.officer(second).otherTaskTurns);turn(game);current=SaveCodec.decode(game.captureSave());}var unit=current.unit(1);check(unit!=null,"human victor survives real AI turn");int[] refs=secondEncounter(current,second,unit.hex);current=secondPrepared;int own=refs[0],nextUnit=refs[1];Path ready=Path.of("out/session-b/sworn-double-battle-second-ready-v1.sg11");if(!Files.exists(ready))Files.write(ready,SaveCodec.encode(current));game.replace(current);cold(game);
                    if(!battle(game,own,nextUnit,second))continue;current=SaveCodec.decode(game.captureSave());ruler=current.loyalty.ruler(4);check(ruler!=null&&current.life.state(first)==Lifecycle.State.DEAD&&current.life.state(second)==Lifecycle.State.DEAD,"two original typed death callbacks closed");int nextNative=PcDuelSourceFacts.saved(current).get(ruler.id).nativeId;check(nextNative==98||nextNative==432||nextNative==635,"current AI second heir remains group member");check(PcDuelRawLoyalty.current(current,ruler.id)==150&&ruler.loyalty==100,"AI second ruler raw150/display100");for(int future=0;future<4;future++)turn(game);current=SaveCodec.decode(game.captureSave());check(current.loyalty.ruler(4).id==ruler.id&&current.life.state(first)==Lifecycle.State.DEAD&&current.life.state(second)==Lifecycle.State.DEAD,"two deaths and heir persist after complete four turns");done=true;System.out.println("PASS natural double ruler death seed "+seed+" successors "+initialHeir+" / "+nextNative);
                }catch(Exception|AssertionError e){Path fault=Path.of("out/session-b/sworn-double-battle-fault-v6.sg11");if(!Files.exists(fault))Files.write(fault,game.captureSave());throw e;}
            }
        }
        check(done,"natural accepted two battles/current sworn heir callbacks completed");System.out.println("PASS typed natural double ruler/sworn battle "+checks+" checks; declared encounters, ordinary deployment/menu/APK pending");
    }
}
