package game.sanguo.core;
import java.io.*;import java.nio.*;import java.nio.file.*;import java.util.*;
import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** Actual original naturally generated terminal, declared source formations.
 * Typed production settlement/whole turns; normal deployment/menu is separate. */
public final class PcDuelNaturalDeathSessionTest {
    static int checks;static void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
    static World fixture(Path endpoint,boolean current,boolean item)throws Exception {
        Map<String,String> data=new HashMap<>();for(String line:Files.readAllLines(endpoint)){if(line.startsWith("#"))continue;String[]p=line.split("\t");data.put(p[0],p[1]);}
        World w=current?PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,14,new PcDuelOptions(0,2,0)):PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,14);
        int[]natives=Arrays.stream(data.get("NATIVES").split(",")).mapToInt(Integer::parseInt).toArray(),ids=new int[6];var facts=PcDuelSourceFacts.saved(w);
        for(int i=0;i<6;i++){final int n=natives[i];ids[i]=facts.values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}
        Hex left=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex a=new Hex(q,r),b=new Hex(q+1,r);if(w.inside(b)&&w.cityAt(a)==null&&w.cityAt(b)==null&&!w.army.water(a)&&!w.army.water(b)&&w.cost(a,World.Weapon.SWORD)>0&&w.cost(b,World.Weapon.SWORD)>0){left=a;break outer;}}
        check(left!=null,"two legal adjacent land cells");
        for(int side=0;side<2;side++){var o=w.officer(ids[side*3]);var home=w.city(o.cityId);var unit=new World.Unit(side+1,o.owner,o.id,World.Weapon.SWORD,new Hex(left.q+side,left.r),5000,17000);unit.gold=997;unit.energy=100;unit.acted=true;unit.deputies=new int[]{ids[side*3+1],ids[side*3+2]};w.units.add(unit);for(var person:w.army.crew(unit)){w.strategy.releaseGovernor(person.id);person.unitId=unit.id;person.cityId=-1;person.acted=true;}w.districts.deployed(home.id,unit);PcGovernorPolicy.deployed(w,unit,home);}
        w.nextUnitId=3;w.governance.reconcile(false);if(!current){var src=PcScenarioIdentity.saved(w);var oldBytes=new ByteArrayOutputStream();var old=new DataOutputStream(oldBytes);old.writeInt(0x50445531);old.writeInt(1);old.writeUTF(src.scenarioId);old.writeUTF(src.sha);old.writeUTF(src.sourceVariant);old.writeInt(-1);w.extensions.put(PcDuelCampaignPolicy.NAMESPACE,oldBytes.toByteArray());}if(item)w.treasures.place(Treasures.definition("item-030"),Treasures.Place.OFFICER,ids[1]);
        int seed=(int)Long.parseLong(data.get("SEED"));var state=PcDuelSettlementSessionTest.normalized(PcDuelKernel.hex(data.get("MODEL")),PcDuelKernel.hex(data.get("MANAGER")),seed,0,ids,natives);for(int side=0;side<2;side++)PcDuelKernel.writeManager(state.manager,0x18+4*side,side+1);
        var bytes=new ByteArrayOutputStream();var d=new DataOutputStream(bytes);d.writeInt(5);d.writeBoolean(true);d.writeInt(0);d.writeBoolean(true);d.writeInt(0);d.writeBoolean(true);d.writeInt(2);d.writeBoolean(true);d.writeInt(-1);d.writeInt(657);d.writeInt(0);byte[]model=PcDuelModelSave.write(state);d.writeInt(model.length);d.write(model);d.writeInt(0);
        var duel=PcDuelCampaign.read(new DataInputStream(new ByteArrayInputStream(bytes.toByteArray())));PcNativeDebatePolicy.setSeed(w,seed);w.contests.nextId=2;w.contests.session=new Contests.Session(1,w.player,w.turn,1,2,-1);w.contests.session.nativeDuel=duel;return w;
    }
    static int stable(World w,int nativeId)throws Exception {return PcDuelSourceFacts.saved(w).values().stream().filter(f->f.nativeId==nativeId).findFirst().orElseThrow().officerId;}
    static Map<Integer,byte[]> original(Path path)throws Exception {
        String text=Files.readString(path);var ints=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);byte[]parsed=ints.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8);var selected=MapJson.object(MapJson.object(MapJson.parse(parsed)).get("selected"));var out=new HashMap<Integer,byte[]>();for(Object value:MapJson.array(selected.get("peopleAfter"))){var row=MapJson.object(value);out.put(((Number)row.get("nativeId")).intValue(),HexFormat.of().parseHex((String)row.get("hex")));}return out;
    }
    public static void main(String[]args)throws Exception {
        Path endpoint=Path.of(args[0]);var expected=original(Path.of(args[1]));World w=fixture(endpoint,true,false);int dead=stable(w,116),winner=stable(w,14),commander=stable(w,365),deputy=stable(w,466);byte[]pending=SaveCodec.encode(w);check(Arrays.equals(pending,SaveCodec.encode(SaveCodec.decode(pending))),"actual natural pending full World/both RNG cold exact");Files.write(Path.of("out/session-b/natural-death-pending-v3.sg11"),pending);
        try(GameSession game=new GameSession(SaveCodec.decode(pending))){
            var facts=game.contest();check(facts.nativeDuel.terminal&&facts.settlementAvailable&&facts.nativeDuel.disposition.isEmpty()&&facts.nativeDuel.settlementError.isEmpty(),"natural death has actual settlement and no captive menu");check(facts.nativeDuel.teams.get(0).fighters.stream().anyMatch(f->f.officerId==dead&&f.terminalOutcome==2),"API source outcome2/stable casualty id");check(facts.state.equals(game.state())&&Arrays.equals(pending,game.captureSave()),"repeat terminal/casualty query no World/policy/RNG writes");
            var old=game.state();var bad=game.execute(ContestCommand.nativeDuelDisposition(old,facts.contestId,facts.revision,dead,2));check(!bad.ok()&&Arrays.equals(pending,game.captureSave()),"dead participant cannot be released as captive");game.replace(SaveCodec.decode(pending));bad=game.execute(ContestCommand.finishNativeDuel(old,facts.contestId,facts.revision));check(!bad.ok()&&Arrays.equals(pending,game.captureSave()),"cold restore fences old token");
            facts=game.contest();var token=game.state();var finish=game.execute(ContestCommand.finishNativeDuel(token,facts.contestId,facts.revision));check(finish.ok(),"one actual natural campaign terminal "+finish.detail);byte[]finished=game.captureSave();World after=SaveCodec.decode(finished);check(!after.contests.busy()&&PcDuelCampaignPolicy.lastFinished(after)==1,"one saved terminal receipt");check(after.life.state(dead)==Lifecycle.State.DEAD&&after.officer(dead).owner==-1&&after.officer(dead).cityId==-1&&after.officer(dead).unitId==-1&&after.government.merit(dead)==0&&after.officerAbilities.experience(dead,1)==0,"natural dead identity/rank/merit/XP complete cleanup");
            check(after.unit(1).officerId==commander&&Arrays.equals(after.unit(1).deputies,new int[]{deputy})&&after.unit(1).troops==3500&&after.unit(1).energy==85,"original support removal/commander preserved/troop30percent/energy");check(after.unit(1).gold==997&&after.unit(1).food==17000&&after.unit(2).troops==5000&&after.unit(2).energy==100,"both units cargo and winner troops preserved");
            for(int nativeId:new int[]{365,116,466,558,14,517}){int id=stable(after,nativeId);byte[]raw=expected.get(nativeId);var b=ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN);check(PcDuelHealthPolicy.health(after,id)==(raw[0x128]&255),"original all participant HP "+nativeId);check(after.government.merit(id)==Short.toUnsignedInt(b.getShort(0xae)),"original active-only merit "+nativeId);check(after.officerAbilities.experience(id,1)==Short.toUnsignedInt(b.getShort(0x12c)),"original active-only WAR XP "+nativeId);}
            for(int nativeId:new int[]{163,365,466})check(!after.relations.likes(stable(after,nativeId),dead),"original incoming like removed "+nativeId);
            check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(after))==358645160L&&after.strategy.getRandomState()==w.strategy.getRandomState(),"exact original one troop RNG; engine RNG unchanged");check(Arrays.equals(finished,SaveCodec.encode(after)),"whole terminal World cold exact");Files.write(Path.of("out/session-b/natural-death-finished-v3.sg11"),finished);bad=game.execute(ContestCommand.finishNativeDuel(token,1,0));check(!bad.ok()&&Arrays.equals(finished,game.captureSave()),"duplicate terminal old token no write");bad=game.execute(ContestCommand.finishNativeDuel(game.state(),1,0));check(!bad.ok()&&Arrays.equals(finished,game.captureSave()),"fresh token cannot repeat dead terminal");
            check(game.officers().officer(dead).status.equals("已故")&&Arrays.equals(finished,game.captureSave()),"normal officer text actual death/source facts pure");
            for(int turn=0;turn<3;turn++){var ticket=game.beginTurn();World computed=SaveCodec.decode(ticket.initial());var next=computed.nextTurn();check(next.ok,"actual whole AI turn "+next.message);check(game.commitTurn(ticket,computed),"serial whole turn commit");byte[]saved=game.captureSave();game.replace(SaveCodec.decode(saved));check(Arrays.equals(saved,game.captureSave())&&SaveCodec.decode(saved).life.state(dead)==Lifecycle.State.DEAD,"full World/both RNG cold/death persists "+turn);}
        }
        for(boolean current:new boolean[]{false}){World blocked=fixture(endpoint,current,current);byte[]before=SaveCodec.encode(blocked);try(GameSession game=new GameSession(blocked)){var facts=game.contest();check(!facts.settlementAvailable&&!facts.nativeDuel.settlementError.isEmpty()&&Arrays.equals(before,game.captureSave()),"unsupported item/old strategy preview disabled and byte pure");var rejected=game.execute(ContestCommand.finishNativeDuel(facts.state,facts.contestId,facts.revision));check(!rejected.ok()&&rejected.detail.equals(facts.nativeDuel.settlementError)&&Arrays.equals(before,game.captureSave()),"preview/actual rejection exact cause; old/dead item not relabelled");}}
        System.out.println("PASS actual original natural support death/typed campaign/3 whole turns/query/old policy "+checks+" checks; declared terminal, normal deployment/menu/APK pending");
    }
}
