package game.sanguo.core;
import java.util.*;
import game.sanguo.runtime.GameSession;
/** Original full4a93b0/4a5d90/4be2a0/4bd3b0 source0 receipt.
 * Declared current armies/units, not ordinary deployment or APK evidence. */
public final class PcDuelArmyMergeTest {
    static int checks;static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    public static void main(String[]args)throws Exception {
        boolean nopeople=Arrays.asList(args).contains("--nopeople"),departure=Arrays.asList(args).contains("--departure");String source=PcScenarioCatalog.all().get(0).identity.scenarioId;World w=PcScenarioCatalog.load(source,departure?28:3,23,new PcDuelOptions(0,0,0));check(PcDuelCampaignPolicy.read(w).version==3&&PcGovernorPolicy.data(w).format==3,"fresh explicit current army strategy");var facts=PcDuelSourceFacts.saved(w);Map<Integer,Integer>ids=new HashMap<>();for(var f:facts.values())ids.put(f.nativeId,f.officerId);
        byte[]raw;try(var input=PcDuelArmyMergeTest.class.getResourceAsStream(nopeople?"/pc-duel/army-merge-nopeople-source0.json":"/pc-duel/army-merge-source0.json")){check(input!=null,"original merge receipt");raw=input.readAllBytes();}check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(raw)).equals(nopeople?"393927bf6921aaaf6640ceeb31c4ff3555ba780a9ad05ad05a709bd0e3f5ae87":"2512296f0e20d91fabebf40fe73a30f7723154ca45cb5822b74197e3f0de804f"),"original full merge receipt SHA");var receipt=MapJson.object(MapJson.parse(raw));check(receipt.get("exeSha").equals(PcScenarioIdentity.EXE_SHA),"exact original executable");
        int target=ids.get(440),victor=ids.get(558);Hex first=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),next=new Hex(q+1,r);if(w.inside(next)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(next,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(next)&&w.cityAt(h)==null&&w.cityAt(next)==null){first=h;break outer;}}
        int[][]crew={{440,58,114},{558,14,109}};for(int side=0;side<2;side++){var leader=w.officer(ids.get(crew[side][0]));var home=w.city(leader.cityId);var unit=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,10000);unit.deputies=new int[]{ids.get(crew[side][1]),ids.get(crew[side][2])};unit.gold=997;w.units.add(unit);for(int n:crew[side]){var person=w.officer(ids.get(n));check(w.life.present(person.id),"actual source current person "+n);w.strategy.releaseGovernor(person.id);person.unitId=unit.id;person.cityId=-1;}w.districts.deployed(home.id,unit);PcGovernorPolicy.deployed(w,unit,home);}w.nextUnitId=3;
        var data=PcGovernorPolicy.data(w);if(nopeople){for(var entry:data.assignments.entrySet())if(entry.getKey()!=target&&entry.getValue().army==6&&w.life.present(entry.getKey()))entry.getValue().army=5;}else{for(var site:w.cities)if(site.kind==World.SiteKind.CITY&&data.siteArmies.getOrDefault(site.id,-1)==6){data.siteArmies.put(site.id,5);site.governorId=-1;data.vacantSites.add(site.id);}}PcGovernorPolicy.write(w,data);w.governance.reconcile(false);var ap=PcArmyActionPolicy.copy(PcArmyActionPolicy.read(w));ap.points[6]=58;PcArmyActionPolicy.write(w,ap);PcArmyActionPolicy.mirror(w);int primaryBudget=PcArmyActionPolicy.points(w,5);int nativeSeed=PcNativeDebatePolicy.seed(w);long strategySeed=w.strategy.getRandomState();byte[]before=SaveCodec.encode(w);
        PcDuelCapture.validate(w,w.unit(2),w.unit(1),target);check(Arrays.equals(before,SaveCodec.encode(w)),"same admitted merge preview allWorld/RNG pure");
        try(GameSession game=new GameSession(w)){var view=game.legacyView();var result=game.legacy(view.draft,()->{try{PcDuelCapture.apply(view.draft,view.draft.unit(2),view.draft.unit(1),target);return view.draft.success("原军团合并");}catch(java.io.IOException e){return view.draft.fail(e.getMessage());}});check(result.ok,"actual session atomic callback "+result.message);byte[]after=game.captureSave();World current=SaveCodec.decode(after);data=PcGovernorPolicy.data(current);check(data.format==3&&data.mergedArmies.get(6)==5&&data.armyLeaders.get(6)==-1,"saved source6->5/old army inactive");var old=PcGovernorPolicy.view(current).armies.get(6);check(old.originalValid&&old.currentKnown&&!old.currentValid&&old.owner==-1&&old.display==0&&old.openingOwner==28&&old.openingDisplay==2,"original and current army facts remain distinct");check(PcArmyActionPolicy.points(current,6)==0&&PcArmyActionPolicy.points(current,5)==primaryBudget,"original AP58 clears without transferring to primary");
            for(var row:MapJson.array(receipt.get("peopleAfter"))){var person=MapJson.object(row);int nativeId=MapJson.integer(person.get("nativeId"),0,1099);if(!ids.containsKey(nativeId))continue;check(data.assignments.get(ids.get(nativeId)).army==MapJson.integer(person.get("army"),-1,46),"original current administrative army native "+nativeId);}
            for(var row:MapJson.array(receipt.get("sitesAfter"))){var site=MapJson.object(row);int nativeSite=MapJson.integer(site.get("nativeSite"),0,86);var joined=data.source.sites.values().stream().filter(s->s.nativeId==nativeSite).findFirst().orElseThrow();check(data.siteArmies.get(joined.id)==MapJson.integer(site.get("army"),-1,46),"original all87 current site army "+nativeSite);if(nativeSite==13||nativeSite==16){check(current.city(joined.id).governorId==MapJson.integer(site.get("governor"),-1,1099)&&data.vacantSites.contains(joined.id),"original moved-site governor remains vacant "+nativeSite);}}
            check(facts.get(current.unit(1).officerId).nativeId==114&&Arrays.equals(current.unit(1).deputies,new int[]{ids.get(58)})&&data.unitArmies.get(1)==5,"original surviving unit114/58 and new army5");check(current.government.captive(target)&&current.government.prisoner(target).unitId==2,"actual target escort separate from old allegiance");var scene=game.sceneFacts();var dto=scene.administration.armies.stream().filter(a->a.nativeId==6).findFirst().orElseThrow();check(dto.originalValid&&dto.currentKnown&&!dto.currentValid&&dto.owner==-1&&dto.openingOwner==28&&dto.openingDisplay==2&&dto.actionPoints==0&&Arrays.equals(after,game.captureSave()),"immutable scene current/source army facts with exact save/RNG purity");
            check(PcNativeDebatePolicy.seed(current)==nativeSeed&&current.strategy.getRandomState()==strategySeed,"whole merge/capture no RNG");check(Arrays.equals(after,SaveCodec.encode(current)),"complete new current army save cold exact");
            World corrupt=SaveCodec.decode(after);var broken=PcGovernorPolicy.data(corrupt);broken.unitArmies.put(1,6);PcGovernorPolicy.write(corrupt,broken);boolean rejected=false;try{SaveCodec.encode(corrupt);}catch(java.io.IOException e){rejected=true;}check(rejected&&Arrays.equals(after,game.captureSave()),"corrupt active unit in invalid army rejected without touching authority");World badBudget=SaveCodec.decode(after);var badAp=PcArmyActionPolicy.copy(PcArmyActionPolicy.read(badBudget));badAp.points[6]=58;PcArmyActionPolicy.write(badBudget,badAp);rejected=false;try{SaveCodec.encode(badBudget);}catch(java.io.IOException e){rejected=true;}check(rejected&&Arrays.equals(after,game.captureSave()),"merged army cannot carry revived AP58 or silently repair on future turn");
            if(departure){var sourceSite=data.source.sites.values().stream().filter(s->s.nativeId==16).findFirst().orElseThrow();var destSite=data.source.sites.values().stream().filter(s->s.nativeId==3).findFirst().orElseThrow();int officer=ids.get(413);var viewNow=game.legacyView();byte[]pure=game.captureSave();var preview=viewNow.draft.domestic.transferError(sourceSite.id,destSite.id,officer);check(preview==null&&Arrays.equals(pure,game.captureSave()),"ordinary civil departure preview pure");var transfer=game.legacy(viewNow.draft,()->viewNow.draft.domestic.transfer(sourceSite.id,destSite.id,officer));check(transfer.ok,"ordinary real civil departure "+transfer.message);World departed=SaveCodec.decode(game.captureSave());check(facts.get(departed.city(sourceSite.id).governorId).nativeId==436&&!PcGovernorPolicy.data(departed).vacantSites.contains(sourceSite.id),"original full413departure elects native436 at16");byte[]departedSave=game.captureSave();game.replace(SaveCodec.decode(departedSave));check(Arrays.equals(departedSave,game.captureSave()),"complete in-flight transfer/army/vacancy/RNG cold exact");}
            for(int turn=0;turn<3;turn++){var ticket=game.beginTurn();World computed=SaveCodec.decode(ticket.initial());check(computed.nextTurn().ok,"actual whole future merge turn");check(game.commitTurn(ticket,computed),"future turn once");byte[]future=game.captureSave();game.replace(SaveCodec.decode(future));check(Arrays.equals(future,game.captureSave()),"future wholeWorld/allRNG cold exact");current=SaveCodec.decode(future);check(PcArmyActionPolicy.points(current,6)==0&&!PcGovernorPolicy.view(current).armies.get(6).currentValid,"invalid army stays inactive/AP0 after real replenishment");}
        }
        System.out.println("PASS original source0 session army merge "+checks+" checks; explicit units/current city fixture, ordinary APK/ruler/primary reorganization pending");
    }
}
