package game.sanguo.core;
import java.io.*;import java.nio.file.*;import java.util.*;
import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** A constructed terminal endpoint from real original numeric model/manager.
 * TEST ONLY explicit capability bytes: does not create a production initializer
 * or certify ordinary command admission, fees, deployment or capture/death. */
public final class PcDuelSettlementSessionTest {
    static int checks;static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
    // Test-only original pointer-to-stable-ID fixture adapter; no rules or RNG draws.
    static PcDuelModelSave.State normalized(byte[]raw,byte[]manager,int seed,int draws,int[]ids,int[]natives){
        PcDuelKernel m=new PcDuelKernel(raw);m.set(0,1);byte[]savedManager=manager.clone();
        for(int side=0;side<2;side++){
            m.set(0x238+24*side+4,1);PcDuelKernel.writeManager(savedManager,0x18+4*side,side);
            for(int slot=0;slot<3;slot++){int i=side*3+slot;m.set(m.fighter(side,slot),ids[i]);PcDuelKernel.writeManager(savedManager,12*side+4*slot,ids[i]);}
        }
        PcDuelKernel.Random random=new PcDuelKernel.Random(seed);random.draws=draws;
        return new PcDuelModelSave.State(m,savedManager,random,ids,natives);
    }
    public static void main(String[]args)throws Exception{
        String modelHex=null,managerHex=null;int[]natives=null;int captureNative=-1,seed=23;long finalRng=-1;
        for(String line:Files.readAllLines(Path.of(args[0]))){String[]p=line.split("\t");if(p[0].equals("MODEL"))modelHex=p[1];if(p[0].equals("MANAGER"))managerHex=p[1];if(p[0].equals("SEED"))seed=(int)Long.parseLong(p[1]);if(p[0].equals("CAPTURE"))captureNative=Integer.parseInt(p[1]);if(p[0].equals("FINAL_RNG"))finalRng=Long.parseLong(p[1]);if(p[0].equals("NATIVES"))natives=Arrays.stream(p[1].split(",")).mapToInt(Integer::parseInt).toArray();}
        if(modelHex==null||managerHex==null||natives==null)throw new AssertionError("Original endpoint corpus missing");
        boolean sameRegion=Arrays.asList(args).contains("--same-region");World w=sameRegion?PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23,new PcDuelOptions(0,0,0)):PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);boolean solo=natives[4]<0;int[]ids=new int[6];for(int i=0;i<6;i++){if(natives[i]<0){ids[i]=-1;continue;}final int n=natives[i];ids[i]=PcDuelSourceFacts.saved(w).values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}
        boolean ai=Arrays.asList(args).contains("--ai-detain")||Arrays.asList(args).contains("--ai-release")||Arrays.asList(args).contains("--ai-execute")||Arrays.asList(args).contains("--ai-recruit"),recruit=Arrays.asList(args).contains("--recruit-fixture")||Arrays.asList(args).contains("--ai-recruit"),release=Arrays.asList(args).contains("--release")||Arrays.asList(args).contains("--ai-release"),execute=Arrays.asList(args).contains("--execute")||Arrays.asList(args).contains("--ai-execute");if(recruit){seed=0;PcDuelRawLoyalty.invalidate(w,ids[3]);w.officer(ids[3]).loyalty=0;PcDuelRawLoyalty.originalWrite(w,ids[3],0);var expected=new PcDuelKernel.Random(0);check(expected.percent(79),"original raw0/seed0 recruitment oracle succeeds");expected.uniform(50);finalRng=Integer.toUnsignedLong(expected.state);}
        Hex left=null,right=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),k=new Hex(q+1,r);if(w.inside(k)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(k,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(k)&&(!(release||recruit)||PcPersonnelReturnRules.cityAt(w,h)==(sameRegion?21:15)&&PcPersonnelReturnRules.cityAt(w,k)==(sameRegion?21:15))&&w.cityAt(h)==null&&w.cityAt(k)==null){left=h;right=k;break outer;}}
        for(int side=0;side<2;side++){var leader=w.officer(ids[side*3]);World.City home=w.city(leader.cityId);World.Unit u=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,side==0?left:right,5000,10000);u.energy=95;u.acted=true;u.deputies=java.util.stream.IntStream.of(ids[side*3+1],ids[side*3+2]).filter(id->id>=0).toArray();u.gold=997;w.units.add(u);for(int i=0;i<3;i++){if(ids[side*3+i]<0)continue;var o=w.officer(ids[side*3+i]);w.strategy.releaseGovernor(o.id);o.unitId=u.id;o.cityId=-1;o.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}
        w.nextUnitId=3;w.governance.reconcile(false);var state=normalized(PcDuelKernel.hex(modelHex),PcDuelKernel.hex(managerHex),seed,0,ids,natives);for(int side=0;side<2;side++)PcDuelKernel.writeManager(state.manager,0x18+4*side,side+1);
        var bytes=new ByteArrayOutputStream();var out=new DataOutputStream(bytes);out.writeInt(sameRegion?5:ai?4:1);out.writeBoolean(ai||sameRegion);out.writeInt(sameRegion?0:ai?3:-1);out.writeBoolean(sameRegion);out.writeInt(sameRegion?0:-1);if(ai||sameRegion){out.writeBoolean(true);out.writeInt(0);}if(sameRegion){out.writeBoolean(true);out.writeInt(35);}out.writeInt(1000);out.writeInt(0);byte[]model=PcDuelModelSave.write(state);out.writeInt(model.length);out.write(model);if(ai||sameRegion)out.writeInt(0);var duel=PcDuelCampaign.read(new DataInputStream(new ByteArrayInputStream(bytes.toByteArray())));
        var src=PcScenarioIdentity.saved(w);bytes=new ByteArrayOutputStream();out=new DataOutputStream(bytes);out.writeInt(0x50445531);out.writeInt(1);out.writeUTF(src.scenarioId);out.writeUTF(src.sha);out.writeUTF(src.sourceVariant);out.writeInt(-1);if(!sameRegion)w.extensions.put(PcDuelCampaignPolicy.NAMESPACE,bytes.toByteArray());PcNativeDebatePolicy.setSeed(w,seed);
        if(ai){var hold=PcDuelAiDisposition.retention(w,ids[0]);check(hold.rankSalarySum==55,"actual original AI home salary55");if(release)w.city(PcPersonnelReturnRules.projectSite(w,hold.nativeHome)).troops=0;if(execute)w.relations.link(ids[0],ids[3],Relations.Kind.DISLIKE);}
        boolean cleanupFixture=args.length>1&&args[1].equals("rank-book");if(cleanupFixture){if(captureNative<0)throw new AssertionError("capture required for rank/book cleanup");var rank=PcOfficerRanks.all().get(54);w.government.ranks.put(ids[3],rank.projectId);w.government.merits.put(ids[3],Math.max(w.government.merit(ids[3]),rank.merit));w.officerAbilities.refresh(w.officer(ids[3]));w.treasures.place(Treasures.definition("item-030"),Treasures.Place.OFFICER,ids[3]);}
        int winningSide=PcDuelKernel.readManager(state.manager,0x54),winningIndex=winningSide*3+PcDuelKernel.readManager(state.manager,0x5c),losingIndex=(1-winningSide)*3+PcDuelKernel.readManager(state.manager,0x60);int[]meritBefore=new int[6],xpBefore=new int[6],pointsBefore=new int[w.factions.length];for(int i=0;i<6;i++){if(ids[i]<0)continue;meritBefore[i]=w.government.merit(ids[i]);xpBefore[i]=w.officerAbilities.experience(ids[i],1);}for(int side=0;side<pointsBefore.length;side++)pointsBefore[side]=w.campaign.points(side);
        boolean humanFate=Arrays.asList(args).contains("--human-fate");if(humanFate){if(captureNative<0||winningSide!=0)throw new AssertionError("winning capture corpus required");duel.state.model.set(0x24+0xd8,0);}
        boolean commandBoundary=Arrays.asList(args).contains("--command-boundary");if(commandBoundary){if(!ai)throw new AssertionError("explicit format4 settings required for format5 action fixture");duel.commandBoundary=true;duel.opponentActed=false;duel.openingVoice=35;w.unit(2).acted=false;}
        w.contests.nextId=2;var s=new Contests.Session(1,w.player,w.turn,1,2,-1);s.nativeDuel=duel;w.contests.session=s;byte[]pending=SaveCodec.encode(w);check(Arrays.equals(pending,SaveCodec.encode(SaveCodec.decode(pending))),"complete pending endpoint World both RNG save exact");
        try(GameSession game=new GameSession(SaveCodec.decode(pending))){var first=game.state();byte[]before=game.captureSave();var ordinal=ContestCommand.Operation.values();check(ordinal[0]==ContestCommand.Operation.DUEL_MOVE&&ordinal[7]==ContestCommand.Operation.FINISH_NATIVE_DUEL&&ordinal[8]==ContestCommand.Operation.NATIVE_DUEL_INPUT,"existing contest operation ordinals preserved");
        var invalidInput=game.execute(ContestCommand.nativeDuelInput(first,1,1,-1,-1,-1));check(!invalidInput.ok()&&Arrays.equals(before,game.captureSave()),"wrong input revision allWorld bothRNG pure");
        invalidInput=game.execute(ContestCommand.nativeDuelInput(first,1,0,99,99,99));check(!invalidInput.ok()&&Arrays.equals(before,game.captureSave()),"terminal rejects native input allWorld bothRNG pure");
        var stale=game.execute(ContestCommand.finishNativeDuel(first,1,1));check(!stale.ok()&&Arrays.equals(before,game.captureSave()),"wrong contest revision rejection allWorld RNG pure");if(humanFate){
            var opened=game.execute(ContestCommand.finishNativeDuel(first,1,0));check(opened.ok(),"human terminal enters saved disposition phase");
            var pendingFacts=game.contest();check(pendingFacts.nativeDuel.disposition.size()==1&&!pendingFacts.nativeDuel.dispositionReady,"detached current pending disposition");
            byte[]review=game.captureSave();World reviewWorld=SaveCodec.decode(review);check(!reviewWorld.government.captive(ids[3])&&reviewWorld.government.merit(ids[winningIndex])==meritBefore[winningIndex]&&PcNativeDebatePolicy.seed(reviewWorld)==seed,"pending phase does not commit health/capture/rewards/RNG");
            check(Arrays.equals(review,SaveCodec.encode(reviewWorld)),"whole pending disposition save exact");var oldToken=game.state();game.replace(reviewWorld);
            World corrupt=SaveCodec.decode(review);var corruptDuel=corrupt.contests.session.nativeDuel;
            int wrongIndex=0;PcDuelKernel.writeManager(corruptDuel.state.manager,0x64,1);
            PcDuelKernel.writeManager(corruptDuel.state.manager,0x64+12,0);
            corruptDuel.disposition=new PcDuelDisposition(List.of(new PcDuelDisposition.Row(ids[wrongIndex],natives[wrongIndex],15,4)));
            boolean rejected=false;try{SaveCodec.decode(SaveCodec.encode(corrupt));}catch(IOException e){rejected=true;}
            check(rejected&&Arrays.equals(review,game.captureSave()),"saved disposition on winning crew rejects without touching live World");
            World oldRecruit=SaveCodec.decode(review);oldRecruit.contests.session.nativeDuel.disposition.select(ids[3],0);byte[]oldRecruitSave=SaveCodec.encode(oldRecruit);try(GameSession historical=new GameSession(SaveCodec.decode(oldRecruitSave))){check(!historical.contest().nativeDuel.dispositionReady&&!historical.contest().nativeDuel.disposition.get(0).error.isEmpty(),"historical unadmitted choice preview matches submit refusal");var blocked=historical.execute(ContestCommand.finishNativeDuel(historical.state(),1,1));check(!blocked.ok()&&Arrays.equals(oldRecruitSave,historical.captureSave()),"historical format2 choice0 cannot bypass original successful admission");}
            var bad=game.execute(ContestCommand.nativeDuelDisposition(oldToken,1,1,ids[3],1));check(!bad.ok()&&Arrays.equals(review,game.captureSave()),"restore invalidates old disposition token");
            bad=game.execute(ContestCommand.nativeDuelDisposition(game.state(),1,1,ids[3],99));check(!bad.ok()&&Arrays.equals(review,game.captureSave()),"invalid disposition bytepure");
            var previewRows=game.contest().nativeDuel.disposition;check(Arrays.equals(review,game.captureSave()),"current callback previews fullWorld/allRNG pure");for(var preview:previewRows)for(int action=0;action<4;action++)if(!preview.actionErrors.get(action).isEmpty()){var rejectedChoice=game.execute(ContestCommand.nativeDuelDisposition(game.state(),1,1,preview.officerId,action));check(!preview.enabled(action)&&!rejectedChoice.ok()&&rejectedChoice.detail.equals(preview.actionErrors.get(action))&&Arrays.equals(review,game.captureSave()),"unsupported callback disabled/refuses same reason before any saved choice");}

            if(Arrays.asList(args).contains("--attempt-recruit")){int savedSeed=PcNativeDebatePolicy.seed(SaveCodec.decode(game.captureSave()));var attempt=game.execute(ContestCommand.nativeDuelDisposition(game.state(),1,1,ids[3],0));check(attempt.ok()&&!game.contest().nativeDuel.dispositionReady,"native zero-chance refusal commits pending alternatives "+attempt.detail);var row=game.contest().nativeDuel.disposition.get(0);check(row.choice==4&&row.mask==14,"original refusal disables recruitment only");byte[]refused=game.captureSave();check(PcNativeDebatePolicy.seed(SaveCodec.decode(refused))==savedSeed,"native zero chance skips RNG");var duplicate=game.execute(ContestCommand.nativeDuelDisposition(game.state(),1,2,ids[3],0));check(!duplicate.ok()&&Arrays.equals(refused,game.captureSave()),"fresh-token recruitment duplicate cannot redraw");game.replace(SaveCodec.decode(refused));check(Arrays.equals(refused,game.captureSave()),"pending refusal fullWorld/bothRNG cold save");}
            int selectionRevision=game.contest().revision;var chooseToken=game.state();var selected=game.execute(ContestCommand.nativeDuelDisposition(chooseToken,1,selectionRevision,ids[3],recruit?0:execute?3:release?2:1));check(selected.ok()&&game.contest().nativeDuel.dispositionReady,"selected detention pending final confirmation");byte[]selectedBytes=game.captureSave();
            bad=game.execute(ContestCommand.nativeDuelDisposition(chooseToken,1,1,ids[3],1));check(!bad.ok()&&Arrays.equals(selectedBytes,game.captureSave()),"double selection old token rejected");
            if(recruit){check(game.contest().nativeDuel.dispositionReady,"successful original admission ready");World savedRecruit=SaveCodec.decode(selectedBytes);check(savedRecruit.contests.session.nativeDuel.disposition.rows.get(0).recruitmentAdmitted,"format3 carries original successful admission");game.replace(savedRecruit);check(Arrays.equals(selectedBytes,game.captureSave()),"format3 selected recruitment fullWorld/allRNG cold continuation");}
            first=game.state();
        }
        var result=game.execute(ContestCommand.finishNativeDuel(first,1,humanFate?game.contest().revision:0));check(result.ok()&&result.event!=null,"API terminal commits once");byte[]finished=game.captureSave();check(!Arrays.equals(before,finished)&&Arrays.equals(finished,SaveCodec.encode(SaveCodec.decode(finished))),"full terminal World both RNG reload exact");var duplicate=game.execute(ContestCommand.finishNativeDuel(first,1,0));check(!duplicate.ok()&&Arrays.equals(finished,game.captureSave()),"old StateToken duplicate pure");duplicate=game.execute(ContestCommand.finishNativeDuel(game.state(),1,0));check(!duplicate.ok()&&Arrays.equals(finished,game.captureSave()),"fresh token no-session duplicate pure");World restored=SaveCodec.decode(finished);if(commandBoundary&&restored.unit(2)!=null)check(!restored.unit(2).acted,"actual typed terminal preserves opponent previous unspent action");check(!restored.contests.busy()&&PcDuelCampaignPolicy.lastFinished(restored)==1,"one terminal receipt survives save");for(int i=0;i<6;i++){if(ids[i]<0)continue;check(restored.government.merit(ids[i])==meritBefore[i]+(captureNative>=0?(i==winningIndex?200:i==losingIndex&&!execute?10:0):(i==0?10:i==3?100:0)),"only original active terminal merit");check(restored.officerAbilities.experience(ids[i],1)==xpBefore[i]+(captureNative>=0?(i==winningIndex?10:i==losingIndex&&!execute?1:0):(i==0?1:i==3?10:0)),"only original active terminal WAR XP");check(PcDuelHealthPolicy.health(restored,ids[i])==Math.max(1,PcDuelKernel.readManager(duel.state.manager,0x7c+12*(i/3)+4*(i%3))),"all original participant physical health persisted");}for(int side=0;side<pointsBefore.length;side++)check(restored.campaign.points(side)==PcTechniquePoints.after(pointsBefore[side],side==restored.unit(captureNative>=0?1:2).owner?50:0),"winner force-only original TP side="+side+" before="+pointsBefore[side]+" actual="+restored.campaign.points(side));
        if(captureNative<0)check(restored.unit(1).troops==3500&&restored.unit(1).energy==80&&restored.unit(2).energy==100,"native casualty-free troop and energy callback");
        else if(solo){check(restored.unit(2)==null&&restored.unit(1).troops==5000&&restored.unit(1).gold==997&&restored.unit(1).food==10000,"original single captured member deletes loser and no resources transferred");var prisoner=restored.government.prisoner(ids[3]);check(prisoner!=null&&prisoner.unitId==1&&prisoner.cityId==-1,"single captured member escort retained");check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(restored))==finalRng&&finalRng==Integer.toUnsignedLong(seed),"original removed loser skips troop RNG draw");}
        else if(execute){check(restored.unit(2).troops==3500&&restored.unit(2).energy==80&&restored.unit(1).energy==100,"original execution aggregate troop/energy");var dead=restored.officer(ids[3]);var admin=PcGovernorPolicy.data(restored).assignments.get(ids[3]);check(restored.life.state(dead.id)==Lifecycle.State.DEAD&&dead.owner==-1&&dead.cityId==-1&&dead.unitId==-1&&admin.home==-1&&admin.army==-1&&!restored.government.captive(dead.id),"one original death and full administrative removal");check(restored.unit(2).officerId==ids[5]&&Arrays.equals(restored.unit(2).deputies,new int[]{ids[4]}),"original executed commander replacement");check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(restored))==finalRng,"execution exact original terminal RNG");}
        else if(recruit){check(restored.unit(2).troops==3500&&restored.unit(2).energy==80&&restored.unit(1).energy==100,"successful recruit then original troop/energy");check(!restored.government.captive(ids[3])&&restored.officer(ids[3]).owner==restored.unit(1).owner&&restored.officer(ids[3]).loyalty==85&&PcDuelRawLoyalty.current(restored,ids[3])==85,"typed original recruitment new ownership/raw loyalty85");var assigned=PcGovernorPolicy.data(restored).assignments.get(ids[3]);check(assigned.army==0&&assigned.home==8&&PcDuelRelease.remaining(restored,ids[3])==3,"typed original new army/home/return task37");check(restored.unit(2).officerId==ids[5]&&Arrays.equals(restored.unit(2).deputies,new int[]{ids[4]}),"typed recruited commander replacement");check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(restored))==finalRng,"one original recruitment roll then troop RNG");}
        else if(release){check(restored.unit(2).troops==3500&&restored.unit(2).energy==80&&restored.unit(1).energy==100,"original release aggregate loss/energy");check(!restored.government.captive(ids[3])&&restored.unit(2).officerId==ids[5]&&Arrays.equals(restored.unit(2).deputies,new int[]{ids[4]}),"release actual allegiance/replacement");check(PcDuelRelease.busy(restored,ids[3])&&PcDuelRelease.remaining(restored,ids[3])==(sameRegion?0:3),"API terminal task37 saved");var officerFacts=game.officers();check(officerFacts.state.equals(game.state())&&officerFacts.officer(ids[3]).status.equals(sameRegion?"归队中 · 等待人员结算":"归队中 · 剩3旬")&&Arrays.equals(finished,game.captureSave()),"current officer detail return status same-token/allWorld/allRNG pure");check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(restored))==finalRng,"release exact original terminal RNG");if(sameRegion){for(int future=0;future<3;future++){var ticket=game.beginTurn();World computed=SaveCodec.decode(ticket.initial());var turn=computed.nextTurn();check(turn.ok,"actual complete future turn "+turn.message);check(game.commitTurn(ticket,computed),"future turn serial commit");byte[]whole=game.captureSave();game.replace(SaveCodec.decode(whole));check(Arrays.equals(whole,game.captureSave()),"complete future World/all RNG cold exact");if(future==0){check(!PcDuelRelease.busy(computed,ids[3]),"zero task37 resolves in actual first global personnel phase");check(!game.officers().officer(ids[3]).status.contains("归队中")&&Arrays.equals(whole,game.captureSave()),"arrival removes return status with pure normal officer query");}}}}
        else {check(restored.unit(2).troops==3500&&restored.unit(2).energy==80&&restored.unit(1).energy==100,"original capture followed by loser troop/energy writes");var p=restored.government.prisoner(ids[3]);check(p!=null&&p.unitId==1&&p.cityId==-1&&restored.unit(2).officerId==ids[5]&&Arrays.equals(restored.unit(2).deputies,new int[]{ids[4]}),"original linked escort and native517 replacement persist");if(cleanupFixture)check(restored.government.office(ids[3])==null&&restored.treasures.item("item-030").holder==ids[0]&&restored.treasures.item("item-030").place==Treasures.Place.OFFICER,"original native office/book cleanup through API survives complete save");check(Integer.toUnsignedLong(PcNativeDebatePolicy.seed(restored))==finalRng,"exact original full capture callback RNG");}}
        System.out.println("PASS constructed native terminal session "+checks+" checks; ordinary admission/capture/death/APK incomplete");
    }
}
