package game.sanguo.core;
import java.nio.file.*;import java.util.*;import game.sanguo.runtime.GameSession;
/** Original menu callbacks versus explicit new games, pure DTO/whole saves.
 * Android newgame and installed native contest remain separate acceptance. */
public final class PcOpeningOptionsSessionTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static int n(Object x){return ((Number)x).intValue();}
 public static void main(String[]args)throws Exception {
  Path path=Path.of("out/session-b/newgame-option-callback-source0-v3.json");byte[] raw=Files.readAllBytes(path);check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(raw)).equals(PcDuelMenuOptions.RECEIPT_SHA),"full original UI callback receipt pinned");var original=MapJson.object(MapJson.parse(raw));check(Boolean.TRUE.equals(original.get("wholeWorldAndRngRestored")),"full original source0 World/RNG restore");String source=PcScenarioCatalog.all().get(0).identity.scenarioId;
  for(Object value:MapJson.array(original.get("rows"))){var row=MapJson.object(value);var selected=MapJson.array(row.get("uiChoice"));var actual=MapJson.array(row.get("actualRootDifficultyDeathLife"));World w=PcScenarioCatalog.load(source,2,24,PcDuelOptions.fromMenu(n(selected.get(2)),n(selected.get(1)),n(selected.get(0))));byte[]before=SaveCodec.encode(w);try(GameSession game=new GameSession(w)){
   var dto=game.pcOpeningOptions();check(dto.supported&&!dto.defaultsKnown&&dto.automaticOverridesKnown&&Integer.valueOf(0).equals(dto.sourceFlag18)&&dto.hasSavedValues(),"saved choice is not a default; serialized source0 no-override flag is now proven");check(dto.state.equals(game.state())&&Arrays.equals(before,game.captureSave()),"query same StateToken/no wholeWorld or RNG writes");
   for(int k=0;k<3;k++){var group=dto.groups.get(k);check(group.savedValue==n(actual.get(k))&&group.choices.size()==3,"original actual root field versus independently saved choice");var table=MapJson.object(MapJson.array(original.get("tables")).get(k));for(int i=0;i<3;i++){var label=MapJson.object(MapJson.array(table.get("labels")).get(i));var c=group.choices.get(i);check(c.value==i&&c.controlId==n(MapJson.array(table.get("controls")).get(i))&&c.label.equals(label.get("text"))&&c.rawHex.equals(label.get("rawHex")),"actual original control/source bytes/label/value");}}
   byte[] saved=game.captureSave();game.replace(SaveCodec.decode(saved));check(Arrays.equals(saved,game.captureSave())&&game.pcOpeningOptions().groups.get(2).savedValue==n(actual.get(2)),"explicit settings wholeWorld/dualRNG cold exact");boolean immutable=false;try{dto.groups.get(0).choices.clear();}catch(UnsupportedOperationException e){immutable=true;}check(immutable,"detached immutable choices");
  }}
  World old=PcScenarioCatalog.load(source,2,24);byte[] oldBytes=SaveCodec.encode(old);try(GameSession game=new GameSession(old)){check(!game.pcOpeningOptions().hasSavedValues()&&Arrays.equals(oldBytes,game.captureSave())&&PcDuelOptions.current(SaveCodec.decode(game.captureSave()))==null,"three-argument newgame query cannot adopt native choices");}
  Path historical=Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11");byte[] genuine=Files.readAllBytes(historical);World legacy=SaveCodec.decode(genuine);byte[] canonical=SaveCodec.encode(legacy);try(GameSession game=new GameSession(legacy)){check(!game.pcOpeningOptions().hasSavedValues()&&Arrays.equals(canonical,game.captureSave())&&Arrays.equals(genuine,Files.readAllBytes(historical)),"genuine39 reads choices without policy/identity/value/RNG migration");}
  boolean rejected=false;try{PcDuelOptions.fromMenu(3,1,1);}catch(IllegalArgumentException e){rejected=true;}check(rejected,"internal rawlife3 is not a fourth menu choice");World special=PcScenarioCatalog.load(source,2,24,new PcDuelOptions(3,1,1));try(GameSession game=new GameSession(special)){byte[] before=game.captureSave();var dto=game.pcOpeningOptions();check(dto.groups.get(2).savedValue==3&&dto.groups.get(2).savedLabel().equals("待核实")&&Arrays.equals(before,game.captureSave()),"existing explicit internal3 retains its raw value without invented menu label");}
  byte[] checkpoint=Files.readAllBytes(Path.of("out/session-b/duel-ruler-ai-seed1-nonterminal-v1.sg11"));try(GameSession game=new GameSession(SaveCodec.decode(checkpoint))){var contest=game.contest();check(contest.nativeDuel!=null&&contest.nativeDuel.openingOptions!=null&&contest.nativeDuel.openingOptions.state.equals(contest.state)&&Arrays.equals(checkpoint,game.captureSave()),"real archived duel DTO embeds same-state choice facts with format5/World/dualRNG untouched");}
  System.out.println("PASS original menu/newgame/saved-choice API "+checks+" checks; A normal picker/menu/current APK pending");
 }
}
