package game.sanguo.core;
import java.util.*;import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** Natural model loss and original forced AI execution from source dislike.
 * Declared adjacent source units remain distinct from ordinary deployment. */
public final class PcRulerHumanInheritanceSessionTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static void cold(GameSession g)throws Exception{byte[]s=g.captureSave();g.replace(SaveCodec.decode(s));check(Arrays.equals(s,g.captureSave()),"wholeWorld/model/dualRNG cold exact");}
 public static void main(String[]args)throws Exception {
  int preferred=args.length==0?0:Integer.parseInt(args[0]);boolean done=false;
  for(int seed=0;seed<64&&!done;seed++){
   World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,11,seed,new PcDuelOptions(0,0,0));Map<Integer,Integer>ids=new HashMap<>();for(var f:PcDuelSourceFacts.saved(w).values())ids.put(f.nativeId,f.officerId);int ruler=ids.get(180),captor=ids.get(618);check(w.relations.dislikes(captor,ruler),"actual source captor dislikes ruler: original forced EXECUTE");
   Hex first=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex a=new Hex(q,r),b=new Hex(q+1,r);if(w.inside(b)&&w.cost(a,World.Weapon.SWORD)>0&&w.cost(b,World.Weapon.SWORD)>0&&!w.army.water(a)&&!w.army.water(b)&&w.cityAt(a)==null&&w.cityAt(b)==null&&PcPersonnelReturnRules.cityAt(w,b)==15){first=a;break outer;}}check(first!=null,"legal declared land");
   for(int side=0;side<2;side++){var o=w.officer(side==0?ruler:captor);var home=w.city(o.cityId);var u=new World.Unit(side+1,o.owner,o.id,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,17000);u.gold=997;u.deputies=side==0?new int[0]:new int[]{ids.get(343)};w.units.add(u);for(var p:w.army.crew(u)){w.strategy.releaseGovernor(p.id);p.unitId=u.id;p.cityId=-1;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}w.nextUnitId=3;w.governance.reconcile(false);
   try(GameSession game=new GameSession(w)){
    System.out.println("Source180 human ruler / AI618+343 seed "+seed+" stance "+preferred+" chance "+w.contests.nativeDuelCandidates(1,2).get(0).chance);
    var start=game.execute(ContestCommand.startNativeDuel(game.state(),1,2,ruler));check(start.ok(),"typed actual creator "+start.detail);if(game.contest().nativeDuel==null){System.out.println("Original refusal seed "+seed);continue;}
    int inputs=0;while(!game.contest().nativeDuel.terminal&&inputs++<300){var f=game.contest();var legal=f.nativeDuel.choices.stream().filter(c->c.enabled()&&c.special==-1&&c.replacement==-1).toList();var choice=legal.stream().filter(c->c.stance==preferred).findFirst().orElse(legal.get(0));var result=game.execute(ContestCommand.nativeDuelInput(f.state,f.contestId,f.revision,choice.stance,choice.special,choice.replacement));check(result.ok(),"legal human input "+result.detail);cold(game);}
    var terminal=game.contest();check(terminal.nativeDuel.terminal,"natural terminal");var terminalWorld=SaveCodec.decode(game.captureSave());var manager=terminalWorld.contests.current().nativeDuel.state.manager;System.out.println("Natural winner "+terminal.winner+" inputs "+inputs+" outcomes "+PcDuelKernel.readManager(manager,0x64)+" / "+PcDuelKernel.readManager(manager,0x70)+" captor "+PcDuelSourceFacts.saved(terminalWorld).get(terminalWorld.unit(2).officerId).nativeId);var finish=game.execute(ContestCommand.finishNativeDuel(terminal.state,terminal.contestId,terminal.revision));check(finish.ok(),"typed original terminal prepare "+finish.detail);
    if(terminal.winner!=1){if(game.contest().nativeDuel!=null){for(var row:game.contest().nativeDuel.disposition){var f=game.contest();var release=game.execute(ContestCommand.nativeDuelDisposition(f.state,f.contestId,f.revision,row.officerId,1));check(release.ok(),"other natural victory detention "+release.detail);}var f=game.contest();check(game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision)).ok(),"other natural outcome fully finishes");}cold(game);continue;}
    var pending=game.contest();if(pending.nativeDuel==null){cold(game);System.out.println("Natural player loss completed without EXECUTE/pending heir seed "+seed);continue;}check(pending.nativeDuel.inheritance!=null&&pending.nativeDuel.inheritance.rulerId==ruler&&pending.nativeDuel.inheritance.selectedHeir==-1,"actual AI EXECUTE creates saved human heir pending");check(!pending.settlementAvailable&&!pending.nativeDuel.dispositionReady,"cannot confirm without heir");byte[]pendingSave=game.captureSave();var current=SaveCodec.decode(pendingSave);check(current.life.present(ruler)&&current.unit(1)!=null&&current.unit(1).gold==997&&current.government.merit(ruler)==w.government.merit(ruler),"no premature death/unit/cargo/rewards before human choice");int rng=PcNativeDebatePolicy.seed(current);long otherRng=current.strategy.getRandomState();for(int i=0;i<3;i++){game.contest();check(Arrays.equals(pendingSave,game.captureSave()),"DTO reads fullWorld/RNG pure");}cold(game);
    var f=game.contest();var again=game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision));check(!again.ok()&&Arrays.equals(pendingSave,game.captureSave()),"repeated prepare rejects without AI reroll");var invalid=game.execute(ContestCommand.nativeDuelHeir(f.state,f.contestId,f.revision,captor));check(!invalid.ok()&&Arrays.equals(pendingSave,game.captureSave()),"foreign heir rejects pure");
    var chosen=f.nativeDuel.inheritance.candidates.stream().filter(h->h.enabled()).findFirst().orElseThrow();var command=ContestCommand.nativeDuelHeir(f.state,f.contestId,f.revision,chosen.officerId);var choice=game.execute(command);check(choice.ok(),"real typed valid human choice "+choice.detail);byte[]selected=game.captureSave();check(!game.execute(command).ok()&&Arrays.equals(selected,game.captureSave()),"double/stale human choice pure");cold(game);current=SaveCodec.decode(game.captureSave());check(PcNativeDebatePolicy.seed(current)==rng&&current.strategy.getRandomState()==otherRng&&current.life.present(ruler),"choice consumes neitherRNG nor death");
    f=game.contest();finish=game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision));check(finish.ok(),"selected heir original production settlement "+finish.detail);check(game.contest().nativeDuel==null,"once complete human inheritance");current=SaveCodec.decode(game.captureSave());check(current.life.state(ruler)==Lifecycle.State.DEAD&&current.loyalty.ruler(11).id==chosen.officerId&&current.unit(1)==null,"actual chosen human ruler/unit deletion/death");byte[]completed=game.captureSave();check(!game.execute(ContestCommand.finishNativeDuel(game.state(),f.contestId,f.revision)).ok()&&Arrays.equals(completed,game.captureSave()),"settlement cannot repeat");
    for(int turn=0;turn<4;turn++){var ticket=game.beginTurn();var computed=SaveCodec.decode(ticket.initial());check(computed.nextTurn().ok,"complete campaign turn");check(game.commitTurn(ticket,computed),"turn once");cold(game);}current=SaveCodec.decode(game.captureSave());check(current.loyalty.ruler(11).id==chosen.officerId&&current.life.state(ruler)==Lifecycle.State.DEAD,"chosen human heir persists through whole turns");done=true;System.out.println("PASS actual natural human inheritance seed "+seed+" inputs "+inputs+" heir "+chosen.nativeId);
   }
  }
  check(done,"actual original forced AI execution human choice completed");System.out.println("PASS human typed inheritance "+checks+" checks; declared units/ordinary menu/currentAPK pending");
 }
}
