package game.sanguo.core;
import java.nio.file.*;import java.util.*;import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
public final class SessionBActualPhysicalRecoveryTest{
 static int n;static void check(boolean b,String s){n++;if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception{
  byte[]raw=Files.readAllBytes(Path.of(args[0]));try(GameSession game=new GameSession(SaveCodec.decode(raw))){byte[]before=game.captureSave();var f=game.contest();check(f.nativeDuel.physicalRecovery.adoptionAvailable&&!f.nativeDuel.physicalRecovery.enabled,"old terminal readonly adoption");check(Arrays.equals(before,game.captureSave()),"query/cancel full pure");var command=ContestCommand.adoptNativePhysicalRecovery(f.state,f.contestId,f.revision);check(game.execute(command).ok(),"typed explicit adoption");byte[]after=game.captureSave();World a=SaveCodec.decode(before),b=SaveCodec.decode(after);check(Arrays.equals(PcDuelModelSave.write(a.contests.current().nativeDuel.state),PcDuelModelSave.write(b.contests.current().nativeDuel.state))&&a.strategy.getRandomState()==b.strategy.getRandomState(),"model/dual RNG adoption unchanged");check(Arrays.equals(a.extensions.get(PcDuelHealthPolicy.NAMESPACE),b.extensions.get(PcDuelHealthPolicy.NAMESPACE)),"no immediate heal");check(!game.execute(command).ok()&&Arrays.equals(after,game.captureSave()),"stale/double once");game.replace(SaveCodec.decode(after));check(Arrays.equals(after,game.captureSave()),"new policy full cold");f=game.contest();check(f.nativeDuel.physicalRecovery.enabled&&!f.nativeDuel.physicalRecovery.adoptionAvailable,"adopted readonly DTO");}
  byte[]pending=Files.readAllBytes(Path.of(args[1]));try(GameSession game=new GameSession(SaveCodec.decode(pending))){var f=game.contest();var row=f.nativeDuel.disposition.get(0);check(row.mask==14&&row.choice==4&&!row.enabled(0),"real failed attempt no reroll");check(game.execute(ContestCommand.adoptNativePhysicalRecovery(f.state,f.contestId,f.revision)).ok(),"future health policy independently adopts pending save");f=game.contest();check(f.nativeDuel.disposition.get(0).mask==14&&!f.nativeDuel.disposition.get(0).enabled(0),"adoption cannot restore recruit option");check(game.execute(ContestCommand.nativeDuelDisposition(f.state,f.contestId,f.revision,row.officerId,1)).ok(),"ordinary HOLD");f=game.contest();check(game.execute(ContestCommand.finishNativeDuel(f.state,f.contestId,f.revision)).ok(),"once settlement");World settled=SaveCodec.decode(game.captureSave());var facts=PcDuelSourceFacts.saved(settled);int lv=facts.values().stream().filter(v->v.nativeId==660).findFirst().orElseThrow().officerId;int old=PcDuelHealthPolicy.health(settled,lv);for(int i=0;i<3;i++){var ticket=game.beginTurn();World next=SaveCodec.decode(ticket.initial());var result=next.nextTurn();check(result.ok&&game.commitTurn(ticket,next),"whole AI/global turn "+i);World w=SaveCodec.decode(game.captureSave());check(PcDuelHealthPolicy.health(w,lv)>=old,"actual participant heals across real turns");old=PcDuelHealthPolicy.health(w,lv);byte[]save=game.captureSave();game.replace(SaveCodec.decode(save));check(Arrays.equals(save,game.captureSave()),"every whole-turn full cold");}check(old==100,"three turns recover original health to100");}
  check(Arrays.equals(raw,Files.readAllBytes(Path.of(args[0])))&&Arrays.equals(pending,Files.readAllBytes(Path.of(args[1]))),"both real originals retained");System.out.println("PASS actual physical recovery typed policy "+n+" checks; terminal/pending/whole3turn/cold/no reroll; APK pending");
 }
}
