package game.sanguo.core;
import java.nio.file.*;import java.util.*;import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
public final class SessionBActualRecruitItemPolicyTest{
 static int n;static void check(boolean b,String s){n++;if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception{
  byte[]raw=Files.readAllBytes(Path.of(args[0]));World original=SaveCodec.decode(raw);byte[]model=PcDuelModelSave.write(original.contests.current().nativeDuel.state);long rng=original.strategy.getRandomState();
  try(var game=new GameSession(original)){byte[]before=game.captureSave();var f=game.contest();check(f.nativeDuel.recruitItemRecipientNativeId==503&&!f.nativeDuel.recruitItemPolicyEnabled&&f.nativeDuel.recruitItemPolicyAdoptionAvailable,"actual old item recipient503 DTO");check(Arrays.equals(before,game.captureSave()),"query/cancel pure");var command=ContestCommand.adoptNativeRecruitItemRecipient(f.state,f.contestId,f.revision);var r=game.execute(command);check(r.ok(),"typed explicit item adoption "+r.detail);byte[]after=game.captureSave();World w=SaveCodec.decode(after);check(Arrays.equals(model,PcDuelModelSave.write(w.contests.current().nativeDuel.state))&&rng==w.strategy.getRandomState(),"original numerical model/dual RNG unchanged");World old=SaveCodec.decode(before);for(var item:old.treasures.items()){var next=w.treasures.item(item.definition.id);check(next.place==item.place&&next.holder==item.holder,"actual adoption no item movement "+item.definition.id);}for(var o:old.officers){var next=w.officer(o.id);check(next.owner==o.owner&&next.cityId==o.cityId&&next.unitId==o.unitId&&next.loyalty==o.loyalty,"actual adoption no officer movement or loyalty "+o.id);}check(Arrays.equals(old.extensions.get(PcDuelRawLoyalty.NAMESPACE),w.extensions.get(PcDuelRawLoyalty.NAMESPACE)),"raw unknown/trust bytes preserved");check(!game.execute(command).ok()&&Arrays.equals(after,game.captureSave()),"stale double once");game.replace(SaveCodec.decode(after));check(Arrays.equals(after,game.captureSave()),"whole new policy cold exact");f=game.contest();check(f.nativeDuel.recruitItemRecipientNativeId==403&&f.nativeDuel.humanActorNativeId==503,"item recipient and legacy probability judge independent");}
  byte[]attempt=Files.readAllBytes(Path.of(args[1]));try(var game=new GameSession(SaveCodec.decode(attempt))){byte[]before=game.captureSave();var f=game.contest();check(!f.nativeDuel.recruitItemPolicyEnabled&&!f.nativeDuel.recruitItemPolicyAdoptionAvailable&&f.nativeDuel.recruitItemRecipientNativeId==503&&f.nativeDuel.humanActorNativeId==403,"actual failed attempt old item/new human policies preserved");var r=game.execute(ContestCommand.adoptNativeRecruitItemRecipient(f.state,f.contestId,f.revision));check(!r.ok()&&Arrays.equals(before,game.captureSave()),"failed attempt cannot rebind or re-roll");game.replace(SaveCodec.decode(before));check(Arrays.equals(before,game.captureSave()),"actual failed pending full cold exact");}
  check(Arrays.equals(raw,Files.readAllBytes(Path.of(args[0])))&&Arrays.equals(attempt,Files.readAllBytes(Path.of(args[1]))),"both actual original files retained");System.out.println("PASS actual recruit item policy "+n+" checks; fresh APK still required");
 }
}
