gradle.beforeProject { project ->
 project.plugins.withId('com.android.application') {
  project.extensions.getByName('androidComponents').finalizeDsl { android ->
   android.defaultConfig.testInstrumentationRunner = 'game.sanguo.mobile.SessionBOfficerContentInstrumentation'
   android.defaultConfig.buildConfigField 'String', 'SOURCE_REVISION', '"B664c00f4-candidate61-r27+A925748c6-closure227"'
  }
 }
}
