package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.os.*;import android.view.*;import android.widget.*;import game.sanguo.core.*;import java.io.*;import java.nio.file.Files;import java.util.*;
/** Ordinary source0/force28/verified native58 deployment; no injected person/stock/world. */
public final class SessionBCapacityInstrumentation extends SessionBFieldworksInstrumentation {
 @Override public void onStart(){Bundle result=new Bundle();try{
  evidence=new File(getTargetContext().getExternalFilesDir("session-b"),coldMode?"capacity-cold":"capacity");evidence.mkdirs();put("output",evidence);
  activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));put("activity",activity);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
  if(coldMode){byte[] expected=Files.readAllBytes(new File(getTargetContext().getExternalFilesDir("session-b"),"capacity/actual-source.sg11").toPath());check(Arrays.equals(expected,capture()),"cold process auto-resumes exact source/capacity/deployment/bothRNG");nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));check(Arrays.equals(expected,capture()),"cold ordinary manual load exact source/capacity/bothRNG");shot("cold-restored");result.putString("stream","PASS SESSION B CAPACITY COLD complete campaign/save/bothRNG; ARM pending\n");}
  else{
   byte[] original=capture();var source=PcScenarioCatalog.all().get(0);World reference=PcScenarioCatalog.preview(source.identity.scenarioId);String faction=reference.faction(28);
   nav("菜单");text("新游戏 / 选择势力");revealDescription("选择PC来源剧本 "+source.identity.path);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("确认开局势力"));revealDescription("选择势力 · "+faction);description("确认开局势力");text("开始新局");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
   World w=SessionProbe.view(activity);check(w.scenarioId.equals(source.identity.scenarioId)&&w.player==28&&!Arrays.equals(original,capture()),"ordinary menu creates exact source0/force28");World.Officer leader=null;String record="";for(var p:PcScenarioPeople.saved(w))if(p.nativeId==58){leader=w.officer(p.officerId);record=p.recordSha;break;}
   check(leader!=null&&leader.id==10058&&w.life.present(leader.id)&&w.government.commandLimit(leader.id)==13000,"verified native58/runtime/record current authority13000");World.City city=w.city(leader.cityId);check(city!=null&&w.idle(city).contains(leader)&&city.troops>=13000&&city.food>=26000&&city.gold>=500,"ordinary stock/person admission sufficient");int leaderId=leader.id;String leaderName=leader.name;note("source="+source.identity.scenarioId+" variant="+source.identity.sourceVariant+" native58/runtime="+leaderId+" record="+record+" name="+leaderName+" city="+city.id+" owner="+leader.owner+" capacity="+w.government.commandLimit(leaderId));
   shot("source-new");nav("地图");revealDescription("定位己方据点 "+city.name);byte[] draft=capture();text("出征");ListView roster=(ListView)tag("deploy.officers");invoke("showRosterTag",new Class<?>[]{ListView.class,String.class},roster,"deploy.role."+leaderId);tap(tag("deploy.role."+leaderId));await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().equals("从编队移除 "+leaderName));tap(tag("deploy.tab.1"));description("剑兵 无需库存");
   enterQuantity("兵力数量","13000");enterQuantity("粮食数量","26000");enterQuantity("金钱数量","500");
   shot("deployment-13000-preview");check(Arrays.equals(draft,capture()),"actual13000 preview preserves full world/RNG");World before=SessionProbe.view(activity);int stock=before.city(city.id).troops,food=before.city(city.id).food,gold=before.city(city.id).gold,count=before.units.size();long revision=activity.deploymentState().revision;tap(tag("deploy.confirm"),2);settle();
   w=SessionProbe.view(activity);World.Unit u=w.unit(w.officer(leaderId).unitId);check(u!=null&&u.troops==13000&&u.food==26000&&u.gold==500&&u.weapon==World.Weapon.SWORD,"ordinary widgets actually deploy13000");check(w.city(city.id).troops==stock-13000&&w.city(city.id).food==food-26000&&w.city(city.id).gold==gold-500&&w.units.size()==count+1&&activity.deploymentState().revision==revision+1,"double-confirm depletes exact stock/food/gold once");shot("actual-13000-deployed");byte[] deployed=capture();Files.write(new File(evidence,"actual-source.sg11").toPath(),deployed);
   boolean existed=new File(activity.getFilesDir(),"manual3.sg11").exists();nav("菜单");text("保存局面");preparedOption("槽位 3");if(existed)text("覆盖存档");check(Arrays.equals(deployed,Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath())),"ordinary save exact full source/capacity/deployment/RNG");
   for(int i=0;i<3;i++)advance("capacity-normal-"+i);shot("three-normal-turns");nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));check(Arrays.equals(deployed,capture()),"ordinary load restores exact13000 deployment and bothRNG");
   result.putString("stream","PASS SESSION B CAPACITY source0/native58 normal menu/force/roster/13000 preview/double-confirm exact cost/three wholeturns/manual save-load/fullWorld/bothRNG; cold and ARM separate\n");
  }
 }catch(Throwable t){result.putString("stream","FAIL SESSION B CAPACITY "+android.util.Log.getStackTraceString(t));try{shot("failed");}catch(Throwable ignored){}}
 finally{try{if(activity!=null)runOnMainSync(activity::finish);settle();}catch(Throwable t){result.putString("stream",result.getString("stream")+"\nFAIL lifecycle "+t);}}
 try{Files.write(new File(evidence,"result.txt").toPath(),result.getString("stream").getBytes("UTF-8"));}catch(Exception ignored){}finish(Activity.RESULT_OK,result);
 }
 private void enterQuantity(String name,String value)throws Exception{revealDescription(name);EditText e=(EditText)await(v->v instanceof EditText&&name.equals(v.getContentDescription()));invoke("enter",new Class<?>[]{EditText.class,String.class},e,value);sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);settle();}
}
