package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.os.*;import android.view.*;import android.widget.*;
import game.sanguo.core.*;import game.sanguo.api.*;import java.io.*;import java.nio.file.Files;import java.util.*;
/** Real source/menu/deployment/explicit MOVE vs ATTACK route/capture/save/cold; no rule injection. */
public final class SessionAAttackTaskInstrumentation extends SessionAScenePresentationInstrumentation {
 private World.Officer person(World w,int nativeId)throws Exception{for(var p:PcScenarioPeople.saved(w))if(p.nativeId==nativeId)return w.officer(p.officerId);throw new AssertionError("strict native/runtime source join "+nativeId);}
 private void quantity(String name,String value)throws Exception{revealDescription(name);EditText e=(EditText)await(v->v instanceof EditText&&name.equals(v.getContentDescription()));invoke("enter",new Class<?>[]{EditText.class,String.class},e,value);sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();}
 private MarchOrders.Plan pending()throws Exception{return (MarchOrders.Plan)field(activity,"pendingMarch");}
 private void store()throws Exception{
  byte[] saved=capture();File slot=new File(activity.getFilesDir(),"manual3.sg11");boolean existed=slot.isFile();nav("菜单");text("保存局面");preparedOption("槽位 3");if(existed)text("覆盖存档");long until=SystemClock.uptimeMillis()+120000;while(SystemClock.uptimeMillis()<until&&(!slot.isFile()||!Arrays.equals(saved,Files.readAllBytes(slot.toPath()))))SystemClock.sleep(100);check(slot.isFile()&&Arrays.equals(saved,Files.readAllBytes(slot.toPath())),"actual full attack/capture Save/RNG normal manual slot");Files.write(new File(evidence,"actual-build.sg11").toPath(),saved);
 }
 @Override public void onStart(){Bundle result=new Bundle();try{
  evidence=new File(getTargetContext().getExternalFilesDir("session-b"),coldMode?"fieldworks-cold":"fieldworks");evidence.mkdirs();put("output",evidence);activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));put("activity",activity);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
  if(coldMode){
   byte[] expected=Files.readAllBytes(new File(getTargetContext().getExternalFilesDir("session-b"),"fieldworks/actual-build.sg11").toPath());check(Arrays.equals(expected,capture()),"actual new process attack/capture full autosave bothRNG");verifySceneFacts("cold-attack");nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));settle();check(Arrays.equals(expected,capture()),"actual new process ordinary manual full attack save bothRNG");verifySceneFacts("cold-attack-manual");result.putString("stream","PASS SESSION A ATTACK COLD new-process full capture/save/RNG/map; ARM pending\n");
  }else{
   var source=PcScenarioCatalog.all().get(0);int faction=29;String name=PcScenarioCatalog.preview(source.identity.scenarioId).faction(faction);
   nav("菜单");text("新游戏 / 选择势力");revealDescription("选择PC来源剧本 "+source.identity.path);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("确认开局势力"));revealDescription("选择势力 · "+name);description("确认开局势力");text("开始新局");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));settle();
   World w=SessionProbe.view(activity);check(w.player==faction,"real source/faction29");World.Officer ruler=person(w,91);World.City city=w.city(ruler.cityId),port=w.city(20057);check(port!=null&&port.owner==-1,"strict actual neutral source port57 target");
   nav("地图");description("定位己方据点 "+city.name);text("出征");ListView roster=(ListView)tag("deploy.officers");invoke("showRosterTag",new Class<?>[]{ListView.class,String.class},roster,"deploy.role."+ruler.id);tap(tag("deploy.role."+ruler.id));await(v->("从编队移除 "+ruler.name).equals(v.getContentDescription()));tap(tag("deploy.tab.1"));description("剑兵 无需库存");quantity("兵力数量","5000");quantity("粮食数量","20000");tap(tag("deploy.confirm"));w=SessionProbe.view(activity);int unit=person(w,91).unitId;check(unit>=0,"normal army deployment");selectUnit(unit);pose(port.hex);
   byte[] before=capture();StateToken prior=activity.deploymentState();text("行军");tile(port.hex);MarchOrders.Plan move=pending();check(move!=null&&move.order.intent==MarchOrders.Intent.MOVE&&move.order.kind==MarchOrders.Kind.TILE&&move.target.equals(port.hex),"ordinary selected neutral site retains exact MOVE/TILE without attack inference");text("取消");check(Arrays.equals(before,capture())&&prior.equals(activity.deploymentState()),"MOVE preview/cancel wholeSave/RNG/token unchanged");
   tap(tag("unit.attack-task"));tile(port.hex);MarchOrders.Plan attack=pending();check(attack!=null&&attack.valid()&&attack.order.intent==MarchOrders.Intent.ATTACK&&attack.order.kind==MarchOrders.Kind.CITY&&attack.order.targetId==port.id&&attack.target.equals(port.hex),"explicit attack task exact neutral CITY/ATTACK pure authority plan");check(!attack.path.isEmpty()&&!attack.path.get(attack.path.size()-1).equals(port.hex),"attack path ends in admitted outside firing range");shot("01-explicit-attack-preview");text("取消");check(Arrays.equals(before,capture())&&prior.equals(activity.deploymentState()),"explicit attack preview/cancel full Save/RNG/token unchanged");
   tap(tag("unit.attack-task"));tile(port.hex);text("确认任务");w=SessionProbe.view(activity);World.Unit u=w.unit(unit);check((u!=null&&u.march!=null&&u.march.intent==MarchOrders.Intent.ATTACK&&u.march.kind==MarchOrders.Kind.CITY&&u.march.targetId==port.id)||w.city(port.id).owner==faction,"actual confirmation commits explicit attack or immediate valid capture");shot("02-committed-attack-route");
   for(int turn=0;turn<12&&SessionProbe.view(activity).city(port.id).owner!=faction;turn++)advance("explicit-attack-capture-"+turn);
   w=SessionProbe.view(activity);check(w.city(port.id).owner==faction,"actual multiple whole-turn continuous attack captures neutral port");check(w.unit(unit)==null&&person(w,91).cityId==port.id,"actual attack capture automatically garrisons full surviving formation");check(PcGovernorPolicy.view(w).siteArmies.get(port.id)==7&&!PcGovernorPolicy.view(w).unitArmies.containsKey(unit),"actual native army7 administration follows capture and retirement");shot("03-actual-task-capture");verifySceneFacts("actual-attack-capture");store();byte[] expected=capture();advance("after-capture-save");nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));settle();check(Arrays.equals(expected,capture()),"normal captured campaign entire save/bothRNG readback");verifySceneFacts("actual-attack-readback");Files.write(new File(evidence,"actual-build.sg11").toPath(),capture());result.putString("stream","PASS SESSION A ATTACK normal Source0/faction29/native91/deploy/exactMOVE-cancel/explicitCITY-ATTACK-cancel/confirm/multi-turn/neutral57-capture/automaticgarrison/nativearmy7/fullsave-read; cold and ARM separate\n");
  }
 }catch(Throwable failure){result.putString("stream","FAIL SESSION A ATTACK "+android.util.Log.getStackTraceString(failure));try{shot("failed");}catch(Throwable ignored){}}
 finally{try{if(activity!=null)runOnMainSync(()->activity.finish());settle();}catch(Throwable failure){result.putString("stream",result.getString("stream","")+"\nFAIL lifecycle "+failure);}}
 try{Files.write(new File(evidence,"result.txt").toPath(),result.getString("stream","").getBytes("UTF-8"));}catch(Exception ignored){}finish(Activity.RESULT_OK,result);
 }
}
