package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.os.Bundle;import android.view.*;import android.widget.*;
import game.sanguo.core.*;import java.io.File;import java.nio.file.Files;import java.util.*;

/** Normal continuation of exact real r25 supply checkpoint. No manufactured save or rule edits. */
public final class SessionBMilitaryContinuationInstrumentation extends SessionBFieldworksInstrumentation {
 private void save(byte[] expected)throws Exception{boolean existed=new File(activity.getFilesDir(),"manual3.sg11").exists();nav("菜单");text("保存局面");preparedOption("槽位 3");if(existed)text("覆盖存档");check(Arrays.equals(expected,Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath())),"normal manual save whole World/RNG exact");}
 private void load()throws Exception{nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));settle();}
 private static String sha(byte[] b)throws Exception{StringBuilder text=new StringBuilder();for(byte v:java.security.MessageDigest.getInstance("SHA-256").digest(b))text.append(Character.forDigit((v>>>4)&15,16)).append(Character.forDigit(v&15,16));return text.toString();}
 private void militaryManagement(World.City c)throws Exception{
  nav("地图");revealDescription("定位己方据点 "+c.name);ClientState ui=(ClientState)field(activity,"ui");if(!ui.panelVisible)description("选中对象指令 ·");if(!ui.panelExpanded)text("展开");text("概览");
  runOnMainSync(()->{View hit=search(activity.getWindow().getDecorView(),v->v instanceof Button&&((Button)v).getText().toString().startsWith("军政 / 俘虏 / 官职"));if(hit!=null)hit.requestRectangleOnScreen(new android.graphics.Rect(0,0,hit.getWidth(),hit.getHeight()),true);});settle();text("军政 / 俘虏 / 官职");
  // Last row may be outside the stock alert viewport; scroll the actual list.
  runOnMainSync(()->{for(View root:android.view.inspector.WindowInspector.getGlobalWindowViews())if(root.hasWindowFocus()){View hit=search(root,v->v instanceof ListView);if(hit!=null)((ListView)hit).setSelection(10);}});settle();option("军事设施管理");
 }
 private void demolition(int sid)throws Exception{
  World w=SessionProbe.view(activity);var c=w.city(20008);int actor=w.idle(c).get(0).id;
  militaryManagement(c);option("阵 · ");option(w.officer(actor).name);byte[] before=capture();text("取消");check(Arrays.equals(before,capture()),"ordinary demolition cancel exact");
  militaryManagement(c);option("阵 · ");option(w.officer(actor).name);
  long revision=activity.deploymentState().revision;View execute=await(v->v instanceof Button&&"执行".contentEquals(((Button)v).getText()));tap(execute,2);settle();w=SessionProbe.view(activity);check(w.war.structures().stream().noneMatch(s->s.id==sid)&&w.unit(1).gold==1000&&activity.deploymentState().revision==revision+1,"ordinary city demolition once, shell removed/no refund");
 }
 @Override public void onStart(){Bundle result=new Bundle();try{
  evidence=new File(getTargetContext().getExternalFilesDir("session-b"),coldMode?"military-continuation-cold":"military-continuation-normal");evidence.mkdirs();put("output",evidence);
  activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));put("activity",activity);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
  if(coldMode){
   byte[] expected=Files.readAllBytes(new File(getTargetContext().getExternalFilesDir("session-b"),"military-continuation-normal/started.sg11").toPath());check(Arrays.equals(expected,capture()),"new process exact unfinished source/World/dual RNG");load();check(Arrays.equals(expected,capture()),"ordinary cold manual load exact unfinished construction");World old=SaveCodec.decode(expected);var oldShell=old.fieldworks.project(1);check(oldShell!=null&&!oldShell.complete,"real saved unfinished shell");Hex site=oldShell.hex;int sid=oldShell.id;
   advance("cold-unfinished-completion");World w=SessionProbe.view(activity);var shell=w.war.at(site);check(shell!=null&&shell.id==sid&&shell.complete&&shell.builder<0&&w.unit(1).gold==1000&&w.unit(1).acted&&w.fieldworks.defensePercent(w.unit(1))>=15,"normal next full turn completes and activates camp, no second payment");verifySceneFacts("completed");shot("completed");Files.write(new File(evidence,"completed.sg11").toPath(),capture());
   demolition(sid);w=SessionProbe.view(activity);check(w.fieldworks.buildCheck(1,War.StructureKind.CAMP,site,0).code.equals("UNIT_COMMAND"),"demolition does not reset construction unit spent action");advance("demolished-action-reset");w=SessionProbe.view(activity);check(w.fieldworks.buildCheck(1,War.StructureKind.CAMP,site,0).allowed(),"normal subsequent turn frees action and exact grid can be rebuilt");byte[] done=capture();save(done);load();check(Arrays.equals(done,capture()),"normal demolished campaign final manual save/load exact");Files.write(new File(evidence,"final.sg11").toPath(),done);shot("demolished-final");
  }else{
   byte[] actual=Files.readAllBytes(new File(evidence,"continue-input.sg11").toPath());check(sha(actual).equals("791bc706d94ed98e7737e24e4ca83c14f4ad414dcd7cbc68f513e0f8887d906d"),"only genuine r25 actual checkpoint");load();check(Arrays.equals(actual,capture()),"ordinary prior actual checkpoint load, no seed/gold/unit/stat edits");World w=SessionProbe.view(activity);check(w.player==2&&w.unit(1).gold==1500&&w.unit(1).troops==7000,"same genuine Sun ordinary campaign");
   Hex to=new Hex(96,155),site=new Hex(96,154);World preview=SaveCodec.decode(actual);check(preview.move(1,to).ok&&preview.fieldworks.buildCheck(1,War.StructureKind.CAMP,site,0).allowed()&&SiteFootprint.distance(preview.city(20008),site)==3,"current exact legal map route under unchanged seven-cell limits");check(Arrays.equals(actual,capture()),"route forecast pure all World/RNG");selectUnit(1);pose(to);text("行军");tile(to);text("确认任务");settle();w=SessionProbe.view(activity);check(w.unit(1).hex.equals(to),"real ordinary map movement exact legal endpoint");
   selectUnit(1);pose(site);byte[] before=capture();militaryMenu();option("阵 · 金500");tile(site);shot("normal-build-confirmation");text("取消");check(Arrays.equals(before,capture()),"normal build confirm cancel exact");text("取消选取");
   selectUnit(1);pose(site);militaryMenu();option("阵 · 金500");tile(site);long revision=activity.deploymentState().revision;View execute=await(v->v instanceof Button&&"执行".contentEquals(((Button)v).getText()));tap(execute,2);settle();w=SessionProbe.view(activity);var shell=w.war.at(site);check(shell!=null&&!shell.complete&&shell.builder==1&&shell.hp==564&&w.unit(1).gold==1000&&w.unit(1).acted&&activity.deploymentState().revision==revision+1,"actual carried-gold500 debit/action/564 shell once");int sid=shell.id;byte[] started=capture();Files.write(new File(evidence,"started.sg11").toPath(),started);verifySceneFacts("started");save(started);
   selectUnit(1);unitAction("中止施工");byte[] stopBefore=capture();text("取消");check(Arrays.equals(stopBefore,capture()),"ordinary stop cancel exact");selectUnit(1);unitAction("中止施工");revision=activity.deploymentState().revision;execute=await(v->v instanceof Button&&"执行".contentEquals(((Button)v).getText()));tap(execute,2);settle();w=SessionProbe.view(activity);check(w.war.at(site).builder<0&&w.war.at(site).hp==564&&w.unit(1).gold==1000&&w.unit(1).acted&&activity.deploymentState().revision==revision+1,"ordinary stop once/no refund or action restoration");
   advance("stopped-shell");w=SessionProbe.view(activity);check(w.war.at(site)!=null&&w.war.at(site).hp==564&&!w.war.at(site).complete&&!w.unit(1).acted,"normal whole stopped turn keeps exact shell and releases next action");selectUnit(1);unitAction("补修军事设施");option("阵 · ");byte[] repairBefore=capture();text("取消");check(Arrays.equals(repairBefore,capture()),"repair confirmation cancel exact");selectUnit(1);unitAction("补修军事设施");option("阵 · ");revision=activity.deploymentState().revision;execute=await(v->v instanceof Button&&"执行".contentEquals(((Button)v).getText()));tap(execute,2);settle();w=SessionProbe.view(activity);check(w.war.at(site).id==sid&&w.war.at(site).complete&&w.war.at(site).hp==1100&&w.unit(1).gold==1000&&w.unit(1).acted&&activity.deploymentState().revision==revision+1,"same actual stopped shell repair completes once/no second gold");Files.write(new File(evidence,"repaired.sg11").toPath(),capture());shot("repaired");
   load();check(Arrays.equals(started,capture()),"ordinary load restores exact saved unfinished shell after actual turn and repair, full World/dual RNG");shot("restored-unfinished");
  }
  result.putString("stream","PASS SESSION B MILITARY CONTINUATION"+(coldMode?" COLD":"")+" actual r25 ordinary military controls/World dual RNG; enemy destruction/fire/all sources/ARM remain separate\n");
 }catch(Throwable t){result.putString("stream","FAIL SESSION B MILITARY CONTINUATION "+android.util.Log.getStackTraceString(t));try{Files.write(new File(evidence,"failed.sg11").toPath(),capture());shot("failed");}catch(Throwable ignored){}}
 finally{try{if(activity!=null)runOnMainSync(activity::finish);settle();}catch(Throwable t){result.putString("stream",result.getString("stream")+"\nFAIL lifecycle "+t);}}
 try{if(evidence!=null)Files.write(new File(evidence,"result.txt").toPath(),result.getString("stream").getBytes("UTF-8"));}catch(Exception ignored){}finish(Activity.RESULT_OK,result);}
}
