package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.os.Bundle;import android.view.*;import android.widget.*;
import game.sanguo.api.*;import game.sanguo.core.*;import java.io.File;import java.nio.file.Files;import java.util.*;

/** Normal content menu/list/search/detail from genuine saved campaign, no replacement DTOs. */
public final class SessionBOfficerContentInstrumentation extends SessionBFieldworksInstrumentation {
 private static String sha(byte[] b)throws Exception{StringBuilder text=new StringBuilder();for(byte v:java.security.MessageDigest.getInstance("SHA-256").digest(b))text.append(Character.forDigit((v>>>4)&15,16)).append(Character.forDigit(v&15,16));return text.toString();}
 private void load()throws Exception{nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));settle();}
 private void save(byte[] expected)throws Exception{nav("菜单");text("保存局面");preparedOption("槽位 3");text("覆盖存档");check(Arrays.equals(expected,Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath())),"ordinary manual save remains exact original World/dual RNG");}
 private void pageAction(String s)throws Exception{runOnMainSync(()->{View hit=search(activity.getWindow().getDecorView(),v->v instanceof Button&&((Button)v).getText().toString().startsWith(s));if(hit!=null)hit.requestRectangleOnScreen(new android.graphics.Rect(0,0,hit.getWidth(),hit.getHeight()),true);});settle();text(s);}
 private void openContent()throws Exception{nav("菜单");pageAction("全国资料 / 核验目录");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("登记人数不等于有效人物完整覆盖"));}
 private void find(String query)throws Exception{EditText input=(EditText)await(v->v instanceof EditText&&"搜索资料".equals(v.getContentDescription()));tap(input);runOnMainSync(()->{input.setSelection(0,input.getText().length());android.view.inputmethod.InputConnection connection=input.onCreateInputConnection(new android.view.inputmethod.EditorInfo());if(connection==null||!connection.commitText(query,1))throw new AssertionError("normal editor input connection unavailable");});settle();check(query.contentEquals(input.getText()),"actual search editor receives requested Unicode text");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();}
 private void inspect(OfficerSnapshot.Officer o,byte[] before,String label)throws Exception{
  find(Integer.toString(o.id));option(o.name+" · ID "+o.id);String expected=CurrentOfficerContent.detail(o);TextView body=(TextView)await(v->v instanceof TextView&&((TextView)v).getText().toString().startsWith("稳定人物 ID "+o.id));check(expected.contentEquals(body.getText()),"actual normal content full detail exact saved DTO "+label);check(Arrays.equals(before,capture()),"actual content list/search/detail preserves full World/dual RNG "+label);shot("detail-"+label);text("返回");
 }
 @Override public void onStart(){Bundle result=new Bundle();try{
  evidence=new File(getTargetContext().getExternalFilesDir("session-b"),coldMode?"officer-content-cold":"officer-content-normal");evidence.mkdirs();put("output",evidence);activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));put("activity",activity);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
  byte[] actual=Files.readAllBytes(new File(getTargetContext().getExternalFilesDir("session-b"),"officer-content-normal/continue-input.sg11").toPath());check(sha(actual).equals("533e5f5a041abbdc35669755b67fa1412afe6ad2ee88e56c6d2115e6d31b7d70"),"exact genuine r26 ordinary campaign checkpoint");
  if(coldMode)check(Arrays.equals(actual,capture()),"new process auto-resumes exact actual campaign, no content backfill");load();check(Arrays.equals(actual,capture()),"ordinary actual checkpoint manual load all World/dual RNG exact");OfficerSnapshot[] dto={null};runOnMainSync(()->dto[0]=activity.officerSnapshot());check(dto[0].state.equals(activity.deploymentState()),"current authoritative DTO same actual StateToken");openContent();
  inspect(dto[0].officer(10365),actual,"sun");inspect(dto[0].officer(156234),actual,"font-184");inspect(dto[0].officer(844857),actual,"font-229");inspect(dto[0].officer(598828),actual,"font-249");inspect(dto[0].officer(850922),actual,"font-616");
  var font=dto[0].officer(156234);find(font.source.courtesy.isEmpty()?font.name:font.source.courtesy);option(font.name+" · ID "+font.id);await(v->v instanceof TextView&&((TextView)v).getText().toString().startsWith("稳定人物 ID "+font.id));check(Arrays.equals(actual,capture()),"normal original name/courtesy search exact and pure");text("当前武将");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains(font.source.biography));shot("existing-current-officer-detail");text("返回");
  find("不会存在的查询 903721");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("没有符合条件的资料"));check(Arrays.equals(actual,capture()),"empty search never fabricates person or mutates state");
  text("本局武将");option("补充武将资料");await(v->v instanceof Button&&"补充武将资料".contentEquals(((Button)v).getText()));find("10365");option(ContentCatalog.get().officer(10365).name+" · ID 10365");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("目标：Windows 繁中 PK 1.1"));check(Arrays.equals(actual,capture()),"separate supplementary catalog read has no hidden editing/backfill");text("返回");text("补充武将资料");option("本局武将");inspect(dto[0].officer(10365),actual,"back-to-current");
  save(actual);load();check(Arrays.equals(actual,capture()),"content browsing followed by ordinary save/load preserves entire original World/RNG");Files.write(new File(evidence,"final.sg11").toPath(),capture());
  result.putString("stream","PASS SESSION B OFFICER CONTENT"+(coldMode?" COLD":"")+" actual ordinary current roster/search/detail/source/glyph IDs/unchanged full World dual RNG; effective coverage/16 menu/ARM separate\n");
 }catch(Throwable t){result.putString("stream","FAIL SESSION B OFFICER CONTENT "+android.util.Log.getStackTraceString(t));try{Files.write(new File(evidence,"failed.sg11").toPath(),capture());shot("failed");}catch(Throwable ignored){}}
 finally{try{if(activity!=null)runOnMainSync(activity::finish);settle();}catch(Throwable t){result.putString("stream",result.getString("stream")+"\nFAIL lifecycle "+t);}}
 try{if(evidence!=null)Files.write(new File(evidence,"result.txt").toPath(),result.getString("stream").getBytes("UTF-8"));}catch(Exception ignored){}finish(Activity.RESULT_OK,result);}
}
