package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.os.*;import android.view.*;import android.widget.*;import game.sanguo.core.*;import java.io.*;import java.nio.file.Files;import java.util.*;
/** Real new-game, administrative page, civil transfer, capture and cold save widgets. */
public final class SessionAArmyBudgetInstrumentation extends SessionAScenePresentationInstrumentation {
 private void editorBudgetPreview(int side)throws Exception{
  byte[] before=capture();var token=activity.deploymentState();String name=SessionProbe.view(activity).faction(side);nav("菜单");pageAction("PK编辑 / 新武将");option("编辑势力");option(name);option("行动力与技巧点");EditText budget=(EditText)await(v->v instanceof EditText&&"第一军团行动力（0—255）".equals(v.getContentDescription()));check(Integer.parseInt(budget.getText().toString())==SessionProbe.view(activity).actionPoints[side],"actual conditional editor displays only authoritative first-army projection");invoke("enter",new Class<?>[]{EditText.class,String.class},budget,"255");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();text("预览修改");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("确认PK编辑"));shot("a-first-army255-preview");text("取消");check(Arrays.equals(before,capture())&&token.equals(activity.deploymentState()),"actual255 editor preview-cancel preserves complete Save/bothRNG/StateToken");
 }
 private World.Officer person(World w,int nativeId)throws Exception {for(var p:PcScenarioPeople.saved(w))if(p.nativeId==nativeId)return w.officer(p.officerId);throw new AssertionError("Missing native identity "+nativeId);}
 private void newSource(int faction)throws Exception {
  var source=PcScenarioCatalog.all().get(0);String name=PcScenarioCatalog.preview(source.identity.scenarioId).faction(faction);
  nav("菜单");text("新游戏 / 选择势力");revealDescription("选择PC来源剧本 "+source.identity.path);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("确认开局势力"));revealDescription("选择势力 · "+name);description("确认开局势力");text("开始新局");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));check(SessionProbe.view(activity).player==faction,"ordinary selected faction "+faction);
 }
 @Override protected void nav(String name)throws Exception {
  for(int attempt=0;attempt<3;attempt++){
   AlertDialog dialog=(AlertDialog)field(activity,"navigationDialog");
   if(dialog==null||!dialog.isShowing()){
    View trigger=await(v->v.isEnabled()&&v.isClickable()&&v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
    android.graphics.Rect bounds=new android.graphics.Rect();int[] rootAt=new int[2];runOnMainSync(()->{trigger.getGlobalVisibleRect(bounds);trigger.getRootView().getLocationOnScreen(rootAt);});note("nav="+name+" attempt="+attempt+" bounds="+bounds+" root="+Arrays.toString(rootAt));tap(trigger);settle();
   }
   dialog=(AlertDialog)field(activity,"navigationDialog");note("nav="+name+" attempt="+attempt+" showing="+(dialog!=null&&dialog.isShowing()));
   if(dialog!=null&&dialog.isShowing()){revealDescription("导航 · "+name);settle();return;}
   shot("navigation-"+name+"-"+attempt);
  }
  throw new AssertionError("Normal enabled navigation trigger did not open "+name);
 }
 private void focusCity(World.City c)throws Exception {nav("地图");runOnMainSync(()->activity.selectAndFocus(c.hex));settle();ClientState ui=(ClientState)field(activity,"ui");if(!ui.panelVisible)description("选中对象指令 ·");text("展开");}
 private void pageAction(String s)throws Exception {runOnMainSync(()->{View hit=search(activity.getWindow().getDecorView(),v->v instanceof Button&&((Button)v).getText().toString().startsWith(s));if(hit!=null)hit.requestRectangleOnScreen(new android.graphics.Rect(0,0,hit.getWidth(),hit.getHeight()),true);});settle();text(s);}
 private void administration(World.City c,String governor)throws Exception {focusCity(c);pageAction("军政 / 俘虏 / 官职");option("原军团与太守");await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("当前太守："+governor));if(PcArmyActionPolicy.enabled(SessionProbe.view(activity)))await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("本据点军团行动力："+PcArmyActionPolicy.cityPoints(SessionProbe.view(activity),c.id)));shot("administration-"+c.id+"-"+SessionProbe.view(activity).turn);text("返回");}
 private void saveActual(String name)throws Exception {byte[] saved=capture();Files.write(new File(evidence,name).toPath(),saved);boolean existed=new File(activity.getFilesDir(),"manual3.sg11").exists();nav("菜单");text("保存局面");preparedOption("槽位 3");if(existed)text("覆盖存档");check(Arrays.equals(saved,Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath())),"ordinary fullWorld/bothRNG saved "+name);}
 private void loadActual(String name)throws Exception {byte[] expected=Files.readAllBytes(new File(evidence,name).toPath());nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));check(Arrays.equals(expected,capture()),"ordinary manual load fullWorld/bothRNG "+name);}
 private void quantity(String name,String value)throws Exception {revealDescription(name);EditText e=(EditText)await(v->v instanceof EditText&&name.equals(v.getContentDescription()));invoke("enter",new Class<?>[]{EditText.class,String.class},e,value);sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();}
 @Override public void onStart(){Bundle result=new Bundle();try {
  evidence=new File(getTargetContext().getExternalFilesDir("session-b"),coldMode?"governor-cold":"governor");evidence.mkdirs();put("output",evidence);activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));put("activity",activity);awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
  if(coldMode){byte[] expected=Files.readAllBytes(new File(getTargetContext().getExternalFilesDir("session-b"),"governor/actual-source.sg11").toPath());check(Arrays.equals(expected,capture()),"true cold auto resume complete administration/capture/bothRNG");nav("菜单");text("读取存档");preparedOption("槽位 3");text("读取存档");awaitPreparation(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));check(Arrays.equals(expected,capture()),"true cold manual load complete administration/capture/bothRNG");verifySceneFacts("cold");shot("cold");result.putString("stream","PASS SESSION A ARMY COLD completeWorld/bothRNG; ARM pending\n");}
  else {
   newSource(28);editorBudgetPreview(28);World w=SessionProbe.view(activity);check(PcArmyActionPolicy.enabled(w)&&PcArmyActionPolicy.points(w,5)==94&&PcArmyActionPolicy.points(w,6)==58,"normal new original army5/6 separate exact initial AP");World.Officer moving=person(w,440);World.City origin=w.city(moving.cityId);int originId=origin.id;World.City destination=null;for(var site:PcGovernorPolicy.view(w).siteNativeIds.entrySet())if(site.getValue()==3)destination=w.city(site.getKey());check(destination!=null,"strict original source native-site3/runtime join");
   check(destination!=null&&moving.role==Strategy.Role.DISTRICT&&origin.governorId==moving.id,"normal source district/governor identity");int targetId=destination.id;String movingName=moving.name;byte[] fresh=capture();administration(origin,movingName);check(Arrays.equals(fresh,capture()),"normal administration page pure completeWorld/bothRNG");verifySceneFacts("new");
   focusCity(origin);pageAction("调动");pageAction("人员调动");option(destination.name+" ·");EditText search=(EditText)await(v->v instanceof EditText&&"表格搜索".equals(v.getContentDescription()));invoke("enter",new Class<?>[]{EditText.class,String.class},search,movingName);sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();tap(await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith(movingName)));shot("transfer-preview");text("取消");check(Arrays.equals(fresh,capture()),"ordinary transfer preview/cancel pure");
   focusCity(origin);pageAction("调动");pageAction("人员调动");option(destination.name+" ·");search=(EditText)await(v->v instanceof EditText&&"表格搜索".equals(v.getContentDescription()));invoke("enter",new Class<?>[]{EditText.class,String.class},search,movingName);sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);settle();tap(await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith(movingName)));int armyBefore=PcArmyActionPolicy.cityArmy(SessionProbe.view(activity),originId);int apBefore=PcArmyActionPolicy.points(SessionProbe.view(activity),armyBefore);int otherBefore=PcArmyActionPolicy.points(SessionProbe.view(activity),5);long revision=activity.deploymentState().revision;text("出发");w=SessionProbe.view(activity);check(w.domestic.busy(moving.id)&&w.city(originId).governorId==person(w,509).id&&activity.deploymentState().revision==revision+1,"real civil departure/election/single commit");check(PcArmyActionPolicy.points(w,armyBefore)==apBefore-10&&PcArmyActionPolicy.points(w,5)==otherBefore,"ordinary transfer debits source army6 only once, preservesarmy5");saveActual("transfer-in-flight.sg11");
   for(int i=0;i<30&&SessionProbe.view(activity).domestic.busy(moving.id);i++)advance("transfer-"+i);w=SessionProbe.view(activity);moving=person(w,440);check(moving.cityId==targetId&&moving.role==Strategy.Role.GOVERNOR&&w.city(targetId).governorId==moving.id,"ordinary completed arrival elected native440 governor");var admin=PcGovernorPolicy.view(w);check(admin.officerArmies.get(moving.id)==5&&admin.officerAdministrativeHomeNative.get(moving.id)==3&&admin.armies.get(6).leaderNativeId==436&&person(w,436).role==Strategy.Role.DISTRICT,"normal original old army6 replacement436 and new army5");administration(w.city(targetId),moving.name);shot("transfer-complete");saveActual("transfer-complete.sg11");advance("after-transfer-save");loadActual("transfer-complete.sg11");
   newSource(29);w=SessionProbe.view(activity);World.Officer ruler=person(w,91);String rulerName=ruler.name;World.City start=w.city(ruler.cityId),port=w.city(20057);focusCity(start);pageAction("出征");ListView roster=(ListView)tag("deploy.officers");invoke("showRosterTag",new Class<?>[]{ListView.class,String.class},roster,"deploy.role."+ruler.id);tap(tag("deploy.role."+ruler.id));await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().equals("从编队移除 "+rulerName));tap(tag("deploy.tab.1"));description("剑兵 无需库存");quantity("兵力数量","5000");quantity("粮食数量","20000");tap(tag("deploy.confirm"));w=SessionProbe.view(activity);int unitId=person(w,91).unitId;check(unitId>=0&&PcGovernorPolicy.view(w).unitArmies.get(unitId)==7,"actual normal deployment native army7");check(PcArmyActionPolicy.enabled(w)&&PcArmyActionPolicy.points(w,7)==55,"ordinary source29 army7 opening65 deploy10 debit");var attackRoute=w.marches.previewCity(unitId,port.id);check(attackRoute.valid()&&!attackRoute.path.isEmpty(),"authority capture approach route admitted");Hex approach=attackRoute.path.get(attackRoute.path.size()-1);check(!approach.equals(port.hex),"attack endpoint is legal range outside site footprint");selectUnit(unitId);pose(approach);text("行军");tile(approach);text("确认任务");
   for(int i=0;i<10&&!SessionProbe.view(activity).unit(unitId).hex.equals(approach);i++)advance("approach-"+i);w=SessionProbe.view(activity);check(w.unit(unitId).hex.equals(approach),"normal explicit MOVE reaches exact attack-range tile without auto-capture");check(w.city(port.id).owner==-1,"MOVE retains neutral port ownership");if(w.siegeError(unitId,port.id)!=null){advance("attack-action-reset");w=SessionProbe.view(activity);}check(w.siegeError(unitId,port.id)==null,"actual current ordinary attack admission");selectUnit(unitId);pose(port.hex);text("攻击");tile(port.hex);text("执行");
w=SessionProbe.view(activity);ruler=person(w,91);port=w.city(port.id);check(port.owner==29&&ruler.cityId==port.id&&port.governorId==ruler.id&&PcGovernorPolicy.view(w).siteArmies.get(port.id)==7&&!PcGovernorPolicy.view(w).unitArmies.containsKey(unitId),"ordinary neutral-port capture/garrison/native army saved and removed unit metadata");administration(port,ruler.name);verifySceneFacts("capture");shot("capture-complete");saveActual("actual-source.sg11");advance("after-capture-save");loadActual("actual-source.sg11");result.putString("stream","PASS SESSION A ARMY normal two factions/new/menu/administration/transfer cancel/arrival/army replacement/real capture/save-load/fullWorld/bothRNG; cold and ARM separate\n");
  }
 }catch(Throwable t){result.putString("stream","FAIL SESSION A ARMY "+android.util.Log.getStackTraceString(t));try{shot("failed");}catch(Throwable ignored){}}finally{try{if(activity!=null)runOnMainSync(activity::finish);settle();}catch(Throwable t){result.putString("stream",result.getString("stream")+"\nFAIL lifecycle "+t);}}
 try{Files.write(new File(evidence,"result.txt").toPath(),result.getString("stream").getBytes("UTF-8"));}catch(Exception ignored){}finish(Activity.RESULT_OK,result);
 }
}
