package game.sanguo.core;
import java.nio.file.*;import java.util.*;import java.util.regex.*;import game.sanguo.api.*;import game.sanguo.runtime.GameSession;
/** Actual cold process recorded inputs and archived final autosave, with no artifact mutation. */
public final class ActualColdSearchDebateReplay {
 public static void main(String[]args)throws Exception{
  Path root=Path.of(args[0]),actual=Path.of(args[1]),output=Path.of(args[2]);byte[] mid=Files.readAllBytes(root.resolve("search/actual-mid.sg11")),done=Files.readAllBytes(actual);Pattern p=Pattern.compile("human contest=([0-9]+) revision=([0-9]+) phase=([0-9]+) round=([0-9]+) card=([0-9]+)");List<ActualSearchDebateReplay.Input> recorded=new ArrayList<>();for(String line:Files.readAllLines(root.resolve("search-cold/diagnosis.txt"))){Matcher m=p.matcher(line);if(m.find())recorded.add(new ActualSearchDebateReplay.Input(Integer.parseInt(m.group(2)),Integer.parseInt(m.group(5))));}int index=0,commands=0;
  try(GameSession g=new GameSession(SaveCodec.decode(mid))){while(g.contest().kind!=ContestSnapshot.Kind.NONE&&commands++<500){var f=g.contest();ContestCommand cmd;if(f.waitingMercy)cmd=ContestCommand.finishDebate(f.state,f.contestId,f.revision,true);else if(f.phase==9)cmd=ContestCommand.finishDebate(f.state,f.contestId,f.revision,false);else{ActualSearchDebateReplay.check(index<recorded.size(),"actual cold card exists");var input=recorded.get(index++);ActualSearchDebateReplay.check(input.revision==f.revision,"actual cold revision");var card=f.cards.stream().filter(c->c.enabled()&&c.nativeCard==input.card).findFirst().orElseThrow();cmd=ContestCommand.card(f.state,f.contestId,f.revision,card.slot);}ActualSearchDebateReplay.check(g.execute(cmd).ok(),"actual cold command accepted");byte[] committed=g.captureSave();ActualSearchDebateReplay.check(Arrays.equals(committed,SaveCodec.encode(SaveCodec.decode(committed))),"cold full model/World/allRNG roundtrip");ActualSearchDebateReplay.check(!g.execute(cmd).ok()&&Arrays.equals(committed,g.captureSave()),"cold stale/double pure");}ActualSearchDebateReplay.check(g.contest().kind==ContestSnapshot.Kind.NONE&&index==recorded.size(),"cold terminal once consumes all actual card inputs");ActualSearchDebateReplay.turn(g);Files.write(output,g.captureSave());ActualSearchDebateReplay.check(Arrays.equals(ActualSearchDebateReplay.canonical(done),ActualSearchDebateReplay.canonical(g.captureSave())),"actual cold final autosave equals recorded legal human/terminal/wholeturn fullWorld/allRNG replay");System.out.println("PASS actual cold SEARCH saved model->recorded human->once campaign terminal->wholeturn fullWorld/allRNG exact canonical; commands="+commands+" raw="+Arrays.equals(done,g.captureSave()));}
  ActualSearchDebateReplay.check(Arrays.equals(mid,Files.readAllBytes(root.resolve("search/actual-mid.sg11")))&&Arrays.equals(done,Files.readAllBytes(actual)),"actual cold artifacts immutable");
 }
}
