from pathlib import Path
root=Path.cwd();p=root/'app/src/androidTest/java/game/sanguo/mobile/SessionBNativeDuelInstrumentation.java';s=p.read_text()
s=s.replace('private String mode="normal",','private boolean jiRoute,recruited; private int routeUnit;\n    private String mode="normal",',1)
s=s.replace('if(args!=null){mode=', 'if(args!=null){jiRoute="ji-recruit".equals(args.getString("native_route","legacy"));mode=',1)
s=s.replace('finishBattle();\n                for(int i=0;i<3;i++)advance', 'finishBattle();\n                if(jiRoute){for(int n=0;!recruited&&n<8;n++){advance("ji-next-encounter-"+n);encounter(routeUnit);finishBattle();}check(recruited,"actual ordinary recruitment succeeds without rewriting seed/result");}\n                for(int i=0;i<3;i++)advance',1)
s=s.replace('load();check(Arrays.equals(expected,capture()),"manual load actual human battle exact");','load();check(Arrays.equals(expected,capture()),"manual load actual human battle exact");\n                if(jiRoute){World w=SessionProbe.view(activity);routeUnit=w.officer(PcDuelSourceFacts.saved(w).values().stream().filter(v->v.nativeId==98).findFirst().orElseThrow().officerId).unitId;}',1)
s=s.replace('opening(7,28,true);opening(0,28,false);unit=deploy(503);','opening(7,28,true);opening(0,jiRoute?4:28,false);unit=jiRoute?deployCrew():deploy(503);routeUnit=unit;',1)
pos=s.index('    private int deploy(int nativeId)throws')
s=s[:pos]+'''    private int deployCrew()throws Exception{
        World w=SessionProbe.view(activity);var people=PcDuelSourceFacts.saved(w);int[] crew=new int[3];int[] natives={98,432,635};for(int i=0;i<3;i++){final int nativeId=natives[i];crew[i]=people.values().stream().filter(p->p.nativeId==nativeId).findFirst().orElseThrow().officerId;}
        var city=w.city(w.officer(crew[0]).cityId);check(city!=null&&city.equipment[World.Weapon.HALBERD.ordinal()]>=6000,"source-joined three-person legal halberd stock");nav("地图");revealDescription("定位己方据点 "+city.name);byte[] before=capture();text("出征");
        ListView roster=(ListView)tag("deploy.officers");for(int id:crew){invoke("showRosterTag",new Class<?>[]{ListView.class,String.class},roster,"deploy.role."+id);tap(tag("deploy.role."+id));}
        tap(tag("deploy.tab.1"));description("戟兵 库存");quantity("兵力数量","6000");quantity("粮食数量","35000");quantity("金钱数量","1500");check(Arrays.equals(before,capture()),"three-person formation preview pure");long revision=activity.deploymentState().revision;tap(tag("deploy.confirm"),2);
        w=SessionProbe.view(activity);var u=w.unit(w.officer(crew[0]).unitId);check(u!=null&&u.troops==6000&&u.food==35000&&u.gold==1500&&u.weapon==World.Weapon.HALBERD&&Arrays.equals(u.deputies,new int[]{crew[1],crew[2]}),"ordinary exact three-person crew/resources");check(activity.deploymentState().revision==revision+1,"three-person double deployment once");note("ji route unit="+u.id+" crew="+Arrays.toString(crew)+" position="+u.hex);shot("ordinary-three-person-deployed");return u.id;
    }
''' +s[pos:]
s=s.replace('if(u.hex.distance(target.hex)>1){','''if(jiRoute&&u.hex.distance(target.hex)<=7&&w.war.structures.stream().noneMatch(v->v.owner==world.player&&v.kind==War.StructureKind.DRUM)&&!PcDuelResponseRules.currentDrumSupport(w,u.officerId,target.hex)){
                    var legal=w.fieldworks.sites(unit,War.StructureKind.DRUM).stream().filter(h->h.distance(targetCell)>0&&h.distance(targetCell)<=7).findFirst();if(legal.isPresent()){Hex site=legal.get();int gold=u.gold;int cost=w.fieldworks.buildCost(unit,War.StructureKind.DRUM,site);byte[] before=capture();selectUnit(unit);pose(site);militaryMenu();option("太鼓台 · 金");tile(site);text("取消");check(Arrays.equals(before,capture()),"actual drum map confirmation cancel pure");text("取消选取");selectUnit(unit);pose(site);militaryMenu();option("太鼓台 · 金");tile(site);long revision=activity.deploymentState().revision;tap(await(v->v instanceof Button&&"执行".contentEquals(((Button)v).getText())),2);World built=SessionProbe.view(activity);check(built.war.at(site)!=null&&built.war.at(site).builder==unit&&built.unit(unit).gold==gold-cost&&built.unit(unit).acted&&activity.deploymentState().revision==revision+1,"ordinary drum build double once actual cargo/action");shot("ordinary-drum-construction");advance("ji-drum-build");continue;}
                }
                if(u.hex.distance(target.hex)>1){''',1)
s=s.replace('filter(h->!h.equals(current.hex))','filter(h->!h.equals(current.hex)&&(!jiRoute||world.cityAt(h)==null))',1)
s=s.replace('check(selected.revision==f.revision+1,"normal recruitment consumes original attempt once");','check(selected.revision==f.revision+1,"normal recruitment consumes original attempt once");recruited|=selected.nativeDuel.disposition.stream().anyMatch(r->r.officerId==pending.officerId&&r.choice==0);',1)
p.write_text(s)
p=root/'tools/content/session_b_verify_fieldworks_ui.py';s=p.read_text();s=s.replace("nativeStrategy=a.native_strategy,","nativeRoute=a.native_route,nativeStrategy=a.native_strategy,",1);s=s.replace("['-e','native_strategy',a.native_strategy,","['-e','native_route',a.native_route,'-e','native_strategy',a.native_strategy,");s=s.replace(" p.add_argument('--initial-save',type=Path,default=None)"," p.add_argument('--initial-save',type=Path,default=None)\n p.add_argument('--native-route',choices=['legacy','ji-recruit'],default='legacy')");p.write_text(s)
p=root/'tools/content/session_b_freeze_opening_combined.py';s=p.read_text().replace("init='docs/", "init='docs/handoff/20261006/session-b/native-opening-acceptance61-r20.init.gradle'if revision==20 else 'docs/",1).replace('17,18,19]','17,18,19,20]');p.write_text(s)
p=root/'docs/handoff/20261006/session-b/native-opening-acceptance61-r20.init.gradle';p.write_text((root/'docs/handoff/20261006/session-b/native-opening-acceptance61-r19.init.gradle').read_text().replace('B0c9f6a5b-candidate61-r19','B1ffabafe-candidate61-r20'))
