#!/usr/bin/env python3
"""Readonly actual369 source mesh flag branches; preserve original-only paths and gaps."""
from pathlib import Path
import json,re
from read_session_state import read_session_state as read
from run_remaining_normal_media import sha
ROOT=Path(__file__).resolve().parents[4];D=Path(__file__).resolve().parent

def main():
 out=D/'ALIAS_GATES394.json';assert not out.exists();b=read(D/'MUSIC_RESERVE_BUILD369.json');manifest=Path(b['candidateInputManifest']);assert sha(manifest)==b['candidateInputManifestSha256'];expected={x['path']:x['sha256'] for x in read(manifest)};base=manifest.parent/'source';patterns=re.compile(r'\b(?:pcGround|pcWater|pcScenery|pcSite|pcUnit|pcFacility|pcDam|pcWall|pcFacilityRig|nativeBody)\b');records=[]
 for p in sorted((base/'app/src/main/java').rglob('*.java')):
  text=p.read_text();lines=text.splitlines();hits=[]
  for i,line in enumerate(lines):
   if patterns.search(line) and not line.strip().startswith(('//','*','/*')) and re.search(r'\bif\b|\?|&&|\|\|',line):hits.append({'line':i+1,'code':line,'context':'\n'.join(lines[max(0,i-3):min(len(lines),i+5)])})
  if hits:path=str(p.relative_to(base));assert sha(p)==expected[path];records.append({'path':path,'sha256':sha(p),'namedFlagPredicates':hits})
 checks=[('FilamentMapView.java','boolean pc=source.pcGround||source.pcWater||source.pcScenery||source.pcSite||source.pcFacility||source.pcUnit||source.pcFacilityRig;','Bounds choose actual source geometry with conservative animation/terrain margin. Exact shader/culling/wholePC/ARM performance not proven.'),('FilamentMapView.java','if(source.pcUnit||source.pcFacilityRig){','Opaque/transparent source primitive ranges and per-member instancing separate from legacy geometry; original index byte parity325 does not prove all actual animated poses.'),('FilamentMapView.java','if(snapshot.ground.pcMap==null&&(item.site!=null','Generic mobile flag omitted on source map. Selection is independent selected()/siteSelectionPath/labelHit overlays; original PC flag/recovery of all original attachments is still unknown.'),('FilamentMapView.java','void updateSeason(){if(instance!=null&&!nativeBody())','Generic pigment skipped on native body, source painting uses bindPcPainting(month). Facility climate fixed0 remains documented gap; no inferred climate from source ordinal.'),('FilamentMapView.java','void updateDamage(){if(instance!=null&&!nativeBody())','Generic shader damage skipped on native body; source body variants/factual HP/work/burning labels separate. Native every damage/construction transition still unaccepted.'),('FilamentMapView.java','if(shape.source.pcUnit&&instance!=null){','Source formation samples copied visual unit/terrain and updates only GPU transforms. No rule damage/success/RNG recomputation; all route/terrain/foot-contact exactPC not accepted.'),('FilamentMapView.java','if(dragMesh.pcUnit){','Selection drag ghost uses already loaded source CPU mesh and source formation; optional UI silhouette is app guidance, not relabeled original effect. Normal MOVE/cancel/allsource fullSave purity is required.'),('TerrainMaterialField.java','if(mesh.pcGround){','Source surface streams retain canonical UV while legacy field attributes are different. Source water child/material path independent; source topology/reuse checks scoped only tested geometry.')]
 review=[]
 for file,token,assessment in checks:
  p=base/'app/src/main/java/game/sanguo/mobile'/file;s=p.read_text();at=s.index(token);line=s[:at].count('\n')+1;lines=s.splitlines();review.append({'path':str(p.relative_to(base)),'sha256':sha(p),'line':line,'exactToken':token,'context':'\n'.join(lines[max(0,line-4):line+11]),'assessment':assessment,'actualFullAcceptance':False})
 report={'actual369Apks':b['apks'],'namedFlagFiles':len(records),'namedFlagPredicateCount':sum(len(x['namedFlagPredicates']) for x in records),'records':records,'eightSpecificAliasReviews':review,'completeNamedFlagPredicateInventory':True,'completeDynamicAndShaderAliasCoverage':False,'scope':'Exact original mesh flags/named nativeBody predicates lexical inventory in actual369 plus8 source routing/selection/material/transform reviews. Together389 covers named PC branches, not arbitrary boolean alias dataflow/shaders/native/C#/all normal events or exactPC pixels. Does not alter game/assets/rules/RNG/Source380 failure/music defaults/B WIP. Fresh392 actual full16/cold ongoing, source fire/commands/media/ARM/finalB still pending.','wholeGoalComplete':False};out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'files':len(records),'predicates':report['namedFlagPredicateCount'],'reviewed':len(review)}))
if __name__=='__main__':main()
