#!/usr/bin/env python3
"""Read original FCE and packaged PNGs; compare every decoded original pixel."""
from pathlib import Path
import json,hashlib,struct,sys,io,collections
from PIL import Image
ROOT=Path(__file__).resolve().parents[4];DOC=ROOT/'docs/handoff/20261006/session-a';sys.path.insert(0,str(ROOT/'tools/content'))
from pc_resources import wftx_levels
SOURCE=Path('/Users/paopao/Downloads/San11pk整合版/San11pk 超级整合版/Media/face/San11Face00.fce')
def digest(raw):return hashlib.sha256(raw).hexdigest()
def main():
 output=DOC/'ORIGINAL_PORTRAIT_PIXELS275.json';assert not output.exists();path=ROOT/'app/src/main/assets/portraits/pc/media-manifest.json';manifestRaw=path.read_bytes();manifest=json.loads(manifestRaw);raw=SOURCE.read_bytes();assert digest(raw)==manifest['sourceFaceSha256'];magic,version,start,count,images=struct.unpack_from('<5I',raw);assert magic==0x45434146 and version==64 and images==count*3;table=20+count*4;entries=list(struct.iter_unpack('<II',raw[table:table+images*8]));assert len(entries)==images;rows=[];groups=collections.Counter();opaque=collections.Counter();opaqueCorners=collections.Counter()
 for row in manifest['images']:
  group=row['imageGroup'];face=row['faceId'];index=face-start if group==0 else count+2*(face-start)+group-1;assert 0<=index<len(entries);offset,size=entries[index];assert size>0 and offset+size<=len(raw);source=raw[offset:offset+size];assert digest(source)==row['sourceWftxSha256'];frames=wftx_levels(source);assert len(frames)==1;original=frames[0]['levels'][0].convert('RGBA');png=ROOT/'app/src/main/assets'/row['asset'];pngRaw=png.read_bytes();assert digest(pngRaw)==row['pngSha256'];decoded=Image.open(io.BytesIO(pngRaw)).convert('RGBA');rgba=decoded.tobytes();assert original.size==decoded.size==(row['width'],row['height']) and rgba==original.tobytes() and digest(rgba)==row['rgbaSha256'];alpha=rgba[3::4];amin=min(alpha);amax=max(alpha);assert amin==row['alphaMin'] and amax==row['alphaMax'];nonOpaque=sum(a!=255 for a in alpha);assert nonOpaque==row['nonOpaquePixels'];groups[group]+=1;opaque[group]+=amin==255;corners=[decoded.getpixel((x,y)) for x,y in [(0,0),(decoded.width-1,0),(0,decoded.height-1),(decoded.width-1,decoded.height-1)]];opaqueCorners[group]+=all(p[3]==255 for p in corners);rows.append({'asset':row['asset'],'group':group,'faceId':face,'sourceResourceIndex':index,'sourceWftxSha256':digest(source),'pngSha256':digest(pngRaw),'rgbaSha256':digest(rgba),'width':decoded.width,'height':decoded.height,'alphaMin':amin,'alphaMax':amax,'cornersRgba':corners,'everyPixelExactToOriginal':True})
 assert digest(SOURCE.read_bytes())==digest(raw) and path.read_bytes()==manifestRaw
 report={'source':str(SOURCE),'sourceSha256BeforeAfter':digest(raw),'manifestSha256BeforeAfter':digest(manifestRaw),'images':len(rows),'byGroup':dict(groups),'fullyOpaqueByGroup':dict(opaque),'allFourCornersOpaqueByGroup':dict(opaqueCorners),'rows':rows,'androidCallerSmallFamilyBindingAccepted':False,'androidOutputPixelsAccepted':False,'all16IdentitiesAllAgeAccepted':False,'sourceReadOnly':True,'scope':'Fresh complete packaged2892 PNG source-pixel verification: actual supplied original FCE entries and original WFTX decode equal every PNG RGBA byte, dimensions/hash/alpha. Original source and manifest hashes unchanged. Group0 corners witness274 removal of unproved mobile corner mask; does not prove PC UI clipping/frame/gamma or actual Android crop/scale/caller timing/identity/all age/fullscreen/ARM. No generated art or image edits.','wholeGoalComplete':False};output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='rows'}))
if __name__=='__main__':main()
