#!/usr/bin/env python3
"""Test-only bounded recorder/cache I/O; unchanged game/PCM/strict whole threshold."""
from pathlib import Path
import json
from run_remaining_normal_media import sha
ROOT=Path(__file__).resolve().parents[4];DOC=Path(__file__).resolve().parent;OUT=ROOT/'out/session-a/capture-buffer355';PATH='app/src/androidTest/java/game/sanguo/mobile/SessionAAudioCaptureService.java'
def main():
 assert not OUT.exists();OUT.mkdir(parents=True);base=ROOT/'out/session-a/repeat-test-build330/source'/PATH;s=base.read_text()
 s=s.replace('import java.io.RandomAccessFile;','import java.io.RandomAccessFile;\nimport java.io.BufferedOutputStream;')
 old='AudioRecord audio=null;long bytes=0,began=SystemClock.elapsedRealtimeNanos(),lastStamp=0;String failure="";';new='AudioRecord audio=null;long bytes=0,began=SystemClock.elapsedRealtimeNanos(),lastStamp=0,maxReadNanos=0,maxWriteNanos=0;int actualBufferFrames=0;String failure="";';assert s.count(old)==1;s=s.replace(old,new)
 old='.setAudioPlaybackCaptureConfig(capture).setBufferSizeInBytes(Math.max(minimum,65536)).build();';new='.setAudioPlaybackCaptureConfig(capture).setBufferSizeInBytes(Math.max(minimum,sampleRate*4*2)).build();';assert s.count(old)==1;s=s.replace(old,new)
 old='recorder=audio;audio.startRecording();';new='actualBufferFrames=audio.getBufferSizeInFrames();recorder=audio;audio.startRecording();';assert s.count(old)==1;s=s.replace(old,new)
 old='byte[] buffer=new byte[8192];\n            try(RandomAccessFile out=new RandomAccessFile(wave,"rw")) {\n                out.write(header(0,sampleRate));';new='byte[] buffer=new byte[8192];\n            try(FileOutputStream file=new FileOutputStream(wave);BufferedOutputStream out=new BufferedOutputStream(file,524288)) {\n                out.write(header(0,sampleRate));';assert s.count(old)==1;s=s.replace(old,new)
 old='int n=audio.read(buffer,0,buffer.length,AudioRecord.READ_BLOCKING);';new='long readStart=SystemClock.elapsedRealtimeNanos();int n=audio.read(buffer,0,buffer.length,AudioRecord.READ_BLOCKING);maxReadNanos=Math.max(maxReadNanos,SystemClock.elapsedRealtimeNanos()-readStart);';assert s.count(old)==1;s=s.replace(old,new)
 old='out.write(buffer,0,n);bytes+=n;';new='long writeStart=SystemClock.elapsedRealtimeNanos();out.write(buffer,0,n);maxWriteNanos=Math.max(maxWriteNanos,SystemClock.elapsedRealtimeNanos()-writeStart);bytes+=n;';assert s.count(old)==1;s=s.replace(old,new)
 old='out.seek(0);out.write(header(bytes,sampleRate));out.getFD().sync();\n            }';new='out.flush();file.getFD().sync();\n            }\n            try(RandomAccessFile metadata=new RandomAccessFile(wave,"rw")){metadata.seek(0);metadata.write(header(bytes,sampleRate));metadata.getFD().sync();}';assert s.count(old)==1;s=s.replace(old,new)
 old='.put("elapsedNanos",SystemClock.elapsedRealtimeNanos()-began).put("timestamps",timestamps)';new='.put("elapsedNanos",SystemClock.elapsedRealtimeNanos()-began).put("timestamps",timestamps).put("actualRecorderBufferFrames",actualBufferFrames).put("diskBufferBytes",524288).put("maximumReadNanos",maxReadNanos).put("maximumWriteNanos",maxWriteNanos).put("samplesDroppedOrSynthesized",false)';assert s.count(old)==1;s=s.replace(old,new)
 target=OUT/PATH;target.parent.mkdir(parents=True);target.write_text(s);report={'paths':[{'path':PATH,'beforeSha256':sha(base),'afterSha256':sha(target),'stagedPath':str(target)}],'game326Unchanged':True,'recorderRequestedSeconds':2,'recorderRequestedMaxBytesAt48k':384000,'diskBufferBytes':524288,'noSampleEditingDroppingOrResampling':True,'scope':'Measurement-only finite capture ring and buffered sequential file I/O, actual buffer/read/write stats. No gameplay/player/code/resources/source/rule changes, no new whole acceptance; strict0.995 and full raw timeline retained. Must build/install/restore new test and verify recording header/bytes.','wholeGoalComplete':False};(DOC/'CAPTURE_BUFFER355.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
if __name__=='__main__':main()
