package game.sanguo.core;
import java.util.*;import java.nio.file.*;
public final class PcArmyActionPolicyTest {
 static int checks;static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}
 public static void main(String[] args)throws Exception{
  Map<String,String> sourceShas=new HashMap<>();Map<String,Map<Integer,Integer>> nativePoints=new HashMap<>();for(String line:Files.readAllLines(Path.of("core/src/test/resources/pc-army-action/original-all16.tsv"))){if(line.startsWith("#")||line.isBlank())continue;String[] v=line.split("\t");check(v.length==4,"original fixture has four fields");sourceShas.put(v[0],v[1]);nativePoints.computeIfAbsent(v[0],k->new HashMap<>()).put(Integer.parseInt(v[2]),Integer.parseInt(v[3]));}
  int matches=0;for(var source:PcScenarioCatalog.all()){
   check(source.identity.sha.equals(sourceShas.get(source.identity.scenarioId)),"exact original source SHA");World w=PcScenarioCatalog.load(source.identity.scenarioId,-1,42);long strategy=w.strategy.randomState,life=w.life.randomState;check(PcArmyActionPolicy.enabled(w),"normal source factory initializes saved original budget");
   for(var row:nativePoints.get(source.identity.scenarioId).entrySet()){check(PcArmyActionPolicy.points(w,row.getKey())==row.getValue(),"source-specific original AP driver "+source.identity.scenarioId+"/"+row.getKey());matches++;}
   check(strategy==w.strategy.randomState&&life==w.life.randomState,"native initial AP no random draws");byte[] before=SaveCodec.encode(w);check(Arrays.equals(before,SaveCodec.encode(SaveCodec.decode(before))),"wholeWorld/armyAP/all RNG save exact");
   var view=PcGovernorPolicy.view(w);for(var army:view.armies)if(!army.originalValid)check(PcArmyActionPolicy.points(w,army.nativeId)==0,"inactive original army gets no invented owner0 budget");
  }check(matches==285,"complete valid normal-owner army fixture count");
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,28,42);check(PcArmyActionPolicy.enabled(w),"normal source factory initializes saved original budget");World.City first=null,second=null;for(var c:w.cities){int army=PcArmyActionPolicy.cityArmy(w,c.id);if(army==5)first=c;if(army==6)second=c;}check(first!=null&&second!=null,"two original armies under same current faction");int other=PcArmyActionPolicy.points(w,6);PcArmyActionPolicy.debit(w,first,20);check(PcArmyActionPolicy.points(w,5)==74&&PcArmyActionPolicy.points(w,6)==other,"city5 debits own army5, never borrows from army6");check(PcArmyActionPolicy.failure(w,second,20,true).code.equals("ORIGINAL_ARMY_DELEGATED"),"normal direct recruitment requires first original army");
  byte[] debited=SaveCodec.encode(w);check(Arrays.equals(debited,SaveCodec.encode(SaveCodec.decode(debited))),"both original armies exact saved debit");w.turn++;PcArmyActionPolicy.replenish(w);int replenished=PcArmyActionPolicy.points(w,5);PcArmyActionPolicy.replenish(w);check(replenished==168&&PcArmyActionPolicy.points(w,5)==replenished,"actual native cumulative replenishment once per full turn");
  World play=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,42);check(PcArmyActionPolicy.enabled(play),"normal source factory initializes saved original budget");World.City home=play.cities.stream().filter(c->c.owner==play.player&&!play.idle(c).isEmpty()).findFirst().orElseThrow();World.Officer actor=play.idle(home).get(0);int opening=PcArmyActionPolicy.cityPoints(play,home.id);byte[] untouched=SaveCodec.encode(play);
  CityActionPlan preview=play.strategy.previewCityAction(CityActionPlan.Operation.PATROL,home.id,actor.id,new int[0]);check(preview.allowed(),"ordinary source0 patrol permitted");check(preview.actionPointsAvailable==opening,"preview reads own original army");check(Arrays.equals(untouched,SaveCodec.encode(play)),"ordinary preview complete-save/RNG pure");check(play.patrol(home.id,actor.id).ok,"ordinary patrol commits");check(PcArmyActionPolicy.cityPoints(play,home.id)==opening-preview.actionPointsCost,"ordinary same army actual debit");check(Arrays.equals(SaveCodec.encode(play),SaveCodec.encode(SaveCodec.decode(SaveCodec.encode(play)))),"ordinary action saved exact");check(play.nextTurn().ok,"complete ordinary full turn");SaveCodec.validate(play);
  int projected=play.actionPoints[play.player];play.actionPoints[play.player]++;boolean projectionRejected=false;try{SaveCodec.encode(play);}catch(java.io.IOException e){projectionRejected=true;}check(projectionRejected,"corrupt global projection never silently repairs on save");play.actionPoints[play.player]=projected;
  byte[] identityGood=play.extensions.get(PcScenarioIdentity.NAMESPACE);play.dataHash="broken";boolean staleSourceRejected=false;try{PcArmyActionPolicy.points(play,0);}catch(IllegalStateException e){staleSourceRejected=true;}check(staleSourceRejected,"cached budget rejects changed live source identity");play.dataHash=PcScenarioCatalog.all().get(0).identity.sha;check(Arrays.equals(identityGood,play.extensions.get(PcScenarioIdentity.NAMESPACE)),"validation does not rewrite source bytes");
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));byte[] oldBefore=SaveCodec.encode(old);check(!PcArmyActionPolicy.enabled(old)&&Arrays.equals(oldBefore,SaveCodec.encode(SaveCodec.decode(oldBefore))),"genuine historical39 no silent army-budget adoption/backfill");int priorAP=old.actionPoints[old.player];old.actionPoints[old.player]=61;boolean legacyLimitRejected=false;try{SaveCodec.encode(old);}catch(java.io.IOException e){legacyLimitRejected=true;}check(legacyLimitRejected,"absent old policy retains AP60 validation");old.actionPoints[old.player]=priorAP;
  World unknown=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,42);unknown.extensions.put(PcArmyActionPolicy.NAMESPACE,new byte[]{1,2,3,4,5});Arrays.fill(unknown.actionPoints,60);byte[] unknownBefore=SaveCodec.encode(unknown);check(!PcArmyActionPolicy.enabled(unknown)&&Arrays.equals(unknownBefore,SaveCodec.encode(SaveCodec.decode(unknownBefore))),"unknown opaque policy bytes preserved without adoption");
  var assignments=PcGovernorPolicy.data(play);int priorArmy=assignments.siteArmies.get(home.id);assignments.siteArmies.put(home.id,-1);PcGovernorPolicy.write(play,assignments);byte[] unknownSite=SaveCodec.encode(play);RuleFailure refusal=play.actionPointFailure(home,20);check(refusal.code.equals("ORIGINAL_ARMY_UNKNOWN"),"unknown captured/source site cannot borrow first army points");check(Arrays.equals(unknownSite,SaveCodec.encode(play)),"unknown army preflight no world/RNG mutation");assignments.siteArmies.put(home.id,priorArmy);PcGovernorPolicy.write(play,assignments);
  World budgets=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,28,42);check(PcArmyActionPolicy.enabled(budgets),"normal source factory initializes saved original budget");int secondary=PcArmyActionPolicy.points(budgets,6);byte[] editorBefore=SaveCodec.encode(budgets);Editor.Draft draft=budgets.editor.faction(28,255,budgets.campaign.points(28));check(draft.valid(),"normal editor validates explicit original first army AP255");check(Arrays.equals(editorBefore,SaveCodec.encode(budgets)),"editor preview allWorld/RNG pure");check(budgets.editor.apply(draft).ok,"ordinary editor apply");check(PcArmyActionPolicy.points(budgets,5)==255&&PcArmyActionPolicy.points(budgets,6)==secondary,"editor changes first army only");check(!budgets.editor.apply(draft).ok,"editor saved stale/double state refused");PcArmyActionPolicy.debitPrimary(budgets,28,20);check(PcArmyActionPolicy.points(budgets,5)==235&&PcArmyActionPolicy.points(budgets,6)==secondary,"management only debits original first army");World.City delegated=budgets.cities.stream().filter(c->c.owner==28&&c.kind==World.SiteKind.CITY&&!budgets.districts.rulerCity(c.id)).findFirst().orElseThrow();int delegatedArmy=PcArmyActionPolicy.cityArmy(budgets,delegated.id);int expectedBefore=PcArmyActionPolicy.points(budgets,5);World.Result configured=budgets.districts.configure(-1,"预算验收",new int[]{delegated.id},Districts.Policy.DEFENSE,-1,-1,false,false);check(configured.ok,"ordinary engineering delegation compiles on explicit saved original budget");check(PcArmyActionPolicy.points(budgets,5)==expectedBefore-20,"configure uses original first army once");byte[] configuredSave=SaveCodec.encode(budgets);World replay=SaveCodec.decode(configuredSave);check(budgets.nextTurn().ok&&replay.nextTurn().ok,"delegation and AI complete wholeturn with independent budgets");check(Arrays.equals(SaveCodec.encode(budgets),SaveCodec.encode(replay)),"delegated fullturn/reload exact independent army AP/World/all RNG");check(PcArmyActionPolicy.points(budgets,delegatedArmy)>=0,"delegated site original army budget retained");PcArmyActionPolicy.clearOwner(budgets,28);check(PcArmyActionPolicy.points(budgets,5)==0&&PcArmyActionPolicy.points(budgets,6)==0&&budgets.actionPoints[28]==0,"collapse clears every owner army and projection");check(Arrays.equals(SaveCodec.encode(budgets),SaveCodec.encode(SaveCodec.decode(SaveCodec.encode(budgets)))),"edited and cleared independent budget complete-save exact");
  System.out.println("PASS original saved army budget "+checks+" checks/285source-specific armies/16sources/independent scope/cumulative turn/save/RNG/old absence; normal APK integration pending");
 }
}
