package game.sanguo.core;
import java.util.*;import java.nio.file.*;
/** Actual normal source/campaign command and legal human inputs; no injected stocks/ability/result. */
public final class PcDebateOrdinaryCampaignTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static World.Officer person(World w,int nativeId)throws Exception {for(var p:PcScenarioPeople.saved(w))if(p.nativeId==nativeId)return w.officer(p.officerId);throw new AssertionError("native source identity");}
 static int play(World w,boolean poor)throws Exception {int targetId=w.contests.current().rightRef,owner=w.player;int moves=0;while(w.contests.busy()&&moves++<400){var session=w.contests.current();var d=session.nativeDebate;if(d.waitingMercy()){check(w.contests.finishDebate(session.id,session.revision,true).ok,"native human terminal choice/result");continue;}if(d.model.phase==9){check(w.contests.finishDebate(session.id,session.revision,false).ok,"native phase9 once-only result");break;}check(d.waitingCard(),"normal actual human card boundary");int slot=-1,score=poor?Integer.MAX_VALUE:Integer.MIN_VALUE;
  for(int i=0;i<d.model.state.left.slots;i++)if(d.cardError(i)==null&&d.model.state.left.hand[i]!=0){int card=d.model.state.left.hand[i];int value=card==12?120:card==10?110:card==11?20:card==13||card==14?0:(card-1)%3+1+((card-1)/3==d.model.state.topic?10:0);if(slot<0||(poor?value<score:value>score)){slot=i;score=value;}}
  if(slot<0)for(int i=0;i<d.model.state.left.slots;i++)if(d.cardError(i)==null){slot=i;break;}check(slot>=0,"legal card exists");check(w.contests.debateCard(session.id,session.revision,slot).ok,"ordinary legal human card");byte[] b=SaveCodec.encode(w);World restored=SaveCodec.decode(b);check(Arrays.equals(b,SaveCodec.encode(restored)),"complete native model/campaign/all RNG reload each input");w=restored;
 }
 check(!w.contests.busy(),"actual production native session released");int success=w.officer(targetId).owner==owner?1:0;check(w.nextTurn().ok,"ordinary next turn unblocked after actual terminal");byte[] done=SaveCodec.encode(w);check(Arrays.equals(done,SaveCodec.encode(SaveCodec.decode(done))),"post-result whole turn fullWorld/all RNG");return success;
 }
 public static void main(String[] args)throws Exception {
  int wins=0,losses=0;
  for(int seed=1;seed<=20&&(wins==0||losses==0);seed++){
   World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,seed);var actor=person(w,116);var target=person(w,222);check(w.contests.nativeCampaignSettlementEnabled(),"fresh source ordinary campaign policy explicit");check(w.contests.persuade(actor.cityId,actor.id,target.id).ok,"actual ordinary source recruitment-debate command");int won=play(w,seed%2==0);wins+=won;losses+=1-won;
  }
  check(wins>0&&losses>0,"real source human wins and losses without forced result");
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));byte[] raw=SaveCodec.encode(old);check(!old.contests.nativeCampaignSettlementEnabled()&&Arrays.equals(raw,SaveCodec.encode(SaveCodec.decode(raw))),"genuine prototype39 no silent settlement migration");var session=old.contests.current();check(session!=null&&session.nativeDebate!=null,"real old saved active native model");World rejected=SaveCodec.decode(raw);rejected.extensions.put(PcDebateCampaignPolicy.NAMESPACE,new byte[]{7,8,9});byte[] rejectedBefore=SaveCodec.encode(rejected);var rejectedSession=rejected.contests.current();check(!rejected.contests.adoptNativeDebateSettlement(rejectedSession.id,rejectedSession.revision).ok,"opaque existing policy blocks adoption");check(rejected.extensions.get(PcNativeHealthPolicy.NAMESPACE)==null&&Arrays.equals(rejectedBefore,SaveCodec.encode(rejected)),"failed opaque adoption writes no health or campaign namespace and preserves fullWorld/all RNG");byte[] beforeModel=PcDebateModelSave.write(session.nativeDebate.model);long strategy=old.strategy.randomState,life=old.life.randomState;int nativeSeed=PcNativeDebatePolicy.seed(old);var adoption=old.contests.adoptNativeDebateSettlement(session.id,session.revision);check(adoption.ok,"explicit existing saved prototype adoption: "+adoption.message);check(Arrays.equals(beforeModel,PcDebateModelSave.write(session.nativeDebate.model))&&old.strategy.randomState==strategy&&old.life.randomState==life&&PcNativeDebatePolicy.seed(old)==nativeSeed,"adoption preserves original hand/model/all RNG");byte[] adopted=SaveCodec.encode(old);check(Arrays.equals(adopted,SaveCodec.encode(SaveCodec.decode(adopted))),"explicit adopted fullWorld/model exact save");play(SaveCodec.decode(adopted),false);
  System.out.println("PASS ordinary source native debate campaign "+checks+" checks wins="+wins+" losses="+losses+"; actual legal inputs/save/reloads/real terminal/wholeturn; genuine39 explicit adoption unchanged model/RNG; start admission/fees/abandon/diplomacy remain unfinished");
 }
}
