package game.sanguo.core;
import java.util.*;
public final class PcDelayedProductionFlowTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static World fixture(boolean nativeMode){World w=CityActionPlanTest.fixture();
  for(var kind:new Domestic.Kind[]{Domestic.Kind.SMITH,Domestic.Kind.STABLE,Domestic.Kind.WORKSHOP,Domestic.Kind.SHIPYARD}){
   var h=w.domestic.buildSites(10).get(0);if(kind==Domestic.Kind.SHIPYARD){var water=h.neighbors().stream().filter(n->w.inside(n)&&w.cityAt(n)==null&&w.domestic.at(n)==null).findFirst().orElseThrow();w.terrain[water.q][water.r]=World.Terrain.WATER;}w.domestic.facilities.add(new Domestic.Facility(w.domestic.nextFacilityId++,10,kind,h,-1,0));
  }w.campaign.learned.put(0,EnumSet.allOf(Campaign.Tech.class));w.campaign.learned.get(0).remove(Campaign.Tech.WARSHIP);w.officerAbilities.initializeOpening(null,false,false);w.merchantMarket.initializeOpening();if(nativeMode)w.pcProduction.initializeOpening();for(int id:new int[]{1,2,3})OfficerAbilities.setBase(w.officer(id),2,80);return w;}
 static int stock(World w,World.Weapon weapon,Army.Ship ship){return weapon==null?w.city(10).ships[ship.ordinal()-1]:w.city(10).equipment[weapon.ordinal()];}
 public static void main(String[] args)throws Exception{
  for(int workers=1;workers<=3;workers++)for(boolean skill:new boolean[]{false,true})for(int item:new int[]{5,6,7,8,10,11}){
   World.Weapon weapon=item==5?World.Weapon.RAM:item==6?World.Weapon.SIEGE_TOWER:item==7?World.Weapon.CATAPULT:item==8?World.Weapon.WOODEN_BEAST:null;Army.Ship ship=item==10?Army.Ship.TOWER_SHIP:item==11?Army.Ship.WARSHIP:null;World w=fixture(true);w.campaign.learned.get(0).add(Campaign.Tech.WARSHIP);int[] ids=new int[workers];for(int n=0;n<workers;n++)ids[n]=n+1;if(skill)w.officer(ids[workers-1]).skillId=weapon==null?Skill.ZAOCHUAN.id:Skill.FAMING.id;
   var op=ship==null?ProductionPlan.Operation.EQUIPMENT:ProductionPlan.Operation.SHIP;byte[] before=SaveCodec.encode(w);long rng=w.strategy.getRandomState();var p=w.previewProduction(10,ids,op,weapon,ship);check(p.allowed(),"native delayed admission "+item+":"+(p.failure==null?"":p.failure.detail));
   int expected;
   int[] current=new int[workers];Arrays.fill(current,80);expected=PcProduction.delayedCounter(current,item,skill&&weapon!=null,skill&&weapon==null,false);check(p.effects.busyTurns==expected&&p.effects.actors.size()==workers,"counter/allactor preview");check(Arrays.equals(before,SaveCodec.encode(w)),"preview fullpure");int initial=stock(w,weapon,ship),gold=w.city(10).gold;int[] merit=Arrays.stream(ids).map(w.government::merit).toArray();World replay=SaveCodec.decode(before);
   check(w.army.produce(10,ids,weapon,ship).ok&&replay.army.produce(10,ids,weapon,ship).ok,"normal delayed crew start");check(w.city(10).gold==gold-p.goldCost&&w.actionPoints[0]==40&&w.strategy.getRandomState()==rng,"one native fee/AP noRNG");for(int n=0;n<workers;n++)check(w.officerAbilities.experience(ids[n],2)==0&&w.government.merit(ids[n])==merit[n]&&w.officer(ids[n]).otherTaskTurns==expected,"start has noXP/merit");check(Arrays.equals(SaveCodec.encode(w),SaveCodec.encode(replay)),"native jobmetadata exact roundtrip");World after=SaveCodec.decode(SaveCodec.encode(w));check(after.army.productions.get(0).officers().length==workers,"all staff persisted");
   for(int turn=1;turn<=expected;turn++){check(w.nextTurn().ok&&replay.nextTurn().ok,"actual complete native turns");check(Arrays.equals(SaveCodec.encode(w),SaveCodec.encode(replay)),"save/replay continues exactly");if(turn<expected){check(stock(w,weapon,ship)==initial&&w.domestic.remainingUses(10,weapon==null?Domestic.Kind.SHIPYARD:Domestic.Kind.WORKSHOP)==0,"noearlycredit,facilityreserved throughturns");}else{check(stock(w,weapon,ship)==initial+1&&w.army.productions.isEmpty(),"one credit andtaskremoved onexactturn");for(int id:ids)check(w.officerAbilities.experience(id,2)==4&&w.officer(id).otherTaskTurns==0&&w.officer(id).otherTask.isEmpty(),"eachXP4/cleared once");}}
  }
  World old=fixture(false);check(old.army.produce(10,1,World.Weapon.RAM,null).ok,"old task normalstart");World saved=SaveCodec.decode(SaveCodec.encode(old));for(int n=0;n<3;n++){check(old.nextTurn().ok&&saved.nextTurn().ok,"old ordinaryturn");check(Arrays.equals(SaveCodec.encode(old),SaveCodec.encode(saved)),"old jobexactcontinuation");}check(old.officerAbilities.experience(1,2)==0,"old task notretrorewarded");
  System.out.println("PASS PcDelayedProductionFlowTest checks="+checks+" actualnormalcrew/turns/save/reservation; stagedonly");
 }
}
