package game.sanguo.core;
import java.util.*;import java.nio.file.*;
/** Actual ordinary source direct command, complete saved-state/RNG/turn checks. */
public final class PcDirectRecruitmentPolicyTest {
 static int checks;static void check(boolean b,String m){checks++;if(!b)throw new AssertionError(m);}
 static World.Officer person(World w,int nativeId)throws Exception{return PcDebateOrdinaryCampaignTest.person(w,nativeId);}
 public static void main(String[]args)throws Exception {
  int[]actors={116,163,195,198,251,355,365,377,466};boolean[]success={false,true,false,false,false,false,false,true,false};
  for(int i=0;i<actors.length;i++){
   World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);if(!PcDirectRecruitmentPolicy.enabled(w))PcDirectRecruitmentPolicy.initializeOpening(w);World.Officer actor=person(w,actors[i]),target=person(w,222);int city=actor.cityId,ap=w.cityActionPoints(w.city(city)),gold=w.city(city).gold,merit=w.government.merit(actor.id);int[]base=actor.abilityProfile.base.clone();long rng=w.strategy.randomState,life=w.life.randomState;int nativeRng=PcNativeDebatePolicy.seed(w);byte[]before=SaveCodec.encode(w);
   RecruitmentPlan plan=w.strategy.previewRecruitment(city,actor.id,target.id);check(plan.allowed()&&plan.nativeRules&&plan.goldCost==0&&plan.actionPointsCost==20,"ordinary direct samecity quote0/20 "+actors[i]);check(plan.nativeSuccess==success[i],"independent original4afd60 result "+actors[i]);check(Arrays.equals(before,SaveCodec.encode(w)),"preview fullWorld/all RNG pure");
   check(w.strategy.recruitOfficer(city,actor.id,target.id).ok,"normal direct command");check(w.cityActionPoints(w.city(city))==ap-20&&w.city(city).gold==gold,"real original AP20/gold0 once");check(w.government.merit(actor.id)==merit+(success[i]?200:10)&&w.officerAbilities.experience(actor.id,4)==(success[i]?5:1),"original direct merit/charmXP, not search rewards");check(w.officerAbilities.experience(actor.id,3)==0&&Arrays.equals(base,actor.abilityProfile.base),"no search POLXP or base rewrite");check(w.campaign.points(w.player)==(success[i]?12:0),"original direct TP");check(target.owner==(success[i]?2:-1)&&target.loyalty==(success[i]?94:0),"original source join/loyalty");check(actor.acted&&target.acted==success[i],"original action flags");check(w.strategy.randomState==rng&&w.life.randomState==life&&PcNativeDebatePolicy.seed(w)==nativeRng,"all RNG unchanged originalmode0");byte[]after=SaveCodec.encode(w);check(Arrays.equals(after,SaveCodec.encode(SaveCodec.decode(after))),"complete source direct saved exact");check(!w.strategy.recruitOfficer(city,actor.id,target.id).ok&&Arrays.equals(after,SaveCodec.encode(w)),"direct repeat pure refusal");World replay=SaveCodec.decode(after);check(w.nextTurn().ok&&replay.nextTurn().ok,"whole campaign turn after normal direct");check(Arrays.equals(SaveCodec.encode(w),SaveCodec.encode(replay)),"whole turn/save/all RNG identical");
  }
  World unknown=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);unknown.extensions.put(PcDirectRecruitmentPolicy.NAMESPACE,new byte[]{5,6,7});byte[]opaque=SaveCodec.encode(unknown);check(!PcDirectRecruitmentPolicy.enabled(unknown)&&Arrays.equals(opaque,SaveCodec.encode(SaveCodec.decode(opaque))),"opaque existing extension preserved");
  World changed=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);World.Officer ca=person(changed,116),ct=person(changed,222);check(changed.strategy.previewRecruitment(ca.cityId,ca.id,ct.id).nativeRules,"fresh default original raw trust");changed.government.allegianceChanged(ct.id);check(!changed.strategy.previewRecruitment(ca.cityId,ca.id,ct.id).nativeRules,"allegiance event invalidates old raw trust even when current display0");byte[]untrusted=SaveCodec.encode(changed);World loaded=SaveCodec.decode(untrusted);check(Arrays.equals(untrusted,SaveCodec.encode(loaded))&&!loaded.strategy.previewRecruitment(ca.cityId,ca.id,ct.id).nativeRules,"save/reload never refills invalidated raw trust");
  World idle=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);idle.extensions.put(PcArmyActionPolicy.NAMESPACE,new byte[]{1,2,3});Arrays.fill(idle.actionPoints,60);byte[]idleBefore=SaveCodec.encode(idle);check(Arrays.equals(idleBefore,SaveCodec.encode(SaveCodec.decode(idleBefore))),"idle direct strategy preserves unknown opaque budget without adopting");
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));byte[]raw=SaveCodec.encode(old);check(!PcDirectRecruitmentPolicy.enabled(old)&&old.extensions.get(PcDirectRecruitmentPolicy.NAMESPACE)==null&&Arrays.equals(raw,SaveCodec.encode(SaveCodec.decode(raw))),"genuine39 no direct adoption/backfill");
  System.out.println("PASS ordinary original independent samecity direct recruitment "+checks+" checks; special gates/currentraw/other sources/crosscity/playerAPK remain separate");
 }
}
