package game.sanguo.core;
import java.util.*;
public final class PcDuelEditedCurrentFactsTest {
    static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
    public static void main(String[]args)throws Exception {
        for(var source:PcScenarioCatalog.all()){World opening=PcScenarioCatalog.load(source.identity.scenarioId,-1,23);PcDuelKinship.unchangedParents(opening);check(true,"distinct source public/internal parents validated");}
        World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);int[]natives={365,116,466};int[]ids=new int[3];for(int i=0;i<3;i++){final int n=natives[i];ids[i]=PcDuelSourceFacts.saved(w).values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}
        Hex h=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex candidate=new Hex(q,r);if(w.cost(candidate,World.Weapon.SWORD)>0&&w.cityAt(candidate)==null){h=candidate;break outer;}}
        var u=new World.Unit(1,2,ids[0],World.Weapon.SWORD,h,5000,17000);u.deputies=new int[]{ids[1],ids[2]};w.units.add(u);w.nextUnitId=2;for(int id:ids){var o=w.officer(id);w.strategy.releaseGovernor(id);o.unitId=1;o.cityId=-1;}w.governance.reconcile(false);
        int[]original=PcDuelUnitStats.currentCrew(w,u);int raw=PcDuelRawLoyalty.current(w,ids[1]);var o=w.officer(ids[1]);var t=w.editor.template(o.id);int[]base=new int[5];for(int i=0;i<5;i++)base[i]=t.stat(i);base[1]=Math.min(100,base[1]+5);int[]apt=o.aptitude.clone();var draft=w.editor.officer(o.id,base,apt,o.sex,o.skillId,o.loyalty,w.government.merit(o.id),t.temper,t.talkMask);check(draft.valid(),"actual base editor preview "+draft.error);check(w.editor.apply(draft).ok,"actual base editor apply");check(w.editor.edited(),"real saved edited flag");check(PcDuelRawLoyalty.current(w,o.id)==raw,"base-only retains current raw loyalty");
        byte[]before=SaveCodec.encode(w);World cold=SaveCodec.decode(before);int[]current=PcDuelUnitStats.currentCrew(cold,cold.unit(1));check(current[1]>=original[1],"current abilities consumed after base edit");var runtime=PcDuelRuntimeFacts.saved(cold);PcDuelBindings.support(cold,ids[1],ids[0],ids[2],runtime,PcDuelRawLoyalty.current(cold,ids[1]));PcDuelKinship.nonHarm(cold,ids[1],ids[0]);check(Arrays.equals(before,SaveCodec.encode(cold)),"all reads pure after actual editor/cold save");
        int[]six={ids[0],ids[1],ids[2],ids[0],ids[1],ids[2]};boolean[][]matrix=PcDuelKinship.terminal(cold,six);for(int i=0;i<6;i++)for(int j=0;j<6;j++)check(matrix[i][j]==PcDuelKinship.nonHarm(cold,six[i],six[j]),"whole terminal equals individually validated current relation");check(Arrays.equals(before,SaveCodec.encode(cold)),"terminal reuse fullWorld/RNG purity");
        cold.relations.people.computeIfAbsent(ids[1],id->new Relations.Person()).father=ids[2];boolean parentDenied=false;try{PcDuelKinship.nonHarm(cold,ids[1],ids[0]);}catch(java.io.IOException e){parentDenied=e.getMessage().contains("父母");}check(parentDenied,"changed public parent blocks stale internal graph");boolean terminalDenied=false;try{PcDuelKinship.terminal(cold,six);}catch(java.io.IOException e){terminalDenied=e.getMessage().contains("父母");}check(terminalDenied,"terminal still refuses changed whole parent graph");
        cold=SaveCodec.decode(before);
        cold.relations.people.computeIfAbsent(ids[1],id->new Relations.Person()).sworn.add(ids[2]);boolean denied=false;try{PcDuelUnitStats.currentCrew(cold,cold.unit(1));}catch(java.io.IOException e){denied=e.getMessage().contains("义兄弟");}check(denied,"actual unresolved sworn change refused");
        System.out.println("PASS edited current facts "+checks+" checks; actual editor/base/current/coldSave; ordinary duel/APK pending");
    }
}
