package game.sanguo.core;
import java.nio.file.*;import java.util.*;import java.nio.*;
/** Declared callback fixture against original4a8440 source0 CITY8 receipt;
 * does not substitute for ordinary menu/probability/whole-turn APK evidence. */
public final class PcDuelSameCityRecruitmentTest{
 static int n;static void check(boolean b,String s){n++;if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception{
  byte[] receipt=Files.readAllBytes(Path.of(args[0]));check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(receipt)).equals(PcDuelHumanActorPolicy.SAME_CITY_RECRUIT_RECEIPT_SHA),"original zero callback receipt SHA");
  String raw=new String(receipt,java.nio.charset.StandardCharsets.UTF_8);var numbers=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(raw);String parsed=numbers.replaceAll(m->Integer.toString((int)Long.parseLong(m.group())));var json=MapJson.object(MapJson.parse(parsed.getBytes(java.nio.charset.StandardCharsets.UTF_8)));byte[] original=HexFormat.of().parseHex((String)json.get("afterHex"));var fields=ByteBuffer.wrap(original).order(ByteOrder.LITTLE_ENDIAN);
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23,new PcDuelOptions(0,2,0));w.extensions.put(PcDuelHumanActorPolicy.NAMESPACE,null);var facts=PcDuelSourceFacts.saved(w);int[] natives={365,116,466,558,14,517},ids=new int[6];
  for(int i=0;i<6;i++){final int nativeId=natives[i];ids[i]=facts.values().stream().filter(f->f.nativeId==nativeId).findFirst().orElseThrow().officerId;}
  for(int side=0;side<2;side++){var leader=w.officer(ids[side*3]);var home=w.city(leader.cityId);Hex cell=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r);if(w.cost(h,World.Weapon.SWORD)>0&&!w.army.water(h)&&w.cityAt(h)==null&&w.units.stream().noneMatch(v->v.hex.equals(h))&&PcPersonnelReturnRules.cityAt(w,h)==8){cell=h;break outer;}}check(cell!=null,"declared legal CITY8 cell");var u=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,cell,5000,10000);u.deputies=new int[]{ids[side*3+1],ids[side*3+2]};u.gold=700;u.energy=100;u.acted=true;w.units.add(u);for(int slot=0;slot<3;slot++){var o=w.officer(ids[side*3+slot]);w.strategy.releaseGovernor(o.id);o.unitId=u.id;o.cityId=-1;o.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}
  w.nextUnitId=3;w.governance.reconcile(false);byte[] before=SaveCodec.encode(w);boolean rejected=false;try{PcDuelRecruitment.validate(w,w.unit(1),w.unit(2),ids[3]);}catch(java.io.IOException e){rejected=true;}check(rejected&&Arrays.equals(before,SaveCodec.encode(w)),"legacy zero branch remains rejected and pure");check(Arrays.equals(before,SaveCodec.encode(SaveCodec.decode(before))),"old complete cold no adoption");
  PcDuelHumanActorPolicy.adopt(w);before=SaveCodec.encode(w);long rng=w.strategy.getRandomState();int nativeRng=PcNativeDebatePolicy.seed(w);PcDuelRecruitment.validate(w,w.unit(1),w.unit(2),ids[3]);check(Arrays.equals(before,SaveCodec.encode(w)),"new callback preview pure");
  boolean port=false;int samePort=-1;for(int site=42;site<87;site++)if(PcPersonnelReturnRules.parent(site)==8){samePort=site;break;}check(samePort>=0,"source same-parent nonCITY test input");try{PcDuelRelease.validateReturn(w,8,samePort);}catch(java.io.IOException e){port=true;}check(port&&Arrays.equals(before,SaveCodec.encode(w)),"same-parent gate/port not relaxed");
  PcDuelRecruitment.apply(w,w.unit(1),w.unit(2),ids[3]);var o=w.officer(ids[3]);var assigned=PcGovernorPolicy.data(w).assignments.get(o.id);check(assigned.army==fields.getInt(0x94)&&assigned.home==fields.getInt(0x98)&&o.cityId==PcPersonnelReturnRules.projectSite(w,fields.getInt(0x9c)),"original allegiance/home/current exact");check(o.loyalty==(original[0xac]&255)&&o.role==Strategy.Role.OFFICER,"original loyalty/status exact");check(fields.getInt(0x13c)==37&&original[0x158]==0&&PcDuelRelease.busy(w,o.id)&&PcDuelRelease.remaining(w,o.id)==0&&o.acted,"original task37 duration0 stays pending");
  byte[] pending=SaveCodec.encode(w);w=SaveCodec.decode(pending);check(Arrays.equals(pending,SaveCodec.encode(w))&&PcDuelRelease.busy(w,o.id),"zero task complete cold exact");PcDuelRelease.tick(w);o=w.officer(ids[3]);byte[] phase=HexFormat.of().parseHex((String)MapJson.object(MapJson.array(json.get("personnelPhases")).get(0)).get("personHex"));check(ByteBuffer.wrap(phase).order(ByteOrder.LITTLE_ENDIAN).getInt(0x13c)==-1&&!PcDuelRelease.busy(w,o.id)&&!o.acted&&o.cityId==PcPersonnelReturnRules.projectSite(w,8),"next personnel phase original arrival");check(w.strategy.getRandomState()==rng&&PcNativeDebatePolicy.seed(w)==nativeRng,"both RNG preserved");byte[] after=SaveCodec.encode(w);check(Arrays.equals(after,SaveCodec.encode(SaveCodec.decode(after))),"arrived complete cold exact");check(Arrays.equals(receipt,Files.readAllBytes(Path.of(args[0]))),"original evidence retained");System.out.println("PASS original same CITY recruit "+n+" checks; declared callback only, APK required");
 }
}
