package game.sanguo.core;
import java.util.*;
/** Constructed correct source crews; ordinary command and broad casualty cases separate. */
public final class PcDuelCaptureTest {
 static int checks;static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
 public static void main(String[]args)throws Exception{
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);var facts=PcDuelSourceFacts.saved(w);int[]natives={365,116,466,558,14,517},ids=new int[6];for(int i=0;i<6;i++){final int n=natives[i];ids[i]=facts.values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}
  Hex left=null,right=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),k=new Hex(q+1,r);if(w.inside(k)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(k,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(k)){left=h;right=k;break outer;}}
  for(int side=0;side<2;side++){var leader=w.officer(ids[side*3]);var home=w.city(leader.cityId);var u=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,side==0?left:right,5000,10000);u.deputies=new int[]{ids[side*3+1],ids[side*3+2]};u.gold=700;u.energy=100;u.acted=true;w.units.add(u);for(int slot=0;slot<3;slot++){var o=w.officer(ids[side*3+slot]);w.strategy.releaseGovernor(o.id);o.unitId=u.id;o.cityId=-1;o.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}
  w.nextUnitId=3;w.governance.reconcile(false);// Declared original rank54/book30 fixtures match the actual source cleanup matrix.
  var rank=PcOfficerRanks.all().get(54);w.government.ranks.put(ids[3],rank.projectId);w.government.merits.put(ids[3],Math.max(w.government.merit(ids[3]),rank.merit));w.officerAbilities.refresh(w.officer(ids[3]));w.treasures.place(Treasures.definition("item-030"),Treasures.Place.OFFICER,ids[3]);
  byte[]before=SaveCodec.encode(w);long rng=w.strategy.getRandomState();int nativeRng=PcNativeDebatePolicy.seed(w),owner=w.officer(ids[3]).owner;var loser=w.unit(2);var winner=w.unit(1);int winnerHome=PcGovernorPolicy.view(w).officerAdministrativeHomeNative.get(ids[0]);
  PcDuelCapture.validate(w,winner,loser,ids[3]);check(Arrays.equals(before,SaveCodec.encode(w)),"capture validation fullWorld/both RNG pure");int replacement=PcDuelCapture.apply(w,winner,loser,ids[3],ids[1]);check(replacement==ids[5]&&w.unit(2)==loser&&loser.officerId==ids[5]&&Arrays.equals(loser.deputies,new int[]{ids[4]}),"original linked leader capture retains unit and appoints native517");
  var p=w.government.prisoner(ids[3]);check(p!=null&&p.unitId==1&&p.cityId==-1&&p.captor==winner.owner&&w.officer(ids[3]).owner==owner,"victor escort and original allegiance");check(w.government.office(ids[3])==null&&w.treasures.item("item-030").place==Treasures.Place.OFFICER&&w.treasures.item("item-030").holder==ids[0],"original rank removal and deputy victory book to commander, no treasury substitution");check(w.officer(ids[3]).unitId==-1&&w.officer(ids[3]).cityId==-1&&w.officer(ids[3]).otherTaskTurns==0,"captured person no longer active crew/task");check(PcGovernorPolicy.view(w).officerAdministrativeHomeNative.get(ids[3])==winnerHome,"original captured administrative home follows victor home");check(loser.gold==700&&loser.food==10000&&loser.troops==5000&&loser.energy==100&&loser.acted,"cargo and action preserved before terminal losses");check(rng==w.strategy.getRandomState()&&nativeRng==PcNativeDebatePolicy.seed(w),"capture and commander selection do not redraw RNG");byte[]after=SaveCodec.encode(w);World loaded=SaveCodec.decode(after);check(Arrays.equals(after,SaveCodec.encode(loaded)),"full source World/captive/formation/both RNG roundtrip");
  boolean rejected=false;try{PcDuelCapture.apply(w,winner,loser,ids[3]);}catch(java.io.IOException e){rejected=true;}check(rejected&&Arrays.equals(after,SaveCodec.encode(w)),"duplicate capture rejects before mutation");
  System.out.println("PASS constructed original capture "+checks+" checks; ordinary admission/treasures/offices/rulers/death incomplete");
 }
}
