package game.sanguo.core;
import java.nio.file.*;
import java.util.*;
/** Original full611-frame execution endpoint; constructed units explicitly
 * remain separate from ordinary admission and a fresh-source capability. */
public final class PcDuelExecutionTest {
    static int checks;static void check(boolean b,String label){checks++;if(!b)throw new AssertionError(label);}
    public static void main(String[]args)throws Exception {
        String raw=Files.readString(Path.of(args[0]));var numbers=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(raw);var receipt=MapJson.object(MapJson.parse(numbers.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8)));
        byte[]original=null;for(Object row:MapJson.array(receipt.get("personAfter"))){var p=MapJson.object(row);if(((Number)p.get("nativeId")).intValue()==558)original=HexFormat.of().parseHex((String)p.get("hex"));}if(original==null)throw new AssertionError("Original execution target missing");var fields=java.nio.ByteBuffer.wrap(original).order(java.nio.ByteOrder.LITTLE_ENDIAN);
        World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);var joined=new HashMap<Integer,Integer>();for(var f:PcDuelSourceFacts.saved(w).values())joined.put(f.nativeId,f.officerId);int[]natives={365,116,466,558,14,517};
        Hex first=null;outer:for(int q=0;q<w.width;q++)for(int y=0;y<w.height;y++){Hex h=new Hex(q,y),k=new Hex(q+1,y);if(w.inside(k)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(k,World.Weapon.SWORD)>0&&w.cityAt(h)==null&&w.cityAt(k)==null&&!w.army.water(h)&&!w.army.water(k)){first=h;break outer;}}
        for(int side=0;side<2;side++){int leader=joined.get(natives[3*side]);var o=w.officer(leader);var home=w.city(o.cityId);var u=new World.Unit(side+1,o.owner,leader,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,17000);u.deputies=new int[]{joined.get(natives[3*side+1]),joined.get(natives[3*side+2])};u.gold=997;u.acted=true;w.units.add(u);for(var person:w.army.crew(u)){w.strategy.releaseGovernor(person.id);person.unitId=u.id;person.cityId=-1;person.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}
        w.nextUnitId=3;w.governance.reconcile(false);int id=joined.get(558);byte[]before=SaveCodec.encode(w);long random=w.strategy.getRandomState();int nativeRandom=PcNativeDebatePolicy.seed(w);int merit=w.government.merit(id),xp=w.officerAbilities.experience(id,1);PcDuelExecution.validate(w,w.unit(1),w.unit(2),id);check(Arrays.equals(before,SaveCodec.encode(w)),"execution preview fullWorld/bothRNG pure");
        PcDuelHealthPolicy.writeDuelResult(w,Map.of(id,original[0x128]&255));PcDuelExecution.apply(w,w.unit(1),w.unit(2),id);var target=w.officer(id);var a=PcGovernorPolicy.data(w).assignments.get(id);
        check(fields.getInt(0xa0)==8&&w.life.state(id)==Lifecycle.State.DEAD,"original status8 death");check(target.owner==-1&&target.cityId==fields.getInt(0x9c)&&target.unitId==-1&&a.home==fields.getInt(0x98)&&a.army==fields.getInt(0x94),"original complete ownership/station/army removal");check(w.government.office(id)==null&&fields.getInt(0xa4)==-1&&target.loyalty==(original[0xac]&255),"original office and loyalty clear");
        check(PcDuelHealthPolicy.health(w,id)==1,"original death retains physicalHP1");check(w.unit(2).officerId==joined.get(517)&&Arrays.equals(w.unit(2).deputies,new int[]{joined.get(14)}),"original native517 replacement/native14 deputy");check(w.unit(2).gold==997&&w.unit(2).food==17000&&w.unit(2).troops==5000,"preserve before terminal aggregate cargo/troops");check(w.government.merit(id)==merit&&w.officerAbilities.experience(id,1)==xp,"old policy retains existing merit/XP semantics");
        check(w.strategy.getRandomState()==random&&PcNativeDebatePolicy.seed(w)==nativeRandom,"execution does not redraw either RNG");byte[]after=SaveCodec.encode(w);check(Arrays.equals(after,SaveCodec.encode(SaveCodec.decode(after))),"complete executed World/lifecycle/administration bothRNG cold save");boolean refused=false;try{PcDuelExecution.apply(w,w.unit(1),w.unit(2),id);}catch(java.io.IOException e){refused=true;}check(refused&&Arrays.equals(after,SaveCodec.encode(w)),"duplicate execution rejects byte pure");
        System.out.println("PASS original ordinary-officer execution "+checks+" checks; full terminal aggregate/ordinary command/rulers/APK pending");
    }
}
