package game.sanguo.core;
import java.nio.file.*;import java.nio.*;import java.util.*;
/** Two complete original escort unit deletions, same/foreign allegiance.
 * Declared current units/capture are fixtures; native return is production. */
public final class PcDuelEscortReleaseTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static int n(Map<String,Object> m,String k){return ((Number)m.get(k)).intValue();}
 public static void main(String[]args)throws Exception {
  boolean execution=args.length>0&&args[0].equals("--execute");
  for(String input:args){if(input.equals("--execute"))continue;String text=Files.readString(Path.of(input));var matcher=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);var original=MapJson.object(MapJson.parse(matcher.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8)));check(Boolean.TRUE.equals(original.get("wholeWorldAndRngRestored"))&&n(original,"rngBefore")==n(original,"rngAfter"),"complete original World/RNG restored/no draw");int captiveNative=original.containsKey("prisonerNative")?n(original,"prisonerNative"):355;
   World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,24,new PcDuelOptions(0,0,0));var ids=PcDuelSwornPolicyTest.ids(w);int captive=ids.get(captiveNative),ruler=ids.get(635),departed=ids.get(614),victor=ids.get(377);var crown=PcRulerCoronation.preview(w,PcRulerSuccession.preview(w,departed).choose(ruler));PcRulerCoronation.apply(w,crown);w.life.die(departed,"declared verified original coronation");PcDuelRawLoyalty.originalWrite(w,departed,0);
   Hex first=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),k=new Hex(q+1,r);if(w.inside(k)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(k,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(k)&&w.cityAt(h)==null&&w.cityAt(k)==null&&PcPersonnelReturnRules.cityAt(w,k)==15){first=h;break outer;}}check(first!=null,"original region15 legal fixture");PcDuelSwornPolicyTest.deploy(w,victor,1,first);PcDuelSwornPolicyTest.deploy(w,ruler,2,new Hex(first.q+1,first.r));var target=w.officer(captive);w.government.capture(target,w.unit(2));var data=PcGovernorPolicy.data(w);var a=data.assignments.get(captive);a.army=PcArmyActionPolicy.primaryArmy(w,target.owner);a.home=data.assignments.get(ruler).home;a.lastCity=-1;PcGovernorPolicy.write(w,data);
   byte[] before=SaveCodec.encode(w);var plan=PcDuelEscortRelease.plan(w,w.unit(2));check(plan.rows.size()==1&&plan.rows.get(0).id==captive,"current exact escorted roster");PcDuelReplacement.select(w,w.unit(2),ruler);check(Arrays.equals(before,SaveCodec.encode(w)),"shared replacement/escort preview wholeWorld/dualRNG pure");if(execution){PcDuelExecution.validate(w,w.unit(1),w.unit(2),ruler);PcDuelHealthPolicy.writeDuelResult(w,Map.of(ruler,1));PcDuelExecution.apply(w,w.unit(1),w.unit(2),ruler);}else PcDuelRelease.apply(w,w.unit(1),w.unit(2),ruler);
   var row=MapJson.object(MapJson.array(original.get("after")).get(captiveNative));byte[] bytes=HexFormat.of().parseHex((String)row.get("hex"));var b=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);var admin=PcGovernorPolicy.data(w).assignments.get(captive);check(!w.government.captive(captive)&&target.owner==(captiveNative==355?2:3)&&target.unitId==-1,"original releases without transfer/allegiance mutation");check(admin.army==b.getInt(0x94)&&admin.home==b.getInt(0x98)&&target.cityId==PcPersonnelReturnRules.projectSite(w,b.getInt(0x9c)),"original exact army/home/current region");check(b.getInt(0x13c)==37&&PcDuelRelease.remaining(w,captive)==(bytes[0x158]&255),"original task37/three-turn travel");check(execution?w.life.state(ruler)==Lifecycle.State.DEAD:PcDuelRelease.busy(w,ruler),"full death or own release preserves carried captive task37 rows");check(w.unit(2)==null&&w.unit(1).gold==997&&w.government.escorted(1).isEmpty(),"removed escort/cargo discarded, no winning prisoner transfer");byte[] saved=SaveCodec.encode(w);w=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(w)),"full escorted release/current World/RNG cold exact");
   for(int turn=0;turn<4;turn++){check(w.nextTurn().ok,"actual campaign return tick");byte[] state=SaveCodec.encode(w);w=SaveCodec.decode(state);check(Arrays.equals(state,SaveCodec.encode(w)),"every complete return turn/cold exact");}check(!PcDuelRelease.busy(w,captive)&&!w.government.captive(captive)&&w.officer(captive).owner==(captiveNative==355?2:3),"released source person completes native return across full turns");if(execution)check(w.life.state(ruler)==Lifecycle.State.DEAD&&w.loyalty.ruler(4)!=null,"full death/crown persists with other captive released");
  }
  System.out.println("PASS original escorted unit deletion/return "+checks+" checks; actual full death/capture/deployment/menu/APK and other cases separate");
 }
}
