package game.sanguo.core;
import java.nio.file.*;
import java.util.*;
/** Continuous computed state compared to original; expected frames never feed rules. */
public final class PcDuelCampaignDriverTest {
 static int checks;
 static void check(boolean ok,String label){checks++;if(!ok)throw new AssertionError(label+" checks="+checks);}
 static PcDuelKernel.Actor[][] copyActors(PcDuelKernel.Actor[][]source){PcDuelKernel.Actor[][]out=new PcDuelKernel.Actor[2][3];for(int side=0;side<2;side++)for(int slot=0;slot<3;slot++){var a=source[side][slot];var b=new PcDuelKernel.Actor(a.nativeId,a.personality,a.war,a.treasureBonus,a.valid,a.predicate488c00);b.originalAge=a.originalAge;b.raw489080=a.raw489080;b.virtual48Value=a.virtual48Value;b.sourceInjuryProtection=a.sourceInjuryProtection;b.warByInjury=a.warByInjury==null?null:a.warByInjury.clone();out[side][slot]=b;}return out;}
 public static void main(String[]args)throws Exception{
  PcDuelKernel m=null;PcDuelKernel.Actor[][]actors=null;PcDuelKernel.SupportFacts[][][][]catalog=null;boolean[][]relations=null;PcDuelKernel.Random random=null;PcDuelKernel.OriginalSettings settings=null;byte[]manager=null;PcDuelCampaign campaign=null;PcDuelCampaign boundary=null,automatic=null;boolean terminalSettingValid=false;int terminalSetting=-1,lastResult=0;
  for(String line:Files.readAllLines(Path.of(args[0]))){if(line.startsWith("#"))continue;String[]p=line.split("\t");
   if(p[0].equals("START")){
    manager=PcDuelKernel.hex(p[2]);m=new PcDuelKernel(new byte[0x59c]);m.set(0,Integer.parseInt(p[3]));random=new PcDuelKernel.Random(23);actors=new PcDuelKernel.Actor[2][3];String[]af=p[7].split(",");
    for(int i=0;i<6;i++){String[]v=af[i].split(":");int[]wars=new int[4];for(int j=0;j<4;j++)wars[j]=Integer.parseInt(v[9+j]);PcDuelKernel.Actor a=new PcDuelKernel.Actor(Integer.parseInt(v[0]),Integer.parseInt(v[1]),wars[0],Integer.parseInt(v[2]),v[3].equals("1"),v[4].equals("1"));a.originalAge=Integer.parseInt(v[5]);a.raw489080=Integer.parseInt(v[6]);a.virtual48Value=v[7].equals("1");a.sourceInjuryProtection=v[8].equals("1");a.warByInjury=wars;actors[i/3][i%3]=a;}
    catalog=new PcDuelKernel.SupportFacts[2][3][3][3];for(String row:p[8].split(",")){String[]v=row.split(":");int[]values=new int[v.length-4];for(int j=0;j<values.length;j++)values[j]=Integer.parseInt(v[j+4]);catalog[Integer.parseInt(v[0])][Integer.parseInt(v[1])][Integer.parseInt(v[2])][Integer.parseInt(v[3])]=new PcDuelKernel.SupportFacts(values);}
    relations=new boolean[6][6];String[]rr=p[9].split(",");for(int i=0;i<36;i++)relations[i/6][i%6]=rr[i].equals("1");settings=new PcDuelKernel.OriginalSettings(p[10].equals("1"),Integer.parseInt(p[11]),p[10].equals("1"),Integer.parseInt(p[12]),p[13].equals("1"),Integer.parseInt(p[14]));terminalSettingValid=p[13].equals("1");terminalSetting=Integer.parseInt(p[14]);
    int[]ids=new int[6],natives=new int[6];byte[] stable=manager.clone();for(int i=0;i<6;i++){ids[i]=actors[i/3][i%3].nativeId;natives[i]=ids[i];PcDuelKernel.writeManager(stable,4*i,ids[i]);}for(int side=0;side<2;side++)PcDuelKernel.writeManager(stable,0x18+side*4,side);
    campaign=PcDuelCampaign.initialize(ids,natives,stable,actors,new int[6][0][2],23,settings);m=campaign.state.model;manager=campaign.state.manager;random=campaign.state.random;
    PcDuelKernel expected=new PcDuelKernel(PcDuelKernel.hex(p[5]));expected.set(0,1);for(int i=0;i<6;i++)expected.set(expected.fighter(i/3,i%3),ids[i]);for(int side=0;side<2;side++)expected.set(0x238+side*24+4,1);
    check(Arrays.equals(m.state,expected.state),"full original initializer normalized identities only");check(Integer.toUnsignedLong(random.state)==Long.parseLong(p[6]),"full initial RNG");lastResult=0;boundary=null;automatic=null;
    if(m.get(0x24+0xd8)==1&&m.get(0x110+0xd8)==1){var savedAuto=new java.io.ByteArrayOutputStream();campaign.write(new java.io.DataOutputStream(savedAuto));automatic=PcDuelCampaign.read(new java.io.DataInputStream(new java.io.ByteArrayInputStream(savedAuto.toByteArray())));final PcDuelKernel.SupportFacts[][][][]sources=catalog;PcDuelCampaign.SupportBinding automaticSupport=model->{PcDuelKernel.SupportFacts[][]out=new PcDuelKernel.SupportFacts[2][3];for(int side=0;side<2;side++)for(int slot=0;slot<3;slot++)out[side][slot]=sources[side][model.activeIndex(side)][model.activeIndex(1-side)][slot];return out;};automatic.advance(copyActors(actors),automaticSupport,relations,false,-1,-1);check(automatic.terminal()&&!automatic.waitingInput(),"AI-only advance reaches terminal without phantom player input");}

   }else if(p[0].equals("FRAME")){
    int next=m.get(8),phase=next>=0&&next<=12?next:m.get(4);final PcDuelKernel.SupportFacts[][][][]bindings=catalog;
    PcDuelCampaign.SupportBinding binding=model->{PcDuelKernel.SupportFacts[][]out=new PcDuelKernel.SupportFacts[2][3];for(int side=0;side<2;side++)for(int slot=0;slot<3;slot++)out[side][slot]=bindings[side][model.activeIndex(side)][model.activeIndex(1-side)][slot];return out;};
    PcDuelCampaign submitted=null;
    if(campaign.waitingInput()&&campaign.state.model.get(0x110+0xd8)==1&&p.length>=9){
     var inputBytes=new java.io.ByteArrayOutputStream();campaign.write(new java.io.DataOutputStream(inputBytes));submitted=PcDuelCampaign.read(new java.io.DataInputStream(new java.io.ByteArrayInputStream(inputBytes.toByteArray())));
     byte[]beforeReject=PcDuelModelSave.write(submitted.state);boolean rejected=false;try{submitted.submit(actors,binding,relations,99,99,99,false);}catch(java.io.IOException expected){rejected=true;}check(rejected&&Arrays.equals(beforeReject,PcDuelModelSave.write(submitted.state)),"invalid input leaves model/manager/RNG unchanged");
     int pphase=submitted.facts().phase,psub=submitted.facts().sub;int pose=pphase==5&&psub==3?Integer.parseInt(p[7]):-1;int special=(pphase==3||pphase==7)&&p.length>=9&&(p[6].equals("request")||p[6].equals("special"))?Integer.parseInt(p[8]):-1;int swap=pphase==5&&psub==4&&p.length>=10?Integer.parseInt(p[9]):-1;
     submitted.submit(copyActors(actors),binding,relations,pose,special,swap,false);check(submitted.waitingInput()||submitted.terminal(),"accepted input reaches saved stable boundary");check(submitted.inputs==campaign.inputs+1,"one accepted input counter");
    }
    lastResult=campaign.frame(actors,binding,relations,p.length>=9&&p[6].equals("request"),p.length>=9&&p[6].equals("pose")?Integer.parseInt(p[7]):-1,p.length>=9&&p[6].equals("special")?Integer.parseInt(p[8]):-1,p.length>=10&&p[6].equals("swap")?Integer.parseInt(p[9]):-1);
    if(submitted!=null)boundary=submitted;
    if(boundary!=null&&campaign.frames==boundary.frames){check(Arrays.equals(campaign.state.model.state,boundary.state.model.state)&&Arrays.equals(campaign.state.manager,boundary.state.manager)&&campaign.state.random.state==boundary.state.random.state&&campaign.state.random.draws==boundary.state.random.draws,"atomic submitted input matches full original frame path at next boundary");boundary=null;}
    java.io.ByteArrayOutputStream saved=new java.io.ByteArrayOutputStream();campaign.write(new java.io.DataOutputStream(saved));campaign=PcDuelCampaign.read(new java.io.DataInputStream(new java.io.ByteArrayInputStream(saved.toByteArray())));m=campaign.state.model;manager=campaign.state.manager;random=campaign.state.random;
    // Rebind from immutable original getter facts as a cold load does. Local
    // model injuries must override this initial actor WAR on the next frame.
    for(var team:actors)for(var actor:team)if(actor.warByInjury!=null)actor.war=actor.warByInjury[0];
    byte[] beforeFacts=PcDuelModelSave.write(campaign.state);int beforeFrames=campaign.frames,beforeInputs=campaign.inputs;
    var facts=campaign.facts();check(Arrays.equals(beforeFacts,PcDuelModelSave.write(campaign.state))&&beforeFrames==campaign.frames&&beforeInputs==campaign.inputs,"detached facts preserve all model/manager/RNG/counters");
    for(var choice:facts.choices){String error=campaign.inputError(choice.stance,choice.special,choice.replacement,false);check(choice.error.equals(error==null?"":error),"displayed action and formal input use identical validator");}
    check(!facts.terminal||facts.choices.isEmpty(),"terminal model offers no further frame input");
    check(facts.teams.size()==2&&facts.frames==campaign.frames&&facts.inputs==campaign.inputs,"fact header");
    for(var team:facts.teams){check(team.fighters.size()==m.get(0x24+team.side*0xec+0xc0),"actual crew count");for(var fighter:team.fighters){int at=m.fighter(team.side,fighter.slot);check(fighter.officerId==campaign.state.officers[team.side*3+fighter.slot]&&fighter.nativeId==campaign.state.natives[team.side*3+fighter.slot]&&fighter.health==m.get(at+4)&&fighter.spirit==m.get(at+8)&&fighter.injury==m.get(at+12)&&fighter.active==(m.activeIndex(team.side)==fighter.slot),"stable participant/model facts");}}
    try{facts.teams.clear();throw new AssertionError("mutable team facts");}catch(UnsupportedOperationException expected){}try{facts.teams.get(0).fighters.get(0).moveCharges.clear();throw new AssertionError("mutable move facts");}catch(UnsupportedOperationException expected){}
    try{facts.choices.clear();throw new AssertionError("mutable input facts");}catch(UnsupportedOperationException expected){}
    String where="case="+p[1]+" frame="+p[2]+" phase="+phase;check(lastResult==Integer.parseInt(p[5]),where+" return");check(Integer.toUnsignedLong(random.state)==Long.parseLong(p[4]),where+" RNG");PcDuelKernel expected=new PcDuelKernel(PcDuelKernel.hex(p[3]));expected.set(0,1);for(int i=0;i<6;i++)expected.set(expected.fighter(i/3,i%3),actors[i/3][i%3].nativeId);for(int side=0;side<2;side++)expected.set(0x238+side*24+4,1);check(Arrays.equals(m.state,expected.state),where+" whole model after saved continuation");
   }else if(p[0].equals("END")){byte[]expected=PcDuelKernel.hex(p[2]);for(int i=0;i<6;i++)PcDuelKernel.writeManager(expected,4*i,actors[i/3][i%3].nativeId);for(int side=0;side<2;side++)PcDuelKernel.writeManager(expected,0x18+4*side,side);check(Arrays.equals(manager,expected),"whole final manager case="+p[1]);check((lastResult==1)==p[3].equals("1"),"whole terminal case="+p[1]);if(automatic!=null)check(Arrays.equals(automatic.state.model.state,m.state)&&Arrays.equals(automatic.state.manager,manager)&&automatic.state.random.state==random.state&&automatic.state.random.draws==random.draws,"one-shot AI advance matches original full model/manager/RNG");System.out.println("PASS continuous case "+p[1]+" terminal "+p[3]);}
  }System.out.println("PASS continuous full initializer/model/manager/RNG "+checks+" checks; normal campaign/APK incomplete");
 }
}
