package game.sanguo.core;
import java.nio.file.*;import java.util.*;
/** Actual archived format5 and genuine39 save bytes: no pending migration. */
public final class PcDuelHeirSaveCompatibilityTest {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception {
  byte[]old=Files.readAllBytes(Path.of("out/session-b/duel-ruler-ai-seed1-nonterminal-v1.sg11"));check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(old)).equals("d13cc26c0b5bd05ec56cfcfb3f1d6264cf769f028ecdb7f9d40fd5d9d30c2b7b"),"actual archived command-boundary checkpoint");World w=SaveCodec.decode(old);check(Arrays.equals(old,SaveCodec.encode(w)),"old format5 exact wholeWorld/model/allRNG encode");var duel=w.contests.current().nativeDuel;check(!duel.heirProtocol&&duel.heirRuler==-1&&duel.chosenHeir==-1,"no old heir adoption");check(w.contests.nativeDuelHeirs().isEmpty()&&Arrays.equals(old,SaveCodec.encode(w)),"old query never upgrades format5");
  byte[]genuine=Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11"));check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(genuine)).equals("5d002d3cee6f84700cd5e1292c05b672e8a05e0b547ac7d753f2b7987d5e2f7f"),"genuine39 artifact");World historical=SaveCodec.decode(genuine);byte[]canonical=SaveCodec.encode(historical);check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(canonical)).equals("05d36bb964bb4a618e0391a80845bd05531574ecae44ce93309ce42cb2faaa2d"),"exact independently compiled completed89534120 canonical encoding");check(genuine.length==canonical.length&&historical.contests.nativeDuelHeirs().isEmpty(),"actual39 no pending strategy backfill");for(int i=0;i<genuine.length;i++)if(i<16||i>19)check(genuine[i]==canonical[i]||i==191589&&genuine[i]==0&&(canonical[i]&255)==255,"all original bytes except existing gzipOS/headerCRC "+i);byte[]a,b;try(var gz=new java.util.zip.GZIPInputStream(new java.io.ByteArrayInputStream(genuine,191580,746))){a=gz.readAllBytes();}try(var gz=new java.util.zip.GZIPInputStream(new java.io.ByteArrayInputStream(canonical,191580,746))){b=gz.readAllBytes();}check(Arrays.equals(a,b)&&a.length==3104,"original native model3104 bytes exact independent of existing gzipOS header");
  System.out.println("PASS old format5 exact/genuine39 completed-baseline+allfield+gzipPayload compatibility; no pending backfill, existinggzipOS header difference retained");
 }
}
