package game.sanguo.core;
import java.nio.file.*;
import java.util.*;
/** Declared original RECRUIT callback endpoint. Constructed units and task
 * ticks explicitly do not prove ordinary admission or full-turn menus. */
public final class PcDuelRecruitmentTest {
    static int checks;
    static void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}
    static int original(Map<String,Object>receipt,String field,int turn,int offset)throws Exception {
        Object rows=turn<0?receipt.get(field):MapJson.object(MapJson.array(receipt.get("returnPhases")).get(turn)).get("people");
        for(Object row:MapJson.array(rows)){var p=MapJson.object(row);if(((Number)p.get("nativeId")).intValue()==558){byte[]b=HexFormat.of().parseHex((String)p.get("hex"));return java.nio.ByteBuffer.wrap(b).order(java.nio.ByteOrder.LITTLE_ENDIAN).getInt(offset);}}throw new AssertionError("original target missing");
    }
    public static void main(String[]args)throws Exception {
        String raw=Files.readString(Path.of(args[0]));var numbers=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(raw);String parsed=numbers.replaceAll(m->Integer.toString((int)Long.parseLong(m.group())));var receipt=MapJson.object(MapJson.parse(parsed.getBytes(java.nio.charset.StandardCharsets.UTF_8)));World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);var facts=PcDuelSourceFacts.saved(w);int[]natives={365,116,466,558,14,517},ids=new int[6];
        for(int i=0;i<6;i++){final int nativeId=natives[i];ids[i]=facts.values().stream().filter(f->f.nativeId==nativeId).findFirst().orElseThrow().officerId;}
        for(int side=0;side<2;side++){var leader=w.officer(ids[side*3]);var home=w.city(leader.cityId);Hex cell=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r);if(w.cost(h,World.Weapon.SWORD)>0&&!w.army.water(h)&&w.cityAt(h)==null&&w.units.stream().noneMatch(v->v.hex.equals(h))&&PcPersonnelReturnRules.cityAt(w,h)==15){cell=h;break outer;}}if(cell==null)throw new AssertionError("no legal region15 land fixture");var u=new World.Unit(side+1,leader.owner,leader.id,World.Weapon.SWORD,cell,5000,10000);u.deputies=new int[]{ids[side*3+1],ids[side*3+2]};u.gold=700;u.energy=100;u.acted=true;w.units.add(u);for(int slot=0;slot<3;slot++){var o=w.officer(ids[side*3+slot]);w.strategy.releaseGovernor(o.id);o.unitId=u.id;o.cityId=-1;o.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}
        w.nextUnitId=3;w.governance.reconcile(false);var equipped=new ArrayList<String>();for(var item:Treasures.catalog()){w.treasures.place(item,Treasures.Place.OFFICER,ids[3]);equipped.add(item.id);}byte[]before=SaveCodec.encode(w);long random=w.strategy.getRandomState();int nativeRandom=PcNativeDebatePolicy.seed(w);var winner=w.unit(1);var loser=w.unit(2);var target=w.officer(ids[3]);
        PcDuelRecruitment.validate(w,winner,loser,target.id);check(Arrays.equals(before,SaveCodec.encode(w)),"recruitment callback preview wholeWorld/bothRNG pure");PcDuelRecruitment.apply(w,winner,loser,target.id);
        check(loser.officerId==ids[5]&&Arrays.equals(loser.deputies,new int[]{ids[4]}),"original replacement517/14");check(target.owner==winner.owner&&!w.government.captive(target.id)&&target.unitId<0,"new allegiance and no captive");
        byte[]original=null;for(Object row:MapJson.array(receipt.get("personAfter"))){var r=MapJson.object(row);if(((Number)r.get("nativeId")).intValue()==558)original=HexFormat.of().parseHex((String)r.get("hex"));}if(original==null)throw new AssertionError("Original target missing");var fields=java.nio.ByteBuffer.wrap(original).order(java.nio.ByteOrder.LITTLE_ENDIAN);var assigned=PcGovernorPolicy.data(w).assignments.get(target.id);
        check(assigned.home==fields.getInt(0x98)&&assigned.army==fields.getInt(0x94),"original new home8/army0");check(target.cityId==PcPersonnelReturnRules.projectSite(w,fields.getInt(0x9c)),"original current origin15");check(PcDuelRawLoyalty.current(w,target.id)==(original[0xac]&255)&&target.loyalty==85,"original raw/display loyalty85");check(PcDuelRelease.busy(w,target.id)&&PcDuelRelease.remaining(w,target.id)==3,"original task37 duration3");check(PcGovernorPolicy.nativeRank(w,target)==fields.getInt(0xa4),"original rank80");
        for(String itemId:equipped){var item=w.treasures.item(itemId);int kind=item.definition.kind.ordinal();check(item.place==Treasures.Place.OFFICER&&item.holder==(kind==6||kind==7?winner.officerId:target.id),"original4a92c0 only native item kinds6/7 transfer "+itemId);}
        byte[]saved=SaveCodec.encode(w);check(Arrays.equals(saved,SaveCodec.encode(SaveCodec.decode(saved))),"complete recruited World cold save");boolean refused=false;try{PcDuelRecruitment.apply(w,winner,loser,target.id);}catch(java.io.IOException e){refused=true;}check(refused&&Arrays.equals(saved,SaveCodec.encode(w)),"duplicate recruitment callback byte pure");
        for(int turn=0;turn<3;turn++){w=SaveCodec.decode(SaveCodec.encode(w));PcDuelRelease.tick(w);target=w.officer(ids[3]);check(w.strategy.getRandomState()==random&&PcNativeDebatePolicy.seed(w)==nativeRandom,"both RNG unchanged task37 "+turn);check(PcDuelRelease.remaining(w,target.id)==2-turn,"duration progression "+turn);int current=original(receipt,"personAfter",turn,0x9c),duration=original(receipt,"personAfter",turn,0x158)&255,task=original(receipt,"personAfter",turn,0x13c);check(target.cityId==PcPersonnelReturnRules.projectSite(w,current),"original current route "+turn);check(PcDuelRelease.remaining(w,target.id)==duration&&PcDuelRelease.busy(w,target.id)==(task==37),"original task37 completion "+turn);byte[]after=SaveCodec.encode(w);check(Arrays.equals(after,SaveCodec.encode(SaveCodec.decode(after))),"complete task37 cold continuation "+turn);}
        check(target.cityId==PcPersonnelReturnRules.projectSite(w,8)&&!target.acted&&!PcDuelRelease.busy(w,target.id),"complete arrival new home8");
        System.out.println("PASS declared ordinary-officer recruitment callback "+checks+" checks; forced gate/fullTurn/menu/APK pending");
    }
}
