package game.sanguo.core;
import java.nio.file.*;import java.util.*;
public final class PcDuelPhysicalRecoveryPolicyTest{
 static int n;static void check(boolean b,String s){n++;if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception{
  byte[]raw=Files.readAllBytes(Path.of(args[0]));World w=SaveCodec.decode(raw);byte[]before=SaveCodec.encode(w);check(!PcDuelPhysicalRecoveryPolicy.enabled(w),"genuine old strategy absent");check(Arrays.equals(before,SaveCodec.encode(SaveCodec.decode(before))),"old full cold exact");
  World full=SaveCodec.decode(before);for(int i=0;full.extensions.putError("full-fixture-"+i,0)==null;i++)full.extensions.put("full-fixture-"+i,new byte[0]);byte[]fullBytes=SaveCodec.encode(full);check(PcDuelPhysicalRecoveryPolicy.adoptionError(full)!=null,"full32 rejects preview");boolean rejected=false;try{PcDuelPhysicalRecoveryPolicy.adopt(full);}catch(java.io.IOException e){rejected=true;}check(rejected&&Arrays.equals(fullBytes,SaveCodec.encode(full)),"full capacity rejection pure");
  PcDuelPhysicalRecoveryPolicy.adopt(w);World stripped=SaveCodec.decode(SaveCodec.encode(w));stripped.extensions.put(PcDuelPhysicalRecoveryPolicy.NAMESPACE,null);check(Arrays.equals(before,SaveCodec.encode(stripped)),"adopt adds marker only, health/all RNG/source unchanged");
  w=SaveCodec.decode(Files.readAllBytes(Path.of(args[1])));PcDuelPhysicalRecoveryPolicy.adopt(w);
  int id=PcDuelSourceFacts.saved(w).values().stream().filter(f->f.nativeId==660).findFirst().orElseThrow().officerId;int hp=PcDuelHealthPolicy.health(w,id);PcDuelPhysicalRecoveryPolicy.tick(w);check(PcDuelHealthPolicy.health(w,id)==hp,"same adoption turn no healing");w.turn++;PcDuelPhysicalRecoveryPolicy.tick(w);check(PcDuelHealthPolicy.health(w,id)==PcDuelPhysicalRecoveryPolicy.recovered(hp,w.contests.injury(id)),"next global turn real source hp");byte[]once=SaveCodec.encode(w);PcDuelPhysicalRecoveryPolicy.tick(w);check(Arrays.equals(once,SaveCodec.encode(w)),"duplicate same turn no second heal/receipt");
  String oracle=Files.readString(Path.of(args[2]));var pattern=java.util.regex.Pattern.compile("\"inputHealth\"\\s*:\\s*(\\d+).*?\"inputInjury\"\\s*:\\s*(\\d+).*?\"outputHealth\"\\s*:\\s*(\\d+)",java.util.regex.Pattern.DOTALL);var matches=pattern.matcher(oracle);int cases=0;while(matches.find()){int health=Integer.parseInt(matches.group(1)),injury=Integer.parseInt(matches.group(2)),expected=Integer.parseInt(matches.group(3));check(PcDuelPhysicalRecoveryPolicy.recovered(health,injury)==expected,"original receipt case "+health+"/"+injury);cases++;}check(cases==44,"all original44 cases consumed");
  for(Lifecycle.State s:Lifecycle.State.values()){var life=w.life.people.get(id);var prior=life.state;life.state=s;check(PcDuelPhysicalRecoveryPolicy.validPerson(w,id)==(s==Lifecycle.State.ACTIVE||s==Lifecycle.State.UNDISCOVERED),"original current status "+s);life.state=prior;}
  World unknown=SaveCodec.decode(before);unknown.extensions.put(PcDuelPhysicalRecoveryPolicy.NAMESPACE,new byte[]{1,2,3,4});byte[]opaque=SaveCodec.encode(unknown);check(!PcDuelPhysicalRecoveryPolicy.enabled(unknown)&&PcDuelPhysicalRecoveryPolicy.adoptionError(unknown)!=null,"opaque retained");check(Arrays.equals(opaque,SaveCodec.encode(SaveCodec.decode(opaque))),"opaque cold full exact");
  World corrupt=SaveCodec.decode(once);byte[]receipt=corrupt.extensions.get(PcDuelPhysicalRecoveryPolicy.NAMESPACE);receipt[receipt.length-1]^=0x40;corrupt.extensions.put(PcDuelPhysicalRecoveryPolicy.NAMESPACE,receipt);rejected=false;try{SaveCodec.encode(corrupt);}catch(java.io.IOException e){rejected=true;}check(rejected,"known corruption rejected");
  World fresh=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,4,0,new PcDuelOptions(0,2,0));check(PcDuelPhysicalRecoveryPolicy.enabled(fresh),"explicit new source initializes");check(Arrays.equals(raw,Files.readAllBytes(Path.of(args[0]))),"actual original evidence preserved");System.out.println("PASS physical recovery policy "+n+" checks; original matrix/status/old/capacity/cold; APK pending");
 }
}
