package game.sanguo.core;
import java.io.*;import java.nio.file.*;import java.util.*;
/** Exact original matrix bytes, current spouse and no silent saved policy adoption. */
public final class PcDuelKinshipTest {
 static int checks;static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
 public static void main(String[]args)throws Exception{
  byte[]matrix=Files.readAllBytes(Path.of(args[0]));World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23);check(PcDuelKinship.enabled(w),"ordinary fresh source initialized only by explicit new-game loader");w.extensions.put(PcDuelKinship.NAMESPACE,null);byte[]before=SaveCodec.encode(w);check(!PcDuelKinship.enabled(w),"explicit absent prior policy remains absent");PcDuelKinship.initialize(w,matrix,"d8cf6789d45f96bfbe77269c36e747499bf0e862f63906918b6fe2d9727704ce");byte[]saved=SaveCodec.encode(w);var namespaceBytes=new ByteArrayOutputStream();w.extensions.write(new DataOutputStream(namespaceBytes));var namespaces=new DataInputStream(new ByteArrayInputStream(namespaceBytes.toByteArray()));namespaces.readInt();int count=namespaces.readInt();check(count<32,"fresh source retains explicit campaign capability namespace headroom");System.out.println("Fresh source namespace count with kinship "+count);
  for(int own=0;own<670;own++)for(int target=0;target<670;target++)check(PcDuelKinship.classifier(w,own,target)==matrix[own*670+target],"every original48d3b0 byte");
  World copy=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(copy)),"complete matrix/source World/both RNG save exact");
  var facts=PcDuelSourceFacts.saved(copy);int[]nativeIds={116,163,195,222,658,590},ids=new int[6];for(int i=0;i<6;i++){final int n=nativeIds[i];ids[i]=facts.values().stream().filter(f->f.nativeId==n).findFirst().orElseThrow().officerId;}byte[]query=SaveCodec.encode(copy);var relations=PcDuelKinship.terminal(copy,ids);for(int i=0;i<6;i++)for(int j=0;j<6;j++){int spouse=copy.relations.spouse(ids[i]);var spouseFact=facts.get(spouse);boolean expected=matrix[nativeIds[i]*670+nativeIds[j]]>=0||spouseFact!=null&&matrix[spouseFact.nativeId*670+nativeIds[j]]>=0;check(relations[i][j]==expected,"original blood plus current saved spouse classifier");}if(args.length>1){String start=Files.readAllLines(Path.of(args[1])).stream().filter(line->line.startsWith("START\t")).findFirst().orElseThrow();String[]fields=start.split("\t"),original=fields[9].split(","),actors=fields[7].split(",");for(int i=0;i<6;i++){check(Integer.parseInt(actors[i].split(":")[0])==nativeIds[i],"original source stable native crew");for(int j=0;j<6;j++)check(relations[i][j]==original[i*6+j].equals("1"),"exact original48d720 terminal getter result");}}
  check(Arrays.equals(query,SaveCodec.encode(copy)),"relationship binding leaves complete World/both RNG unchanged");
  copy.extensions.put(PcDuelKinship.NAMESPACE,new byte[]{1,2,3,4});byte[]opaque=SaveCodec.encode(copy);check(!PcDuelKinship.enabled(copy)&&Arrays.equals(opaque,SaveCodec.encode(SaveCodec.decode(opaque))),"opaque future strategy inert");copy.extensions.put(PcDuelKinship.NAMESPACE,new byte[]{0x50,0x44,0x4b,0x31});boolean rejected=false;try{SaveCodec.encode(copy);}catch(IOException e){rejected=true;}check(rejected,"known malformed policy rejects");
  check(Arrays.equals(before,SaveCodec.encode(SaveCodec.decode(before))),"absence old strategy unchanged no refill");System.out.println("PASS original kinship saved/current relation "+checks+" checks; source0 only, full normal native Duel/APK remains pending");
 }
}
