package game.sanguo.core;
import java.util.*;
/** Original source0 full4a93b0/4a5d90 district receipt:440 -> Army5,
 * Army6 successor436. Declared units, not ordinary APK admission proof. */
public final class PcDuelDistrictCaptureTest {
    static int checks;static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    public static void main(String[]args)throws Exception {
        World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,3,23);var facts=PcDuelSourceFacts.saved(w);int target=facts.values().stream().filter(f->f.nativeId==440).findFirst().orElseThrow().officerId;int victor=facts.values().stream().filter(f->f.nativeId==558).findFirst().orElseThrow().officerId;
        var data=PcGovernorPolicy.data(w);int army=data.assignments.get(target).army;check(army==6&&data.armyLeaders.get(army)==440&&w.officer(target).role==Strategy.Role.DISTRICT,"actual source0 district leader440/army6");check(PcArmyActionPolicy.primaryArmy(w,w.officer(target).owner)==5,"original old-owner first army5 independent of victor");
        Hex first=null;outer:for(int q=0;q<w.width;q++)for(int r=0;r<w.height;r++){Hex h=new Hex(q,r),next=new Hex(q+1,r);if(w.inside(next)&&w.cost(h,World.Weapon.SWORD)>0&&w.cost(next,World.Weapon.SWORD)>0&&!w.army.water(h)&&!w.army.water(next)&&w.cityAt(h)==null&&w.cityAt(next)==null){first=h;break outer;}}
        for(int side=0;side<2;side++){int id=side==0?target:victor;var person=w.officer(id);var home=w.city(person.cityId);var unit=new World.Unit(side+1,person.owner,id,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,10000);unit.gold=997;w.units.add(unit);w.strategy.releaseGovernor(id);person.unitId=unit.id;person.cityId=-1;w.districts.deployed(home.id,unit);PcGovernorPolicy.deployed(w,unit,home);}w.nextUnitId=3;w.governance.reconcile(false);
        byte[]before=SaveCodec.encode(w);int rng=PcNativeDebatePolicy.seed(w);long strategic=w.strategy.getRandomState();var loser=w.unit(1);var winner=w.unit(2);World cityless=SaveCodec.decode(before);var unknown=PcGovernorPolicy.data(cityless);for(var site:cityless.cities)if(site.kind==World.SiteKind.CITY&&unknown.siteArmies.getOrDefault(site.id,-1)==army)unknown.siteArmies.put(site.id,-1);PcGovernorPolicy.write(cityless,unknown);byte[]unsupported=SaveCodec.encode(cityless);boolean rejected=false;try{PcDuelCapture.validate(cityless,cityless.unit(2),cityless.unit(1),target);}catch(java.io.IOException e){rejected=e.getMessage().contains("无城市");}check(rejected&&Arrays.equals(unsupported,SaveCodec.encode(cityless)),"original4b9550 requires CITY and people; gate/port/people alone cannot guess merge");
        PcDuelCapture.validate(w,winner,loser,target);check(Arrays.equals(before,SaveCodec.encode(w)),"district preview wholeWorld/allRNG pure");PcDuelCapture.apply(w,winner,loser,target);
        byte[]raw;try(var input=PcDuelDistrictCaptureTest.class.getResourceAsStream("/pc-duel/district-capture-source0.json")){check(input!=null,"original callback fixture available");raw=input.readAllBytes();}check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(raw)).equals("d02a04d295a3d11ef2d5fdda0f2877ae69b72cd282f8f57b2a87d970ce6748e7"),"full original callback receipt SHA");var receipt=MapJson.object(MapJson.parse(raw));check(receipt.get("exeSha").equals(PcScenarioIdentity.EXE_SHA)&&MapJson.integer(receipt.get("oldOwner"),0,41)==28&&MapJson.integer(receipt.get("oldPrimaryArmy"),0,46)==5,"old-force primary exactly original getter");
        data=PcGovernorPolicy.data(w);for(var row:MapJson.array(receipt.get("sitesAfter"))){var site=MapJson.object(row);if(MapJson.integer(site.get("army"),-1,46)!=6)continue;int nativeSite=MapJson.integer(site.get("nativeSite"),0,86),expected=MapJson.integer(site.get("governor"),-1,1099);var joined=data.source.sites.values().stream().filter(c->c.nativeId==nativeSite).findFirst().orElseThrow();int governor=w.city(joined.id).governorId;check((governor<0?-1:facts.get(governor).nativeId)==expected,"original all87 callback affected Army6 site "+nativeSite+" governor "+expected);}
        check(data.assignments.get(target).army==5&&data.armyLeaders.get(6)==436,"original first army reassignment then native436 succession");int next=facts.values().stream().filter(f->f.nativeId==436).findFirst().orElseThrow().officerId;check(w.officer(next).role==Strategy.Role.DISTRICT&&w.officer(target).role==Strategy.Role.OFFICER,"current new commander and captive underlying role");check(w.government.captive(target)&&w.officer(target).owner==loser.owner&&w.government.prisoner(target).unitId==winner.id,"original old allegiance and victor escort distinct");check(PcNativeDebatePolicy.seed(w)==rng&&w.strategy.getRandomState()==strategic,"complete district capture no RNG");byte[]after=SaveCodec.encode(w);check(Arrays.equals(after,SaveCodec.encode(SaveCodec.decode(after))),"complete army/role/escort/governor/RNG cold exact");System.out.println("PASS source0 district capture "+checks+" checks; declared units/full original receipt, ordinary APK and empty-army/ruler remain pending");
    }
}
