package game.sanguo.core;
import java.nio.*;import java.nio.file.*;import java.util.*;
/** Full original natural source493 execution/child133 succession callback. */
public final class PcRulerParentExecutionTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static int n(Map<String,Object>m,String k){return ((Number)m.get(k)).intValue();}
 public static void main(String[]args)throws Exception {
  String text=Files.readString(Path.of(args[0]));var large=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);var r=MapJson.object(MapJson.parse(large.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8)));check(Boolean.TRUE.equals(r.get("wholeWorldAndRngRestored"))&&MapJson.array(r.get("omittedPresentation")).isEmpty(),"full original callback no omissions");
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,24,new PcDuelOptions(0,0,0));Map<Integer,Integer>ids=new HashMap<>();for(var f:PcDuelSourceFacts.saved(w).values())ids.put(f.nativeId,f.officerId);int dead=ids.get(493),child=ids.get(133),victor=ids.get(365);check(w.relations.parent(child,false)==dead,"actual current child relation");int childRefusal=PcRecruitmentBanPolicy.current(w,child).ruler;var item=w.treasures.item("item-000");check(item!=null&&w.treasures.held(dead).contains(item),"actual original helditem0");
  Hex first=null;outer:for(int q=0;q<w.width;q++)for(int y=0;y<w.height;y++){Hex a=new Hex(q,y),b=new Hex(q+1,y);if(w.inside(b)&&w.cost(a,World.Weapon.SWORD)>0&&w.cost(b,World.Weapon.SWORD)>0&&!w.army.water(a)&&!w.army.water(b)&&w.cityAt(a)==null&&w.cityAt(b)==null){first=a;break outer;}}
  for(int side=0;side<2;side++){var o=w.officer(side==0?victor:dead);var home=w.city(o.cityId);var u=new World.Unit(side+1,o.owner,o.id,World.Weapon.SWORD,new Hex(first.q+side,first.r),5000,17000);u.gold=997;u.acted=true;u.deputies=side==0?new int[]{ids.get(116),ids.get(466)}:new int[0];w.units.add(u);for(var p:w.army.crew(u)){w.strategy.releaseGovernor(p.id);p.unitId=u.id;p.cityId=-1;p.acted=true;}w.districts.deployed(home.id,u);PcGovernorPolicy.deployed(w,u,home);}w.nextUnitId=3;w.governance.reconcile(false);byte[]before=SaveCodec.encode(w);PcDuelExecution.validate(w,w.unit(1),w.unit(2),dead);check(Arrays.equals(before,SaveCodec.encode(w)),"parent death preview fullWorld/RNG pure");PcDuelHealthPolicy.writeDuelResult(w,Map.of(dead,1));PcDuelExecution.apply(w,w.unit(1),w.unit(2),dead);
  check(w.life.state(dead)==Lifecycle.State.DEAD&&w.unit(2)==null&&w.loyalty.ruler(5).id==child,"actual parent death/child heir/singleunit deletion");check(w.relations.parent(child,false)==dead&&PcRecruitmentBanPolicy.current(w,child).ruler==childRefusal,"original parent graph/refusal preserved without invented revenge");check(w.treasures.held(victor).stream().anyMatch(x->x.definition.id.equals("item-000"))&&w.treasures.held(dead).isEmpty(),"original item0 owner493->365");
  for(Object value:MapJson.array(MapJson.object(r.get("administrativeAfter")).get("people"))){var row=MapJson.object(value);int nativeId=n(row,"nativeId");if(!ids.containsKey(nativeId))continue;int id=ids.get(nativeId);var b=ByteBuffer.wrap(HexFormat.of().parseHex((String)row.get("hex"))).order(ByteOrder.LITTLE_ENDIAN);check(PcGovernorPolicy.data(w).assignments.get(id).army==b.getInt(0x94),"all original postdeath currentarmy "+nativeId);if(w.officer(id).owner==5&&w.life.present(id))check(PcDuelRawLoyalty.current(w,id)==(b.get(0xac)&255),"all original serving rawloyalty "+nativeId);}
  byte[]save=SaveCodec.encode(w);check(Arrays.equals(save,SaveCodec.encode(SaveCodec.decode(save))),"full child succession World/RNG cold exact");System.out.println("PASS original parent execution "+checks+" checks; ordinary deployment/currentAPK and other inheritanceitems pending");
 }
}
