package game.sanguo.core;
import java.nio.*;import java.nio.file.*;import java.util.*;
/** Full original natural duel execution callback, not an isolated formula. */
public final class PcRulerCoronationLoyaltyTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static int n(Map<String,Object>m,String k){return ((Number)m.get(k)).intValue();}
 public static void main(String[]args)throws Exception {
  String text=Files.readString(Path.of(args[0]));var large=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);var receipt=MapJson.object(MapJson.parse(large.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8)));
  check(Boolean.TRUE.equals(receipt.get("wholeWorldAndRngRestored"))&&MapJson.array(receipt.get("omittedPresentation")).isEmpty(),"complete unskipped original callback");check(n(receipt,"rngBefore")==n(receipt,"rngAfter"),"original callback no random draw");
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,24,new PcDuelOptions(0,0,0));Map<Integer,Integer>ids=new HashMap<>();for(var f:PcDuelSourceFacts.saved(w).values())ids.put(f.nativeId,f.officerId);
  byte[]before=SaveCodec.encode(w);var administration=PcRulerCoronation.preview(w,ids.get(517));var succession=administration.succession;check(succession.selected==ids.get(109),"actual selected current native109");check(administration.primaryArmy==1&&administration.heirArmy==1&&administration.heirNative==109,"current original primary/heir army and identity");check(PcGovernorPolicy.data(w).source.sites.get(administration.homeCity).nativeId==21,"current original administrative home21");var plan=administration.loyalty;Set<Integer>observed=new HashSet<>();
  var after=MapJson.object(receipt.get("administrativeAfter"));Map<Integer,byte[]>people=new HashMap<>();for(Object value:MapJson.array(after.get("people"))){var row=MapJson.object(value);people.put(n(row,"nativeId"),HexFormat.of().parseHex((String)row.get("hex")));}
  for(Object value:MapJson.array(receipt.get("entryFacts"))){var entry=MapJson.object(value);if(!"0x4a75a0".equals(entry.get("address")))continue;int nativeId=n(entry,"personNative"),id=ids.get(nativeId);check(n(entry,"weighted")==1,"original weighted flag");check(observed.add(id),"each original roster entry once");if(entry.containsKey("resultRaw"))check(plan.get(id)!=null&&plan.get(id)==n(entry,"resultRaw"),"original temporary weighted setter result native "+nativeId);if(nativeId!=517)check(plan.get(id)!=null&&plan.get(id)==(people.get(nativeId)[0xac]&255),"full callback current raw loyalty native "+nativeId);else check((people.get(nativeId)[0xac]&255)==0&&plan.containsKey(id),"departed intermediate recomputation precedes terminal raw0");}
  check(observed.equals(plan.keySet()),"exact full original serving roster");check(!plan.containsKey(ids.get(109))&&plan.containsKey(ids.get(517)),"original excludes heir but includes temporarily demoted departing ruler");check(Arrays.equals(before,SaveCodec.encode(w)),"plan fullWorld/allRNG pure");World cold=SaveCodec.decode(before);check(plan.equals(PcRulerCoronation.loyalty(cold,PcRulerSuccession.preview(cold,ids.get(517)))),"cold current plan exact");
  var jail=cold.cities.stream().filter(c->c.owner==2).findFirst().orElseThrow();cold.government.capture(cold.officer(ids.get(14)),jail);byte[]captured=SaveCodec.encode(cold);check(!PcRulerCoronation.preview(cold,ids.get(517)).loyalty.containsKey(ids.get(14)),"actual current capture removes original serving roster entry");check(Arrays.equals(captured,SaveCodec.encode(cold)),"captured plan pure");
  World changed=SaveCodec.decode(before);PcDuelRawLoyalty.invalidate(changed,ids.get(313));byte[]unknown=SaveCodec.encode(changed);boolean refused=false;try{PcRulerCoronation.preview(changed,ids.get(517));}catch(java.io.IOException e){refused=true;}check(refused&&Arrays.equals(unknown,SaveCodec.encode(changed)),"unknown current raw loyalty refuses byte-pure instead of reconstructing source values");
  System.out.println("PASS current coronation weighted loyalty "+checks+" checks; production administrative writes/normal command/APK pending");
 }
}
