package game.sanguo.core;
import java.nio.*;import java.nio.file.*;import java.util.*;
/** Complete original deployed-heir crown receipt versus production plan.
 * Declared crew/deployment is not normal menu or APK acceptance. */
public final class PcRulerDeployedHeirTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static World opening()throws Exception{return PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,4,24,new PcDuelOptions(0,0,0));}
 static void formation(World w,Map<Integer,Integer>ids,List<Object>crew)throws Exception {
  Hex land=PcDuelSwornPolicyTest.land(w);int leader=ids.get(MapJson.integer(crew.get(0),0,1099));PcDuelSwornPolicyTest.deploy(w,leader,1,land);var unit=w.unit(1);int[] deputies=new int[crew.size()-1];
  for(int k=1;k<crew.size();k++){int id=ids.get(MapJson.integer(crew.get(k),0,1099));var o=w.officer(id);w.strategy.releaseGovernor(id);o.unitId=1;o.cityId=-1;o.acted=true;deputies[k-1]=id;}unit.deputies=deputies;w.governance.reconcile(false);
 }
 public static void main(String[]args)throws Exception {
  var receipt=MapJson.object(MapJson.parse(Files.readAllBytes(Path.of(args[0]))));check(Boolean.TRUE.equals(receipt.get("wholeWorldAndRngRestored")),"original World/dualRNG restored");check(PcScenarioIdentity.EXE_SHA.equals(receipt.get("exeSha"))&&HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(Path.of((String)receipt.get("originalReceiptPath"))))).equals(receipt.get("originalReceiptSha")),"full original receipt SHA linked without relaxing bounded JSON parser");
  for(Object entry:MapJson.array(receipt.get("rows"))){var row=MapJson.object(entry);World w=opening();var ids=PcDuelSwornPolicyTest.ids(w);formation(w,ids,MapJson.array(row.get("crewBefore")));w.unit(1).troops=MapJson.integer(row.get("declaredTroops"),1,65535);w.unit(1).energy=MapJson.integer(row.get("declaredEnergy"),0,255);int dead=ids.get(614),heir=ids.get(98);var unit=w.unit(1);Hex position=unit.hex;boolean savableFixture=unit.troops<=18000&&unit.energy<=w.campaign.energyCap(unit.owner);byte[] before=savableFixture?SaveCodec.encode(w):null;long rng=w.strategy.getRandomState();int nativeRng=PcNativeDebatePolicy.seed(w);var plan=PcRulerCoronation.validateExecution(w,dead,heir);if(savableFixture)check(Arrays.equals(before,SaveCodec.encode(w)),"complete deployed-heir preview World/RNG pure");PcRulerCoronation.apply(w,plan);
   byte[] original=HexFormat.of().parseHex((String)MapJson.object(row.get("after")).get("unitHex"));var b=ByteBuffer.wrap(original).order(ByteOrder.LITTLE_ENDIAN);check(unit.officerId==ids.get(b.getInt(12)),"original actual unit leader");List<Integer> deputies=new ArrayList<>();for(int k=0;k<2;k++)if(b.getInt(16+k*4)>=0)deputies.add(ids.get(b.getInt(16+k*4)));check(Arrays.equals(unit.deputies,deputies.stream().mapToInt(Integer::intValue).toArray()),"exact original deputy order");check(unit.troops==(b.getShort(24)&65535)&&unit.energy==(original[26]&255)&&unit.gold==997&&unit.food==17000&&unit.hex.equals(position)&&unit.acted,"original troops/energy/cargo/current position/action retained");check(w.city(plan.homeCity).governorId==heir&&MapJson.integer(MapJson.object(MapJson.array(MapJson.object(row.get("after")).get("sites")).get(PcGovernorPolicy.data(w).source.sites.get(plan.homeCity).nativeId)).get("governorRaw"),-1,1099)==98,"original deployed administrative governor appointment");check(w.officer(heir).role==Strategy.Role.RULER&&w.officer(heir).unitId==1&&w.officer(heir).cityId==-1,"deployed heir is ruler without city teleport");
   var people=MapJson.array(MapJson.object(row.get("after")).get("people"));for(var e:ids.entrySet())if(w.officer(e.getValue()).owner==4){var person=MapJson.object(people.get(e.getKey()));check(MapJson.integer(person.get("nativeId"),0,1099)==e.getKey()&&PcDuelRawLoyalty.current(w,e.getValue())==MapJson.integer(person.get("rawLoyalty"),0,255),"all force4 original crown raw loyalty "+e.getKey());}
   check(rng==w.strategy.getRandomState()&&nativeRng==PcNativeDebatePolicy.seed(w),"promotion does not redraw RNG");if(!savableFixture){System.out.println("Original resource clamp comparison only: declared outside historical engine Save bounds; no Save/normal-flow claim");continue;}byte[] saved=SaveCodec.encode(w);w=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(w)),"full promoted crew/administration/current World cold exact");
   w=opening();ids=PcDuelSwornPolicyTest.ids(w);formation(w,ids,MapJson.array(row.get("crewBefore")));w.unit(1).troops=MapJson.integer(row.get("declaredTroops"),1,65535);w.unit(1).energy=MapJson.integer(row.get("declaredEnergy"),0,255);Hex h=w.unit(1).hex;PcDuelSwornPolicyTest.deploy(w,ids.get(365),2,new Hex(h.q+1,h.r));PcDuelSwornPolicyTest.deploy(w,ids.get(614),3,new Hex(h.q+2,h.r));dead=ids.get(614);heir=ids.get(98);before=SaveCodec.encode(w);PcDuelExecution.validate(w,w.unit(2),w.unit(3),dead,heir);check(Arrays.equals(before,SaveCodec.encode(w)),"actual execution with deployed chosen heir preview pure");PcDuelHealthPolicy.writeDuelResult(w,Map.of(dead,1));PcDuelExecution.apply(w,w.unit(2),w.unit(3),dead,heir);check(w.life.state(dead)==Lifecycle.State.DEAD&&w.unit(3)==null&&w.loyalty.ruler(4).id==heir&&w.unit(1).officerId==heir&&w.city(PcPersonnelReturnRules.projectSite(w,PcGovernorPolicy.data(w).assignments.get(heir).home)).governorId==heir,"full production death/crown keeps deployed ruler unit");saved=SaveCodec.encode(w);w=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(w)),"actual full death/crown cold exact");
   for(int t=0;t<4;t++){check(w.nextTurn().ok,"complete campaign turn after deployed crown");saved=SaveCodec.encode(w);w=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(w)),"complete turn World/dualRNG cold exact");}
  }
  World probe=opening();var probeIds=PcDuelSwornPolicyTest.ids(probe);formation(probe,probeIds,List.of(432,98));int promoted=probeIds.get(98);var proof=PcRulerCoronation.validateExecution(probe,probeIds.get(614),promoted);PcRulerCoronation.apply(probe,proof);check(PcGovernorPolicy.deployedRulerGovernor(probe,probe.officer(promoted),probe.city(proof.homeCity)),"exact connected remote ruler appointment");var other=probe.cities.stream().filter(c->c.id!=proof.homeCity).findFirst().orElseThrow();check(!PcGovernorPolicy.deployedRulerGovernor(probe,probe.officer(promoted),other),"remote appointment cannot leak to another site");probe.officer(promoted).role=Strategy.Role.OFFICER;boolean invalid=false;try{SaveCodec.encode(probe);}catch(java.io.IOException e){invalid=true;}check(invalid,"nonruler remote governor cannot save");
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));byte[] oldBytes=SaveCodec.encode(old);check(!PcGovernorPolicy.deployedRulerGovernor(old,old.loyalty.ruler(old.player),old.cities.get(0))&&Arrays.equals(oldBytes,SaveCodec.encode(old)),"genuine39 cannot adopt deployed-crown capability, byte pure");
  System.out.println("PASS original deployed-heir crown "+checks+" checks; normal deployment/typed chain/menu/APK separate");
 }
}
