package game.sanguo.core;
import java.nio.*;import java.nio.file.*;import java.util.*;
/** Declared valid original heir440, full original4b78f0/4bd3b0 receipt. */
public final class PcRulerCrossArmyTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static int n(Map<String,Object>m,String k){return ((Number)m.get(k)).intValue();}
 static ByteBuffer bytes(Map<String,Object>r){return ByteBuffer.wrap(HexFormat.of().parseHex((String)r.get("hex"))).order(ByteOrder.LITTLE_ENDIAN);}
 public static void main(String[]args)throws Exception {
  String text=Files.readString(Path.of(args[0]));var large=java.util.regex.Pattern.compile("(?<=[\\s:\\[,])\\d{10,}(?=\\s*[,}\\]])").matcher(text);var receipt=MapJson.object(MapJson.parse(large.replaceAll(m->Integer.toString((int)Long.parseLong(m.group()))).getBytes(java.nio.charset.StandardCharsets.UTF_8)));check(Boolean.TRUE.equals(receipt.get("wholeWorldAndRngRestored"))&&n(receipt,"rngBefore")==n(receipt,"rngAfter"),"complete original noRNG callback");
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,23,new PcDuelOptions(0,0,0));Map<Integer,Integer>ids=new HashMap<>();for(var f:PcDuelSourceFacts.saved(w).values())ids.put(f.nativeId,f.officerId);
  byte[]initial=SaveCodec.encode(w);Map<Integer,Integer>governors=new HashMap<>();for(var c:w.cities)governors.put(c.id,c.governorId);Map<Integer,ByteBuffer>nativeSitesBefore=new HashMap<>();Map<Integer,Strategy.Role>roles=new HashMap<>();for(var o:w.officers)roles.put(o.id,o.role);var before=MapJson.object(receipt.get("before"));Map<Integer,ByteBuffer>nativeBefore=new HashMap<>();for(Object value:MapJson.array(before.get("people"))){var row=MapJson.object(value);nativeBefore.put(n(row,"nativeId"),bytes(row));}for(Object value:MapJson.array(before.get("sites"))){var row=MapJson.object(value);nativeSitesBefore.put(n(row,"nativeId"),bytes(row));}var candidates=PcRulerSuccession.preview(w,ids.get(403));check(candidates.selected==ids.get(435),"original AI choice remains435");var plan=PcRulerCoronation.preview(w,candidates.choose(ids.get(440)));PcRulerCoronation.validateMerge(w,plan);check(Arrays.equals(initial,SaveCodec.encode(w)),"declared valid heir/current merge preview fullWorld pure");int primary=PcArmyActionPolicy.points(w,5);long random=w.strategy.getRandomState();int nativeRandom=PcNativeDebatePolicy.seed(w);PcRulerCoronation.apply(w,plan);var data=PcGovernorPolicy.data(w);var after=MapJson.object(receipt.get("after"));
  check(data.mergedArmies.get(6)==5&&data.armyLeaders.get(6)==-1&&data.armyLeaders.get(5)==440,"original current army6inactive and primary leader440");check(PcArmyActionPolicy.points(w,6)==0&&PcArmyActionPolicy.points(w,5)==primary,"original old budget clears without transferring");
  for(Object value:MapJson.array(after.get("people"))){var row=MapJson.object(value);int nativeId=n(row,"nativeId");if(!ids.containsKey(nativeId))continue;int id=ids.get(nativeId);var b=bytes(row);var o=w.officer(id);check(data.assignments.get(id).army==b.getInt(0x94),"complete original current person army "+nativeId);if(o.owner==28&&w.life.present(id)){check(PcDuelRawLoyalty.current(w,id)==(b.get(0xac)&255),"complete original weighted raw "+nativeId);int status=o.role==Strategy.Role.RULER?0:o.role==Strategy.Role.DISTRICT?1:o.role==Strategy.Role.GOVERNOR?2:3;if(nativeBefore.get(nativeId).getInt(0xa0)!=b.getInt(0xa0)||o.role!=roles.get(id))check(status==b.getInt(0xa0),"actual original changed role "+nativeId);else check(o.role==roles.get(id),"unchanged current role preserved "+nativeId);}}
  for(Object value:MapJson.array(after.get("sites"))){var row=MapJson.object(value);int nativeId=n(row,"nativeId");var s=data.source.sites.values().stream().filter(x->x.nativeId==nativeId).findFirst().orElseThrow();var b=bytes(row);int army=n(row,"armyRaw");if(nativeId<42)check(army==b.getInt(0x38),"original city domain and property wrapper agree "+nativeId);check(data.siteArmies.get(s.id)==army,"complete original site army "+nativeId);if(nativeId<42){int governor=b.getInt(0x34);if(nativeSitesBefore.get(nativeId).getInt(0x34)!=governor||w.city(s.id).governorId!=governors.get(s.id))check(w.city(s.id).governorId==ids.getOrDefault(governor,-1),"original changed city governor "+nativeId);else check(w.city(s.id).governorId==governors.get(s.id),"unchanged current governor preserved "+nativeId);}}
  check(w.strategy.getRandomState()==random&&PcNativeDebatePolicy.seed(w)==nativeRandom,"coronation allRNG unchanged");byte[]save=SaveCodec.encode(w);check(Arrays.equals(save,SaveCodec.encode(SaveCodec.decode(save))),"complete current army/source/coronation cold exact");
  System.out.println("PASS original current cross-army coronation "+checks+" checks; declared heir input, death/human selection/normal APK pending");
 }
}
