package game.sanguo.core;
import java.util.*;import java.nio.file.*;
/** Normal source SEARCH and real choices/cards/save/turn. No forced terminal. */
public final class PcSearchOrdinaryTest {
 static int checks;static void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
 static World.Officer person(World w,int n)throws Exception{return PcDebateOrdinaryCampaignTest.person(w,n);}
 static World start(int actorNative,long seed)throws Exception {
  World w=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,2,seed);if(!PcSearchPolicy.enabled(w))PcSearchPolicy.initializeOpening(w);World.Officer actor=person(w,actorNative);
  byte[]before=SaveCodec.encode(w);var preview=w.strategy.previewCityAction(CityActionPlan.Operation.SEARCH,actor.cityId,actor.id,new int[0]);check(preview.allowed()&&preview.actionPointsCost==20,"normal source SEARCH preview20");check(Arrays.equals(before,SaveCodec.encode(w)),"preview allWorld/RNG pure");
  int ap=w.cityActionPoints(w.city(actor.cityId)),gold=w.city(actor.cityId).gold,merit=w.government.merit(actor.id);var result=w.strategy.search(actor.cityId,actor.id);check(result.ok,"ordinary SEARCH accepted "+result.message);check(w.contests.current()!=null&&w.contests.current().searchChoice(),"ordinary source discovery pending choice "+actorNative+" "+result.message);check(w.contests.current().rightRef==person(w,658).id,"actual native selected target658 stableID");check(w.cityActionPoints(w.city(actor.cityId))==ap&&w.city(actor.cityId).gold==gold&&w.government.merit(actor.id)==merit&&!actor.acted,"first dialog no cost/reward/action yet");check(w.campaign.points(w.player)==0,"original first dialogue no TP yet");check(!person(w,658).acted&&w.life.present(person(w,658).id),"original discovery state only; target action untouched");
  byte[]pending=SaveCodec.encode(w);w=SaveCodec.decode(pending);check(Arrays.equals(pending,SaveCodec.encode(w)),"whole pendingchoice/save/RNG exact");check(!w.nextTurn().ok,"pending choice blocks turn");return w;
 }
 public static void main(String[]args)throws Exception {
  int[] actors={198,251,377,466},chances={25,23,22,32};
  for(int i=0;i<actors.length;i++){
   World w=start(actors[i],23);var c=w.contests.current();World.Officer actor=w.officer(c.leftRef),target=w.officer(c.rightRef);check(PcSearchPolicy.probability(w,actor,target)==chances[i],"actual original newly discovered probability "+actors[i]+"="+PcSearchPolicy.probability(w,actor,target));int ap=w.cityActionPoints(w.city(c.city)),merit=w.government.merit(actor.id);int[]xp=actor.abilityProfile.experience.clone();
   check(w.contests.searchChoice(c.id,c.revision,false).ok,"normal human decline search recruit");check(!w.contests.busy()&&w.cityActionPoints(w.city(c.city))==ap-20&&w.government.merit(actor.id)==merit+3&&w.campaign.points(w.player)==10,"original decline AP20/merit3/actualTP10");check(Arrays.equals(xp,actor.abilityProfile.experience)&&actor.acted&&target.owner<0&&!target.acted,"decline noXP/target remains free");byte[]done=SaveCodec.encode(w);check(Arrays.equals(done,SaveCodec.encode(SaveCodec.decode(done))),"full decline save");check(w.nextTurn().ok,"normal full turn after decline");
   w=start(actors[i],23);c=w.contests.current();int id=c.id,revision=c.revision;check(w.contests.searchChoice(id,revision,true).ok,"normal consent attempts recruit");check(w.contests.searchChoicePhase()==2&&w.campaign.points(w.player)==10,"native failed roll -> optional debate");byte[]choice=SaveCodec.encode(w);check(!w.contests.searchChoice(id,revision,true).ok&&Arrays.equals(choice,SaveCodec.encode(w)),"stale/double consent pure");w=SaveCodec.decode(choice);c=w.contests.current();check(w.contests.searchChoice(c.id,c.revision,false).ok,"normal decline optionaldebate");check(!w.contests.busy()&&person(w,658).owner<0&&w.government.merit(person(w,actors[i]).id)==(actors[i]==466?1100:100),"original failed recruitment callback100 merit");check(w.nextTurn().ok,"full turn after declined debate");
  }
  World second=PcScenarioCatalog.load(PcScenarioCatalog.all().get(0).identity.scenarioId,29,23);World.Officer secondActor=person(second,430);int secondAp=second.actionPoints[29];check(second.strategy.search(secondActor.cityId,secondActor.id).ok&&second.contests.current().rightRef==person(second,590).id,"independent original force29 topSEARCH430 selects590");check(PcSearchPolicy.probability(second,secondActor,person(second,590))==31,"original independent force29 native5c51c0 chance31");var sc=second.contests.current();check(second.contests.searchChoice(sc.id,sc.revision,true).ok&&second.contests.searchChoicePhase()==2,"original430/590 failed75 roll, threshold106 optionaldebate");sc=second.contests.current();check(second.contests.searchChoice(sc.id,sc.revision,false).ok&&second.actionPoints[29]==secondAp-20,"independent force29 native failed callbackAP20");check(second.nextTurn().ok,"independent ordinary fullturn");
  int wins=0,losses=0;for(int seed=1;seed<=40&&(wins==0||losses==0);seed++){World w=start(seed%2==0?198:466,seed);var c=w.contests.current();check(w.contests.searchChoice(c.id,c.revision,true).ok,"consent");c=w.contests.current();check(w.contests.searchChoice(c.id,c.revision,true).ok&&w.contests.current().nativeDebate!=null,"normal SEARCH enters native human debate, zero extra gold");int won=play(w,seed);wins+=won;losses+=1-won;System.out.println("actual search actor="+(seed%2==0?198:466)+" seed="+seed+" won="+won);}check(wins>0&&losses>0,"ordinary search natural human win/loss wins="+wins+" losses="+losses);
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));check(!PcSearchPolicy.enabled(old)&&old.extensions.get(PcSearchPolicy.NAMESPACE)==null,"real old39 no adoption");byte[]raw=SaveCodec.encode(old);check(Arrays.equals(raw,SaveCodec.encode(SaveCodec.decode(raw))),"real old39 full model/all RNG exact");old.extensions.put(PcSearchPolicy.NAMESPACE,new byte[]{9,8,7});raw=SaveCodec.encode(old);check(!PcSearchPolicy.enabled(old)&&Arrays.equals(raw,SaveCodec.encode(SaveCodec.decode(raw))),"opaque extension unchanged");
  System.out.println("PASS ordinary original discovery/consent/optional nativeDebate "+checks+" checks wins="+wins+" losses="+losses+"; no-discovery/treasure/special gates declared engineering/unknown; actual APK separate");
 }
 static int play(World w,int strategy)throws Exception {
  int targetId=w.contests.searchTargetId(),owner=w.player;java.util.Random decisions=new java.util.Random(strategy);int moves=0;
  while(w.contests.busy()&&moves++<400){var s=w.contests.current();var d=s.nativeDebate;if(d.waitingMercy()){check(w.contests.finishDebate(s.id,s.revision,true).ok,"normal actual mercy/finalcallback");continue;}if(d.model.phase==9){check(w.contests.finishDebate(s.id,s.revision,false).ok,"normal once-only native finalcallback");continue;}
   check(d.waitingCard(),"normal human boundary");List<Integer> legal=new ArrayList<>();for(int slot=0;slot<d.model.state.left.slots;slot++)if(d.cardError(slot)==null)legal.add(slot);int slot=legal.get(decisions.nextInt(legal.size()));check(w.contests.debateCard(s.id,s.revision,slot).ok,"legal human displayed card");byte[]raw=SaveCodec.encode(w);w=SaveCodec.decode(raw);check(Arrays.equals(raw,SaveCodec.encode(w)),"full source/native model/all RNG each input reload");
  }
  check(!w.contests.busy(),"normal search native terminal released");int won=w.officer(targetId).owner==owner?1:0;check(w.nextTurn().ok,"normal full turn after native callback");byte[]done=SaveCodec.encode(w);check(Arrays.equals(done,SaveCodec.encode(SaveCodec.decode(done))),"normal fullturn/save/allRNG");return won;
 }
}
