package game.sanguo.core;
import java.nio.file.*;import java.util.*;
/** Source actual serialized flags and original source7 transfer, not full GUI. */
public final class PcSourceOpeningOptionsTest {
 static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 public static void main(String[]args)throws Exception {
  byte[] raw=Files.readAllBytes(Path.of("out/session-b/source-flag-header-v1.json"));check(PcCommandCapacityPolicy.hex(java.security.MessageDigest.getInstance("SHA-256").digest(raw)).equals("692391c85748e5da8d9ac1ae390ecf8e649ca2ba320ca4042048f929af57d3a0"),"original16 flag receipt");var receipt=MapJson.object(MapJson.parse(raw));var catalog=PcScenarioCatalog.all();
  for(Object obj:MapJson.array(receipt.get("rows"))){var row=MapJson.object(obj);String id=(String)row.get("sourceId");var requested=PcDuelOptions.fromMenu(0,2,1);World w=PcScenarioCatalog.load(id,-1,24,requested);var facts=PcSourceOpeningOptions.saved(w);int flag=((Number)row.get("flag18")).intValue();check(facts.flag18==flag&&facts.requested.life==0&&facts.effective.life==(flag==0?0:3),"original per-source effective life override");check(PcDuelOptions.current(w).life==facts.effective.life&&PcDuelOptions.current(w).death==2&&PcDuelOptions.current(w).difficulty==1,"effective policy preserves original difficulty/death");byte[] saved=SaveCodec.encode(w);w=SaveCodec.decode(saved);check(Arrays.equals(saved,SaveCodec.encode(w))&&PcSourceOpeningOptions.saved(w).flag18==flag,"new source/header/request/effect/fullWorld/dualRNG cold exact");byte[] before=SaveCodec.encode(w);PcSourceOpeningOptions.saved(w);check(Arrays.equals(before,SaveCodec.encode(w)),"source/header query pure");}
  World old=SaveCodec.decode(Files.readAllBytes(Path.of("out/session-b/duel-ruler-ai-seed1-nonterminal-v1.sg11")));byte[] saved=SaveCodec.encode(old);check(PcSourceOpeningOptions.saved(old)==null&&Arrays.equals(saved,SaveCodec.encode(old)),"actual old native format5 never gets new source policy");World legacy=SaveCodec.decode(Files.readAllBytes(Path.of("docs/handoff/20261004/session1/batch19-actual-art-mid.sg11")));byte[] canonical=SaveCodec.encode(legacy);check(PcSourceOpeningOptions.saved(legacy)==null&&Arrays.equals(canonical,SaveCodec.encode(legacy)),"actual39 remains absent/read pure");
  World three=PcScenarioCatalog.load(catalog.get(7).identity.scenarioId,-1,24);saved=SaveCodec.encode(three);check(PcSourceOpeningOptions.saved(three)==null&&PcDuelOptions.current(three)==null&&Arrays.equals(saved,SaveCodec.encode(three)),"three-argument behavior unchanged");World historicalNative=PcScenarioCatalog.load(catalog.get(7).identity.scenarioId,-1,24);PcDuelCampaignPolicy.initializeOpening(historicalNative,new PcDuelOptions(0,0,0));PcGovernorPolicy.initializeCurrentArmies(historicalNative);saved=SaveCodec.encode(historicalNative);check(PcSourceOpeningOptions.saved(historicalNative)==null&&PcDuelOptions.current(historicalNative).life==0&&Arrays.equals(saved,SaveCodec.encode(SaveCodec.decode(saved))),"declared prior PDU3 without namespace retains stored0, not claimed genuine archived source7 fixture");
  World wrong=PcScenarioCatalog.load(catalog.get(7).identity.scenarioId,-1,24,new PcDuelOptions(0,0,0));byte[] bytes=wrong.extensions.get(PcSourceOpeningOptions.NAMESPACE).clone();bytes[bytes.length-16+3]=0;wrong.extensions.put(PcSourceOpeningOptions.NAMESPACE,bytes);boolean refused=false;try{SaveCodec.encode(wrong);}catch(java.io.IOException e){refused=true;}check(refused,"corrupt source flag cannot masquerade as compatible override");
  System.out.println("PASS source/header/newgame override "+checks+" checks; GUI/current APK/lifecycle/global startup remain separate");
 }
}
