package game.sanguo.mobile;
import android.app.*;import android.content.Intent;import android.graphics.*;import android.os.*;import android.view.*;import android.view.inspector.WindowInspector;import android.view.accessibility.AccessibilityNodeInfo;import android.widget.*;
import game.sanguo.api.*;import game.sanguo.core.*;
import java.io.*;import java.util.*;import java.util.function.Predicate;

/** Real saved campaign/normal next-turn/save/load/health detail acceptance. */
public final class PcHealthInstrumentation extends Instrumentation {
    private MainActivity activity;private File output;private String evidenceId;private int checks;private final StringBuilder log=new StringBuilder();
    @Override public void onCreate(Bundle args){super.onCreate(args);evidenceId=args.getString("evidenceId","health");if(!evidenceId.matches("[A-Za-z0-9_.-]+"))throw new IllegalArgumentException("Evidence ID");start();}
    private void settle(){runOnMainSync(()->{});SystemClock.sleep(200);}
    private void check(boolean b,String label)throws Exception{if(!b)throw new AssertionError(label);checks++;log.append("PASS ").append(label).append('\n');java.nio.file.Files.write(new File(output,"progress.txt").toPath(),log.toString().getBytes("UTF-8"));}
    private View find(View v,Predicate<View> p){Rect r=new Rect();if(!v.isShown()||!v.getGlobalVisibleRect(r)||r.width()<8||r.height()<8)return null;if(p.test(v))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View x=find(((ViewGroup)v).getChildAt(i),p);if(x!=null)return x;}return null;}
    private View await(Predicate<View> p){long until=SystemClock.uptimeMillis()+30000;while(SystemClock.uptimeMillis()<until){View[] result={null};runOnMainSync(()->{for(View root:WindowInspector.getGlobalWindowViews())if(root.hasWindowFocus()){View x=find(root,p);if(x!=null)result[0]=x;}});if(result[0]!=null)return result[0];settle();}throw new AssertionError("Normal control timed out");}
    private void tap(View v){settle();Rect r=new Rect();runOnMainSync(()->{int[] screen=new int[2];v.getGlobalVisibleRect(r);v.getRootView().getLocationOnScreen(screen);r.offset(screen[0],screen[1]);});long down=SystemClock.uptimeMillis();for(int a:new int[]{MotionEvent.ACTION_DOWN,MotionEvent.ACTION_UP}){MotionEvent e=MotionEvent.obtain(down,SystemClock.uptimeMillis(),a,r.centerX(),r.centerY(),0);e.setSource(InputDevice.SOURCE_TOUCHSCREEN);if(!getUiAutomation().injectInputEvent(e,true))throw new AssertionError("Touch rejected");e.recycle();SystemClock.sleep(50);}settle();}
    private void description(String s){tap(await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith(s)));}
    private void text(String s){tap(await(v->v instanceof TextView&&((TextView)v).getText().toString().startsWith(s)&&(v.isClickable()||v.getParent()instanceof AdapterView)));}
    private void nav(String s){description("打开功能导航");description("导航 · "+s);}
    private Object field(String name)throws Exception{java.lang.reflect.Field f=MainActivity.class.getDeclaredField(name);f.setAccessible(true);return f.get(activity);}
    private byte[] capture(){byte[][] bytes={null};runOnMainSync(()->{try{bytes[0]=((GameApplication)activity.getApplication()).host().capture();}catch(Exception e){throw new RuntimeException(e);}});return bytes[0];}
    private void awaitBytes(byte[] expected)throws Exception{long until=SystemClock.uptimeMillis()+60000;while(SystemClock.uptimeMillis()<until){if(Arrays.equals(expected,capture())){check(true,"normal read restores full health/source/World/RNG");return;}settle();}throw new AssertionError("Normal load differs from full saved bytes");}
    private void detail(int id)throws Exception{byte[] prior=capture();nav("武将");View clear=await(v->(v instanceof Button&&((Button)v).getText().toString().equals("清除"))||(v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("武将筛选")));boolean compact=clear.getContentDescription()!=null&&clear.getContentDescription().toString().startsWith("武将筛选");tap(clear);if(compact)text("清除全部筛选");DataTable<?> table=(DataTable<?>)await(v->v instanceof DataTable);Bundle query=new Bundle();query.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,SaveCodec.decode(prior).officer(id).name);boolean[] entered={false};runOnMainSync(()->entered[0]=table.search.performAccessibilityAction(AccessibilityNodeInfo.ACTION_SET_TEXT,query));check(entered[0],"normal officer search accepts authoritative saved name");settle();int[] position={-1};runOnMainSync(()->{for(int i=0;i<table.list.getAdapter().getCount();i++)if(table.list.getAdapter().getItemId(i)==id)position[0]=i;});check(position[0]>=0,"actual injured officer row");runOnMainSync(()->table.list.setSelection(position[0]));settle();View[] row={null};runOnMainSync(()->row[0]=table.list.getChildAt(position[0]-table.list.getFirstVisiblePosition()));check(row[0]!=null,"actual searched injured officer row visible");tap(row[0]);TextView view=(TextView)await(v->v instanceof TextView&&((TextView)v).getText().toString().contains("基础（统武智政魅）"));World w=SaveCodec.decode(prior);check(view.getText().toString().contains("负伤 · 剩"+w.contests.injuryTurns(id)+"旬"),"normal detail uses original recovery calendar");check(view.getText().toString().contains("武力 "+w.officer(id).war),"normal detail uses refreshed injured current ability");tap(await(v->v.getId()==android.R.id.button2&&v instanceof Button));check(Arrays.equals(prior,capture()),"health detail leaves all World/RNG bytes unchanged");}
    @Override public void onStart(){Bundle result=new Bundle();try{
        output=getTargetContext().getExternalFilesDir("session1-pc-health-"+evidenceId);output.mkdirs();activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));await(v->v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith("打开功能导航"));
        byte[] supplied=java.nio.file.Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath()),initial=capture();check(Arrays.equals(initial,SaveCodec.encode(SaveCodec.decode(supplied))),"actual ART complete policy restore");World control=SaveCodec.decode(initial);check(control.turn==5&&control.contests.injury(10116)==2,"actual saved fifth-turn original injury");detail(10116);
        nav("菜单");text("保存局面");text("槽位 3");text("覆盖存档");settle();check(Arrays.equals(initial,java.nio.file.Files.readAllBytes(new File(activity.getFilesDir(),"manual3.sg11").toPath())),"normal save persists all health/source/dual RNG");
        for(int target=6;target<=15;target++){nav("地图");check(control.nextTurn().ok,"independent complete campaign control");text("下一旬");text("执行");text("演示控制");text("跳过剩余演示");long until=SystemClock.uptimeMillis()+180000;while((SaveCodec.decode(capture()).turn<target||field("turnWork")!=null)&&SystemClock.uptimeMillis()<until)settle();check(Arrays.equals(SaveCodec.encode(control),capture()),"real normal turn full World and both RNGs · "+target);int expected=target<9?2:target<15?1:0;check(SaveCodec.decode(capture()).contests.injury(10116)==expected,"original month/native-ID recovery · "+target);}
        check(control.contests.injury(10116)==0,"fully recovered by original month6");nav("菜单");text("读取存档");text("槽位 3");text("读取存档");awaitBytes(initial);check(SaveCodec.decode(capture()).contests.injury(10116)==2,"normal load rolls health back exactly");java.nio.file.Files.write(new File(output,"actual-health-flow-final.sg11").toPath(),capture());result.putString("stream","PC SOURCE OPENING PASS health "+checks+" checks\n"+log);finish(Activity.RESULT_OK,result);
    }catch(Throwable e){result.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,result);}}
}
