package game.sanguo.core;

/** Generated by tools/content/export_pc_tactic_costs.py; native Scenario.s11 costs.
 * Getter4951a0, execution5a31d0 and debit58589c..5858b7 verified offline.
 * Native IDs are independent of project weapon/ship enum ordinals. */
final class PcTacticCosts {
    private PcTacticCosts() {}
    private static final int[] VALUES={15,20,25,15,20,30,10,15,25,15,20,25,10,10,10,10,10,10,15,0,0,0,0,0,0,0,0,0,0,0,0,0};
    static int at(int nativeId) { return VALUES[nativeId]; }
}
