package game.sanguo.core;

import java.util.*;

/** PC PK's 100 skills. A catalog entry is NOT a claim that its rules are implemented. */
public enum Skill {
    FEIJIANG("san11.feijiang","飞将"),
    DUNZOU("san11.dunzou","遁走"),
    QIANGXING("san11.qiangxing","强行"),
    CHANGQU("san11.changqu","长驱"),
    TUIJIN("san11.tuijin","推进"),
    CAODUO("san11.caoduo","操舵"),
    TAPO("san11.tapo","踏破"),
    YUNBAN("san11.yunban","运搬"),
    JIEDU("san11.jiedu","解毒"),
    SAOTAO("san11.saotao","扫讨"),
    WEIFENG("san11.weifeng","威风"),
    ANGYANG("san11.angyang","昂扬"),
    LIANZHAN("san11.lianzhan","连战"),
    JIXI("san11.jixi","急袭"),
    QIANGXI("san11.qiangxi","强袭"),
    LUANZHAN("san11.luanzhan","乱战"),
    GONGCHENG("san11.gongcheng","攻城"),
    JIJIAO("san11.jijiao","掎角"),
    BOFU("san11.bofu","捕缚"),
    JINGMIAO("san11.jingmiao","精妙"),
    QIANGDUO("san11.qiangduo","强夺"),
    XINGONG("san11.xingong","心攻"),
    QUZHU("san11.quzhu","驱逐"),
    SHECHENG("san11.shecheng","射程"),
    BAIMA("san11.baima","白马"),
    FUZUO("san11.fuzuo","辅佐"),
    QIANGJIANG("san11.qiangjiang","枪将"),
    JIJIANG("san11.jijiang","戟将"),
    GONGJIANG("san11.gongjiang","弓将"),
    QIJIANG("san11.qijiang","骑将"),
    SHUIJIANG("san11.shuijiang","水将"),
    YONGJIANG("san11.yongjiang","勇将"),
    SHENJIANG("san11.shenjiang","神将"),
    DOUSHEN("san11.doushen","斗神"),
    QIANGSHEN("san11.qiangshen","枪神"),
    JISHEN("san11.jishen","戟神"),
    GONGSHEN("san11.gongshen","弓神"),
    QISHEN("san11.qishen","骑神"),
    GONGSHEN_SIEGE("san11.gongshen_siege","工神"),
    SHUISHEN("san11.shuishen","水神"),
    BAWANG("san11.bawang","霸王"),
    JICHI("san11.jichi","疾驰"),
    SHESHOU("san11.sheshou","射手"),
    MENGZHE("san11.mengzhe","猛者"),
    BUQU("san11.buqu","不屈"),
    JINGANG("san11.jingang","金刚"),
    TIEBI("san11.tiebi","铁壁"),
    NUFA("san11.nufa","怒发"),
    TENGJIA("san11.tengjia","藤甲"),
    QIANGYUN("san11.qiangyun","强运"),
    XUELU("san11.xuelu","血路"),
    HUWEI("san11.huwei","护卫"),
    DAIFU("san11.daifu","待伏"),
    HUOGONG("san11.huogong","火攻"),
    YANDU("san11.yandu","言毒"),
    JILUE("san11.jilue","机略"),
    GUIJI("san11.guiji","诡计"),
    XUSHI("san11.xushi","虚实"),
    MIAOJI("san11.miaoji","妙计"),
    MIJI("san11.miji","秘计"),
    KANPO("san11.kanpo","看破"),
    DONGCHA("san11.dongcha","洞察"),
    HUOSHEN("san11.huoshen","火神"),
    SHENSUAN("san11.shensuan","神算"),
    BAICHU("san11.baichu","百出"),
    GUIMOU("san11.guimou","鬼谋"),
    LIANHUAN("san11.lianhuan","连环"),
    SHENMOU("san11.shenmou","深谋"),
    FANJI("san11.fanji","反计"),
    QINGGUO("san11.qingguo","倾国"),
    YAOSHU("san11.yaoshu","妖术"),
    GUIMEN("san11.guimen","鬼门"),
    GUILV("san11.guilv","规律"),
    CHENZHUO("san11.chenzhuo","沉着"),
    MINGJING("san11.mingjing","明镜"),
    ZOUYUE("san11.zouyue","奏乐"),
    SHIXIANG("san11.shixiang","诗想"),
    ZHUCHENG("san11.zhucheng","筑城"),
    TUNTIAN("san11.tuntian","屯田"),
    MINGSHENG("san11.mingsheng","名声"),
    NENGLI("san11.nengli","能吏"),
    FANZHI("san11.fanzhi","繁殖"),
    FAMING("san11.faming","发明"),
    ZAOCHUAN("san11.zaochuan","造船"),
    ZHIDAO("san11.zhidao","指导"),
    YANLI("san11.yanli","眼力"),
    LUNKE("san11.lunke","论客"),
    FUHAO("san11.fuhao","富豪"),
    MIDAO("san11.midao","米道"),
    ZHENGSHUI("san11.zhengshui","征税"),
    ZHENGSHOU("san11.zhengshou","征收"),
    QINWU("san11.qinwu","亲乌"),
    QINQIANG("san11.qinqiang","亲羌"),
    QINYUE("san11.qinyue","亲越"),
    QINMAN("san11.qinman","亲蛮"),
    WEIYA("san11.weiya","威压"),
    RENZHENG("san11.renzheng","仁政"),
    FENGSHUI("san11.fengshui","风水"),
    QIYUAN("san11.qiyuan","祈愿"),
    NEIZHU("san11.neizhu","内助");
    public final String id,label;
    Skill(String id,String label){this.id=id;this.label=label;}
    private static final Map<String,Skill> INDEX=new HashMap<>();
    static {for(Skill s:values())if(INDEX.put(s.id,s)!=null)throw new ExceptionInInitializerError(s.id);}
    public static Skill find(String id){return INDEX.get(id);}
    public static String label(String id){Skill s=find(id);return s!=null?s.label:"none".equals(id)?"无":id;}
}
